"""Generate cozmo-stack/tests/Cozmo.Protocol.Tests/WwiseStreamSourceOracle.cs from emu_stream.py's source-class scenarios.

    python re-analysis/tools/emu/emu_stream_expected.py > cozmo-stack/tests/Cozmo.Protocol.Tests/WwiseStreamSourceOracle.cs

Every value in the generated file is the engine's own output (the real source-class functions, the stream layer and the WAVE walker run under Unicorn by emu_stream.py);
none comes from the C#. The state strings have the format of the C# test helpers (StateString in WwiseStreamSourceTests).
"""
import emu_stream as m


CAPTURE = []
_real_out = m.out


def capture(case, **kw):
    kw['case'] = case
    CAPTURE.append(kw)


m.out = capture


def stream_part(s):
    if s is None:
        return 'str=none'
    nodes = ';'.join('%d/%d/%d/%d' % (n['start'], n['size'], n['offset'], n['state'] & 7) for n in s['nodes'])
    return 'str:b2d=%d b6c=%d b6e=%d b6d=%d f44=%d f48=%d f4c=%d f54=%d f58=%d p38=%d nodes=[%s]' % (
        s['b2d'], s['b6c'], s['b6e'], s['b6d'], s['f44'], s['f48'], s['f4c'], s['f54'], s['f58'], s['p38'], nodes)


def state_string(d, vorbis):
    parts = ['f10=%d f14=%d f18=%d f1c=%d f20=%d f24=%d f28=%d h38=%d stream=%d f40=%s f44=%d f48=%d f4c=%d f50=%d f54=%d f58=%d h5c=%d b5e=%d' % (
        d['f10'], d['f14'], d['f18'], d['f1c'], d['f20'], d['f24'], d['f28'], d['h38'], d['stream'], d['f40'], d['f44'], d['f48'], d['f4c'], d['f50'], d['f54'], d['f58'], d['h5c'], d['b5e']),
        'pbi158=%d pbi15c=%d pbi160=%d pbi161=%d pbi162=%d pbi1b4=%d pbi1bd=%d pbi1be=%d' % (
        d['pbi158'], d['pbi15c'], d['pbi160'], d['pbi161'], d['pbi162'], d['pbi1b4'], d['pbi1bd'], d['pbi1be'])]
    if vorbis:
        parts.append('v68=%d v80=%d va8=%d ve0=%d ve8=%d vf0=%d vf4=%d vf8=%d l2c=%d l2e=%d vorb=%s' % (
            d['v68'], 1 if d['v80'] else 0, d['va8'], d['ve0'], d['ve8'], d['vf0'], d['vf4'], d['vf8'], d['l2c'], d['l2e'], d['vorb']))
    parts.append('setups=[%s]' % ';'.join('%d/%d/%d/%d' % (x['size'], x['flag'], x['crc'], 1 if x['in_prefix'] else 0) for x in d['setups']))
    parts.append('cb=[%s]' % ';'.join('%d/%d/%d' % (c['playing_id'], c['estimate'], c['flag']) for c in d['callbacks']))
    parts.append('ob=[%s]' % ';'.join(str(x) for x in d['out_buffers']))
    parts.append(stream_part(d['str']))
    return ' '.join(parts)


def cs_string(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'


def main():
    m.sc_vorbis()
    m.sc_adpcm()
    m.sc_pcm()
    m.sc_vorbis_gate()
    m.sc_vorbis_gate7()
    print('// <auto-generated> by re-analysis/tools/emu/emu_stream_expected.py from the engine\'s own output (emu_stream.py): do not edit. </auto-generated>')
    print('namespace Cozmo.Protocol.Tests;')
    print('')
    print('/// <summary>The engine\'s results and states for the source-class scenarios of emu_stream.py (the real 0xAB22D4, 0xA7538C and their callees under Unicorn).</summary>')
    print('internal static class StreamSourceOracle')
    print('{')
    print('    public static readonly Dictionary<string, (int[] Results, string[] States)> Cases = new()')
    print('    {')
    for d in CAPTURE:
        case = d['case']
        if case.startswith('vorbis_gate7_'):
            continue
        vorbis = case.startswith('vorbis')
        if 'results' in d:
            results = d['results']
        elif 'result' in d:
            results = [d['result']]
        else:
            continue
        states = []
        for key in ('state_after_first', 'state', 'state_end'):
            if key in d:
                states.append(state_string(d[key], vorbis))
        print('        [%s] = (new[] { %s }, new[] { %s }),' % (cs_string(case), ', '.join(str(r) for r in results), ', '.join(cs_string(s) for s in states)))
    print('    };')
    print('')
    print('    /// <summary>The hand-built files of the PCM stream class (emu_stream.py sc_pcm): the RIFF bytes and the loop count of each scenario.</summary>')
    print('    public static readonly Dictionary<string, (string Blob, int Loop)> PcmCases = new()')
    print('    {')
    for d in CAPTURE:
        if d['case'].startswith('pcm_'):
            print('        [%s] = (%s, %d),' % (cs_string(d['case']), cs_string(d['blob']), d['loop']))
    print('    };')
    print('')
    print('    /// <summary>The buffering gate of 0xAB1550 (emu_stream.py vorbis_gate7): (decode reached, [state+0x28], [S+0x10], callbacks as playingId/estimate/flag).</summary>')
    print('    public static readonly Dictionary<string, (bool Reached, int Code, int F10, string Callbacks)> Gate7 = new()')
    print('    {')
    for d in CAPTURE:
        if d['case'].startswith('vorbis_gate7_'):
            cb = ';'.join('%d/%d/%d' % tuple(c) for c in d['callbacks'])
            print('        [%s] = (%s, %d, %d, %s),' % (cs_string(d['case'][len('vorbis_gate7_'):]), 'true' if d['reached'] else 'false', d['code'], d['f10'], cs_string(cb)))
    print('    };')
    print('}')


if __name__ == '__main__':
    main()
