// <auto-generated>
//     Generated by re-analysis/tools/generate_animation_triggers.py. Do not edit by hand.
//
//     Source: unity/scripts/csharp/Anki.Cozmo/ReactionTrigger.cs, decompiled from the official
//     3.4.0-1204 APK. Declared `: byte`, so these ordinals go on the wire as written.
//     Count and NoneTrigger are sentinels and are left out.
// </auto-generated>

namespace Cozmo.Robot.Behavior;

/// <summary>
/// The things the shipped engine treats as worth reacting to. Anki's own set, not ours:
/// 21 of them. What a reaction then plays is decided by <see cref="ReactionTable"/>.
/// </summary>
public enum ReactionTrigger : byte
{
    CliffDetected,
    CubeMoved,
    FacePositionUpdated,
    FistBump,
    Frustration,
    Hiccup,
    MotorCalibration,
    NoPreDockPoses,
    ObjectPositionUpdated,
    PlacedOnCharger,
    PetInitialDetection,
    RobotFalling,
    RobotPickedUp,
    RobotPlacedOnSlope,
    ReturnedToTreads,
    RobotOnBack,
    RobotOnFace,
    RobotOnSide,
    RobotShaken,
    Sparked,
    UnexpectedMovement,
}
