"""Extract the engine's compiled-in fiducial-marker nearest-neighbour library into one binary blob.

`Anki::Vision::VisionMarker::GetNearestNeighborLibrary` (0x0089ED1C in libcozmoEngine.so 3.4.0-1204)
constructs a `NearestNeighborLibrary` from data linked into the binary:

    images            u8 [598][1024]   @ 0x00C9BCA8   one probe image per row (32x32 probe grid)
    images2           u8 [598][1024]   @ 0x00D314A8   second array passed to the ctor; never copied
                                                      into the database Mat, so not extracted
    labels            u16[598]         @ 0x00DC6CA8   library row -> label (0..149; 149 = INVALID)
    labelToCode       u32[150]         @ 0x00DC7154   label -> Vision::MarkerType code
    cornerReorder     u32[150][4]      @ 0x00DC73AC   label -> how to reorder the quad's corners
    orientationDeg    f32[150]         @ 0x00DC7D0C   label -> marker rotation in degrees

and the probe geometry `GetProbeValues` samples with (exported data symbols, all s16 fixed point with
NUM_FRACTIONAL_BITS = 15, i.e. value / 32768 is the position within the unit marker square):

    ProbeCenters_X/Y        s16[1024]  @ 0x00DC7FEC / 0x00DC87EC   the 32x32 probe grid
    ProbePoints_X/Y         s16[5]     @ 0x00DC7F74 / 0x00DC7F7E   the 5 offsets averaged per probe
    ThresholdDarkProbe_X/Y  s16[12]    @ 0x00DC7F8C / 0x00DC7FA4   the 12 border probes (dark)
    ThresholdBrightProbe_X/Y s16[12]   @ 0x00DC7FBC / 0x00DC7FD4   the 12 interior probes (bright)

Every fact above was read from the constructor's immediates and the tables it indexes; nothing here
is inferred. The blob is Anki's data and is NOT committed: it is written to
cozmo-stack/src/Cozmo.Robot/Vision/Data/marker_nn_library.bin (git-ignored), embedded in Cozmo.Robot when
present, and regenerated by the build (Cozmo.Robot.csproj target ExtractMarkerLibrary) or by hand from the
user's own shared object:

    python re-analysis/tools/extract_marker_library.py [path/to/libcozmoEngine.so] [--check]

Layout of the blob (little-endian):

    magic      8 bytes  "CZMKNN02"
    numImages  u32      598
    numProbes  u32      1024
    numLabels  u32      150
    reserved   u32      0
    images     u8 [numImages * numProbes]
    labels     u16[numImages]
    codes      u32[numLabels]
    reorder    u32[numLabels * 4]
    orient     f32[numLabels]
    centersX   s16[numProbes]
    centersY   s16[numProbes]
    pointsX    s16[5]
    pointsY    s16[5]
    darkX      s16[12]
    darkY      s16[12]
    brightX    s16[12]
    brightY    s16[12]
"""
import hashlib
import pathlib
import struct
import sys

import lief

ROOT = pathlib.Path(__file__).resolve().parents[2]
DEFAULT_SO = (ROOT / "resources" / "lib" / "armeabi-v7a" / "libcozmoEngine.so")
OUT = ROOT / "cozmo-stack" / "src" / "Cozmo.Robot" / "Vision" / "Data" / "marker_nn_library.bin"

NUM_IMAGES, NUM_PROBES, NUM_LABELS = 598, 1024, 150
# SHA-256 of the blob this script writes from libcozmoEngine.so 3.4.0-1204 (the build the project targets).
EXPECTED_SHA256 = "1b7166ac37b166975f0e5313a3d4486ebae73010e42ffb89bbd0d4536a29c81d"
EXPECTED_SIZE = 621384
IMAGES, LABELS, CODES, REORDER, ORIENT = 0x00C9BCA8, 0x00DC6CA8, 0x00DC7154, 0x00DC73AC, 0x00DC7D0C
CENTERS_X, CENTERS_Y, POINTS_X, POINTS_Y = 0x00DC7FEC, 0x00DC87EC, 0x00DC7F74, 0x00DC7F7E
DARK_X, DARK_Y, BRIGHT_X, BRIGHT_Y = 0x00DC7F8C, 0x00DC7FA4, 0x00DC7FBC, 0x00DC7FD4


def read(so, addr, n):
    data = bytes(so.get_content_from_virtual_address(addr, n))
    if len(data) != n:
        raise SystemExit(f"short read at 0x{addr:08X}: wanted {n}, got {len(data)}")
    return data


def build(so_path):
    so = lief.parse(str(so_path))
    images = read(so, IMAGES, NUM_IMAGES * NUM_PROBES)
    labels = read(so, LABELS, NUM_IMAGES * 2)
    codes = read(so, CODES, NUM_LABELS * 4)
    reorder = read(so, REORDER, NUM_LABELS * 16)
    orient = read(so, ORIENT, NUM_LABELS * 4)

    # sanity: labels within range, every code a MarkerType (0..39), reorder entries are permutations
    lab = struct.unpack("<%dH" % NUM_IMAGES, labels)
    assert max(lab) == NUM_LABELS - 1 and min(lab) == 0, lab[:8]
    cod = struct.unpack("<%dI" % NUM_LABELS, codes)
    assert max(cod) <= 39, cod
    reo = struct.unpack("<%dI" % (NUM_LABELS * 4), reorder)
    for i in range(NUM_LABELS):
        assert sorted(reo[4 * i:4 * i + 4]) == [0, 1, 2, 3], (i, reo[4 * i:4 * i + 4])
    ori = struct.unpack("<%df" % NUM_LABELS, orient)
    assert set(ori) <= {0.0, 90.0, 180.0, 270.0}, set(ori)

    probes = b"".join(read(so, a, n * 2) for a, n in (
        (CENTERS_X, NUM_PROBES), (CENTERS_Y, NUM_PROBES), (POINTS_X, 5), (POINTS_Y, 5),
        (DARK_X, 12), (DARK_Y, 12), (BRIGHT_X, 12), (BRIGHT_Y, 12)))
    cx = struct.unpack("<%dh" % NUM_PROBES, probes[:NUM_PROBES * 2])
    assert 0 < min(cx) and max(cx) < 32768, (min(cx), max(cx))

    header = b"CZMKNN02" + struct.pack("<IIII", NUM_IMAGES, NUM_PROBES, NUM_LABELS, 0)
    return header + images + labels + codes + reorder + orient + probes


def main(argv):
    so_path = DEFAULT_SO
    check = "--check" in argv
    for a in argv:
        if a != "--check":
            so_path = pathlib.Path(a)
    blob = build(so_path)
    digest = hashlib.sha256(blob).hexdigest()
    if digest != EXPECTED_SHA256 or len(blob) != EXPECTED_SIZE:
        print(f"WARNING: extracted library sha256 {digest} ({len(blob)} bytes) is not the 3.4.0-1204 library "
              f"({EXPECTED_SHA256}, {EXPECTED_SIZE} bytes); is {so_path} the right build?")
    if check:
        if not OUT.exists():
            raise SystemExit(f"{OUT} missing")
        if OUT.read_bytes() != blob:
            raise SystemExit(f"{OUT} differs from the library in {so_path}")
        print(f"ok: {OUT.name} matches ({len(blob)} bytes, sha256 {digest})")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_bytes(blob)
    print(f"wrote {OUT} ({len(blob)} bytes, sha256 {digest}); this file is git-ignored (Anki's data) and regenerated by the build")
    return 0 if digest == EXPECTED_SHA256 else 3


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
