"""Generate cozmo-stack/src/Cozmo.Protocol/Generated/MessageCatalog.cs from the official tag map + size comparison.
usage: python gen_message_catalog.py <re-analysis/protocol dir> <cozmo-stack root>"""
import json,sys,os
P,ROOT=sys.argv[1],sys.argv[2]
tags=json.load(open(os.path.join(P,"robot_protocol_official_tags.json")))
rows=json.load(open(os.path.join(P,"robot_msg_compare.json")))
sizes={r[0]:r[4] for r in rows}; pyn={r[0]:r[5] for r in rows}
# Size() was not a trivial constant for these, but the Unpack field widths (robot_msg_field_widths_official.json) are fixed:
OVERRIDE={0xF0:(91,"fixed by Unpack field widths 12+20+16+12+12+4+4+8+2+1")}
def pascal(s): return s[0].upper()+s[1:]
entries=[]; seen={}
for u in ("EngineToRobot","RobotToEngine"):
    for t,(member,typ) in sorted(((int(k),v) for k,v in tags[u].items())):
        typ=typ.replace("&&",""); name=pascal(member)
        if name in seen: name=name+("FromRobot" if u=="RobotToEngine" else "ToRobot")
        seen[name]=1
        sz=sizes.get(t,"?"); szv=-1 if sz in("variable","?") else int(sz); note=""
        if t in OVERRIDE: szv,note=OVERRIDE[t][0],"; "+OVERRIDE[t][1]
        entries.append((t,name,typ,u,szv,pyn.get(t,'-'),("variable" if szv<0 else str(szv))+note))
L=["// <auto-generated> by re-analysis/tools/gen_message_catalog.py from robot_protocol_official_tags.json + robot_msg_compare.json",
"// (libcozmoEngine.so 3.4.0-1204). Tag numbers, member names and CLAD type names are the OFFICIAL ones recovered from the engine.",
"// OfficialSize is the constant returned by <Type>::Size() (or a documented override); -1 = variable-length.",
"#nullable enable","namespace Cozmo.Protocol;","",
"/// <summary>Official EngineToRobot / RobotToEngine union tags (u8). 0x01-0xAF engine->robot, 0xB0-0xFF robot->engine.</summary>",
"public enum RobotMessageId : byte","{"]
for t,name,typ,u,szv,py,sz in entries:
    L.append(f"    /// <summary>{typ} ({u}); official size {sz}; PyCozmo name: {py}</summary>"); L.append(f"    {name} = 0x{t:02X},")
L+=["}","","public enum MessageDirection { EngineToRobot, RobotToEngine }","",
"public sealed record MessageInfo(RobotMessageId Id, string Member, string CladType, MessageDirection Direction, int OfficialSize, string PyCozmoName);","",
"public static class MessageCatalog","{","    public static readonly IReadOnlyDictionary<RobotMessageId, MessageInfo> ById = new Dictionary<RobotMessageId, MessageInfo>","    {"]
for t,name,typ,u,szv,py,sz in entries:
    L.append(f'        [RobotMessageId.{name}] = new(RobotMessageId.{name}, "{name}", "{typ}", MessageDirection.{u}, {szv}, "{py}"),')
L+=["    };","","    public static MessageInfo? Lookup(byte tag) => ById.TryGetValue((RobotMessageId)tag, out var i) ? i : null;",
f"    public const int EngineToRobotCount = {sum(1 for e in entries if e[3]=='EngineToRobot')};",
f"    public const int RobotToEngineCount = {sum(1 for e in entries if e[3]=='RobotToEngine')};","}"]
out=os.path.join(ROOT,"src","Cozmo.Protocol","Generated","MessageCatalog.cs")
open(out,"w",encoding="utf-8").write("\n".join(L)+"\n"); print("wrote",out,len(entries),"entries")
