"""Generate the AnimationTrigger enum from the decompiled Unity authority.

The enum is Anki's, not ours: the names and their order come from
unity/scripts/csharp/Anki.Cozmo/AnimationTrigger.cs in the official 3.4.0 APK. Declaration order is the
ordinal, because the decompiled enum assigns no explicit values.

    python re-analysis/tools/generate_animation_triggers.py           # write
    python re-analysis/tools/generate_animation_triggers.py --check   # verify, for CI

Cross-check performed on every run: every CladEvent in the OBB's AnimationTriggerMap.json must name a
trigger this enum defines. A mismatch means one of the two inputs is from a different build.
"""
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
CSHARP = ROOT / "unity" / "scripts" / "csharp" / "Anki.Cozmo" / "AnimationTrigger.cs"
TRIGGER_MAP = (ROOT / "re-analysis" / "obb" / "assets" / "cozmo_resources" / "assets"
               / "animationGroupMaps" / "AnimationTriggerMap.json")
OUT = ROOT / "cozmo-stack" / "src" / "Cozmo.Robot" / "Behavior" / "AnimationTrigger.g.cs"


def read_triggers():
    src = CSHARP.read_text(encoding="utf-8")
    body = src.split("{", 1)[1].rsplit("}", 1)[0]
    names = []
    for line in body.splitlines():
        line = line.strip().rstrip(",").strip()
        if not line or line.startswith("//"):
            continue
        if "=" in line:
            raise SystemExit(f"unexpected explicit value in the enum: {line!r}")
        names.append(line)
    if not names or names[-1] != "Count":
        raise SystemExit("expected the enum to end with Count")
    return names[:-1]


def cross_check(names):
    if not TRIGGER_MAP.exists():
        return "AnimationTriggerMap.json not present; skipped the cross-check"
    pairs = json.loads(TRIGGER_MAP.read_text(encoding="utf-8"))["Pairs"]
    mapped = {p["CladEvent"] for p in pairs}
    missing = sorted(mapped - set(names))
    if missing:
        raise SystemExit(f"{len(missing)} mapped triggers are not in the enum, e.g. {missing[:5]}")
    return f"all {len(mapped)} mapped triggers exist in the enum; {len(names) - len(mapped)} triggers have no group"


def render(names, note):
    lines = [
        "// <auto-generated>",
        "//     Generated by re-analysis/tools/generate_animation_triggers.py. Do not edit by hand.",
        "//",
        "//     Source: unity/scripts/csharp/Anki.Cozmo/AnimationTrigger.cs, decompiled from the official",
        "//     3.4.0-1204 APK. The names and their order are Anki's; declaration order is the ordinal,",
        "//     because the decompiled enum assigns no explicit values.",
        f"//     Cross-check: {note}",
        "// </auto-generated>",
        "",
        "namespace Cozmo.Robot.Behavior;",
        "",
        "/// <summary>",
        "/// Every animation trigger the shipped engine defines: the names it uses to ask for an animation",
        f"/// without naming a clip. {len(names)} of them, mapped to animation groups by AnimationTriggerMap.json.",
        "/// </summary>",
        "public enum AnimationTrigger",
        "{",
    ]
    lines += [f"    {n}," for n in names]
    lines += ["}", ""]
    return "\n".join(lines)


def main():
    names = read_triggers()
    note = cross_check(names)
    text = render(names, note)
    if "--check" in sys.argv:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current.replace("\r\n", "\n") != text:
            print(f"OUT OF DATE: {OUT}")
            return 1
        print(f"up to date: {len(names)} triggers; {note}")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUT} with {len(names)} triggers; {note}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
