namespace Cozmo.Robot.Vision.Jpeg;

// fidelity: M3-001, M3-018
// Static tables of the shipped decoder (libopencv_imgcodecs.so): the zigzag order (0xCECF0, J29), the size-specific natural
// orders used by short DQT payloads (J48), the arithmetic-coding probability table (0xCF328, J63) and the default MJPEG
// Huffman tables loader data (VA 0x175018, the default-table row of 20261010-jpeg-defaults-and-save-rows.md).
internal static class JpegTables
{
    /// <summary>jpeg_natural_order: 64 entries then 16 copies of 63 (malformed overruns use the padded table, not a bounds error, J29).</summary>
    public static readonly int[] NaturalOrder8 =
    {
        0, 1, 8, 16, 9, 2, 3, 10, 17, 24, 32, 25, 18, 11, 4, 5,
        12, 19, 26, 33, 40, 48, 41, 34, 27, 20, 13, 6, 7, 14, 21, 28,
        35, 42, 49, 56, 57, 50, 43, 36, 29, 22, 15, 23, 30, 37, 44, 51,
        58, 59, 52, 45, 38, 31, 39, 46, 53, 60, 61, 54, 47, 55, 62, 63,
        63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63,
    };

    private static readonly int[]?[] Reduced = new int[]?[9];

    /// <summary>
    /// jpeg_natural_order2..7: the zigzag of the top-left n x n block in an 8-wide layout, padded with 63 (n*n + 16 entries).
    /// Generated by the zigzag rule and compared in the tests with the tables dumped from the shipped .so (VA 0xCE938,
    /// 0xCE988, 0xCE9F0, 0xCEA70, 0xCEB18, 0xCEBE8).
    /// </summary>
    public static int[] NaturalOrder(int n)
    {
        if (n == 8) return NaturalOrder8;
        lock (Reduced)
        {
            if (Reduced[n] != null) return Reduced[n]!;
            var t = new int[n * n + 16];
            int k = 0;
            for (int s = 0; s <= 2 * (n - 1); s++)
            {
                if ((s & 1) == 0)
                {
                    // even diagonals run up-right in the 8x8 zigzag (0,1,8,16,9,2,...): start at the bottom
                    int row = Math.Min(s, n - 1);
                    int col = s - row;
                    while (row >= 0 && col < n) { t[k++] = row * 8 + col; row--; col++; }
                }
                else
                {
                    int col = Math.Min(s, n - 1);
                    int row = s - col;
                    while (col >= 0 && row < n) { t[k++] = row * 8 + col; row++; col--; }
                }
            }
            for (; k < t.Length; k++) t[k] = 63;
            Reduced[n] = t;
            return t;
        }
    }

    /// <summary>
    /// jpeg_zigzag_order2..8 (J111): entry [v - 1, h - 1] is the zigzag index of coefficient (row v - 1, column h - 1) of the n x n block, the
    /// number of coefficients a component of scaled size h x v needs before the reduced sequential decoder may skip the rest (limit = entry + 1,
    /// J109). The shipped tables (VA 0xCEFF0, 0xCF000, 0xCF028, 0xCF068, 0xCF0D0, 0xCF160, 0xCF228) are exactly the inverse of the size-n
    /// natural order; the tests compare them with the values dumped from the .so.
    /// </summary>
    public static int ZigzagLimit(int n, int v, int h)
    {
        var order = NaturalOrder(n);
        int pos = (v - 1) * 8 + (h - 1);
        for (int i = 0; i < n * n; i++)
            if (order[i] == pos) return i;
        throw new ArgumentOutOfRangeException(nameof(v));
    }

    /// <summary>The arithmetic decoder's probability table: 113 states plus the fixed bin (word i = Qe &lt;&lt; 16 | next_lps &lt;&lt; 8 | switch &lt;&lt; 7 | next_mps), J63.</summary>
    public static readonly uint[] ArithTable =
    {
        0x5A1D0181, 0x2586020E, 0x11140310, 0x080B0412, 0x03D80514, 0x01DA0617, 0x00E50719, 0x006F081C, 0x0036091E, 0x001A0A21, 0x000D0B23, 0x00060C09, 0x00030D0A, 0x00010D0C, 0x5A7F0F8F, 0x3F251024,
        0x2CF21126, 0x207C1227, 0x17B91328, 0x1182142A, 0x0CEF152B, 0x09A1162D, 0x072F172E, 0x055C1830, 0x04061931, 0x03031A33, 0x02401B34, 0x01B11C36, 0x01441D38, 0x00F51E39, 0x00B71F3B, 0x008A203C,
        0x0068213E, 0x004E223F, 0x003B2320, 0x002C0921, 0x5AE125A5, 0x484C2640, 0x3A0D2741, 0x2EF12843, 0x261F2944, 0x1F332A45, 0x19A82B46, 0x15182C48, 0x11772D49, 0x0E742E4A, 0x0BFB2F4B, 0x09F8304D,
        0x0861314E, 0x0706324F, 0x05CD3330, 0x04DE3432, 0x040F3532, 0x03633633, 0x02D43734, 0x025C3835, 0x01F83936, 0x01A43A37, 0x01603B38, 0x01253C39, 0x00F63D3A, 0x00CB3E3B, 0x00AB3F3D, 0x008F203D,
        0x5B1241C1, 0x4D044250, 0x412C4351, 0x37D84452, 0x2FE84553, 0x293C4654, 0x23794756, 0x1EDF4857, 0x1AA94957, 0x174E4A48, 0x14244B48, 0x119C4C4A, 0x0F6B4D4A, 0x0D514E4B, 0x0BB64F4D, 0x0A40304D,
        0x583251D0, 0x4D1C5258, 0x438E5359, 0x3BDD545A, 0x34EE555B, 0x2EAE565C, 0x299A575D, 0x25164756, 0x557059D8, 0x4CA95A5F, 0x44D95B60, 0x3E225C61, 0x38245D63, 0x32B45E63, 0x2E17565D, 0x56A860DF,
        0x4F466165, 0x47E56266, 0x41CF6367, 0x3C3D6468, 0x375E5D63, 0x52316669, 0x4C0F676A, 0x4639686B, 0x415E6367, 0x56276AE9, 0x50E76B6C, 0x4B85676D, 0x55976D6E, 0x504F6B6F, 0x5A106FEE, 0x55226D70,
        0x59EB6FF0, 0x5A1D7171,
    };
}
