using System.IO.Compression;
using System.Text;
using Cozmo.Robot.Animation.Wwise;
using Xunit;

namespace Cozmo.Protocol.Tests;

/// <summary>
/// M6-025 / M6-022 (C33.3): the source-class stream functions (0xAB22D4, 0xAB2088, 0xAB1C04, 0xAB2BFC, 0xAB12B4, 0xAB1550's gate, 0xA7538C, 0xA74564, 0xA7482C, 0xA74970, 0xA746A8, 0xA74C80, 0xA74E00) and the voice
/// pass retry that drives them. Every expected state and result is the engine's own: the real source-class functions, the stream layer and the WAVE walker 0x9CD340 run under Unicorn on the shipped Vorbis
/// media (re-analysis/tools/emu/emu_stream.py; the strings in WwiseStreamSourceOracle.cs are generated by emu_stream_expected.py from that output); none comes from running this implementation. The bodies C33 does not
/// adopt are stood in on BOTH sides by the same stand-in (the codebook cache 0xAB2D74, the output-buffer allocation 0xAB3264, the ADPCM header parse 0xA73ABC) or by a validated double (the walker, test W1).
/// </summary>
public class WwiseStreamSourceTests
{
    // ------------------------------------------------------------------ fixtures

    private static byte[]? ReadWem(string name)
    {
        if (WwiseAssets.SoundDir is not { } dir) { Assert.Fail("the shipped re-analysis/obb/assets/cozmo_resources/sound/AudioAssets.zip is not present: these tests do not pass silently without it"); return null; }
        using var zip = ZipFile.OpenRead(Path.Combine(dir, "AudioAssets.zip"));
        var entry = zip.GetEntry(name) ?? throw new InvalidOperationException(name);
        using var s = entry.Open();
        using var ms = new MemoryStream();
        s.CopyTo(ms);
        return ms.ToArray();
    }

    private const string VorbisName = "English(US)/99908739.wem";
    private const string AdpcmName = "998061257.wem";

    private static uint Crc32(byte[] data)
    {
        uint crc = 0xFFFFFFFF;
        foreach (byte b in data)
        {
            crc ^= b;
            for (int i = 0; i < 8; i++) crc = (crc & 1) != 0 ? (crc >> 1) ^ 0xEDB88320 : crc >> 1;
        }
        return ~crc;
    }

    /// <summary>
    /// A TEST DOUBLE of the walker 0x9CD340 (not read by C33, so production has no body): the RIFF chunk walk as emu_stream.py's sc_walker shows it for the shipped media. It is validated against the engine's own
    /// results by test W1. Results: 0x1F for a null pointer or length 0; 7 when the bytes are not a WAVE file or the data chunk comes before a format chunk; 8 when a chunk header or a non-data chunk is not inside the
    /// length; 1 at the data chunk. A "smpl" chunk with one loop gives the loop start / end; a cue chunk (the marker list) is not modelled and throws.
    /// </summary>
    internal static WwiseWaveWalk Walker(WwiseBytePtr data, uint length)
    {
        if (data.IsNull || length == 0) return new WwiseWaveWalk { Result = 0x1F };
        var a = data.Array!;
        int b = data.Index;
        if (length < 12 || a[b] != 'R' || a[b + 1] != 'I' || a[b + 2] != 'F' || a[b + 3] != 'F' || a[b + 8] != 'W' || a[b + 9] != 'A' || a[b + 10] != 'V' || a[b + 11] != 'E')
            return new WwiseWaveWalk { Result = 7 };
        uint pos = 12;
        WwiseBytePtr fmt = default;
        uint w24 = 0, w28 = 0;
        while (true)
        {
            if (pos + 8 > length) return new WwiseWaveWalk { Result = 8 };
            string id = Encoding.ASCII.GetString(a, b + (int)pos, 4);
            uint size = BitConverter.ToUInt32(a, b + (int)pos + 4);
            if (id == "data")
            {
                if (fmt.IsNull) return new WwiseWaveWalk { Result = 7 };
                return new WwiseWaveWalk { Result = 1, Format = fmt, DataSize1C = size, DataOffset20 = pos + 8, Word24 = w24, Word28 = w28 };
            }
            if (pos + 8 + size > length) return new WwiseWaveWalk { Result = 8 };
            if (id == "fmt ") fmt = data.Add((int)pos + 8);
            else if (id == "smpl")
            {
                if (BitConverter.ToUInt32(a, b + (int)pos + 8 + 0x1C) != 1) throw new NotSupportedException("test double: only a single smpl loop");
                w24 = BitConverter.ToUInt32(a, b + (int)pos + 8 + 0x2C);
                w28 = BitConverter.ToUInt32(a, b + (int)pos + 8 + 0x30);
            }
            else if (id == "cue ") throw new NotSupportedException("test double: the marker list is not modelled");
            pos += 8 + size + (size & 1);
        }
    }

    private sealed class SourceRig
    {
        public readonly StreamRig Rig;
        public readonly WwisePlayingInstance Pbi;
        public readonly WwiseBankMemory Memory = new();
        public readonly byte[]? Prefix;
        public readonly List<string> Setups = new();
        public readonly List<string> Callbacks = new();
        public readonly List<int> OutBuffers = new();
        public readonly List<uint> ParseLefts = new();
        public bool OutFail;
        public readonly bool Vorbis;
        public readonly byte[] Wem;
        public WwiseVorbisStreamSource? V;
        public WwisePcmAdpcmStreamSource? A;
        public WwiseStreamSourceSeams Seams = null!;
        public readonly WwiseSourceBlock150 Block;
        public WwiseStreamSourceBase Src => (WwiseStreamSourceBase?)V ?? A!;

        public SourceRig(byte[] wem, int prefixLen, bool vorbis = true, ushort loop = 1, byte flags1BD = 0x44, uint flags4 = 0, uint priorityBits = 0x3F800000, byte bits0c = 0x03,
            uint stale = 0, bool noWalker = false, bool noCodebook = false, bool noCallback = false, bool noParse = false, byte bits0d = 0x02, string? name = null)
        {
            Wem = wem;
            Vorbis = vorbis;
            uint sourceId = vorbis ? 99908739u : 998061257u;
            uint plugin = vorbis ? 0x00040001u : 0x00020001u;
            Rig = new StreamRig(fileSize: wem.Length, io: new ManualIo { StaleQueryWord = stale }, content: wem);
            Pbi = new WwisePlayingInstance(new WwisePlayInitParams { PlayingId = 0x1234, TargetNodeId = 1 }, 1,
                new WwiseSourceDescriptor(plugin, 1, sourceId, 0, 0), new byte[0x44], null, continuous: false);
            Pbi.Word15C = 0;                                                                               // the oracle's PBI image is zero-filled (no PBI constructor ran)
            Pbi.LoopCount1B8 = loop;
            Pbi.Flags1BD = flags1BD;
            Pbi.Flags4 = flags4;
            Pbi.Priority1C0 = BitConverter.Int32BitsToSingle(unchecked((int)priorityBits));
            if (prefixLen != 0)
            {
                uint address = Memory.Allocate(prefixLen + 16)!.Value;
                Prefix = Memory.Block(address);
                Array.Copy(wem, Prefix, prefixLen);
                Pbi.Word1DC = address;
                Pbi.Word1E0 = (uint)prefixLen;
            }
            Block = new WwiseSourceBlock150 { SourceId04 = sourceId, Bits0C = bits0c, Bits0D = bits0d, Name10 = name, Plugin14 = plugin };
            Seams = new WwiseStreamSourceSeams
            {
                Memory = Memory,
                WaveWalker9CD340 = noWalker ? null : Walker,
                CodebookCacheAB2D74 = noCodebook ? null : (src, ptr, size, flag) =>
                {
                    var bytes = new byte[size];
                    Array.Copy(ptr.Array!, ptr.Index, bytes, 0, size);
                    Setups.Add($"{size}/{flag}/{Crc32(bytes)}/{(ReferenceEquals(ptr.Array, Prefix) ? 1 : 0)}");
                    return new object();
                },
                BufferingCallbackA059D8 = noCallback ? null : (pid, src, info) => Callbacks.Add($"{pid}/{info.Estimate}/{info.Flag}"),
                OutputBuffersFailAB3264 = ch => { OutBuffers.Add(ch); return OutFail; },
                ParseHeaderPcmAdpcm = noParse ? null : (src, data) =>
                {
                    ParseLefts.Add(src.Left44);
                    src.HeaderSize20 = 64; src.DataSize1C = (uint)(wem.Length - 64); src.TotalSamples14 = 20000;      // the stand-in of 0xA73ABC on both sides
                    return 1;
                },
            };
            if (vorbis) V = new WwiseVorbisStreamSource(Rig.Manager, Pbi, Block, Seams);
            else A = new WwisePcmAdpcmStreamSource(Rig.Manager, Pbi, Block, Seams);
        }

        public int Start() => V is not null ? V.StartStreamAB22D4() : A!.StartStreamA7538C();

        public void Io(uint start, uint size)
        {
            var s = Src.Stream3C!;
            s.RunOpen963890();
            Rig.Deliver(s, start, size);
        }

        private string F40()
        {
            var p = Src.Data40;
            if (p.IsNull) return "0";
            return ReferenceEquals(p.Array, Prefix) ? p.Index.ToString() : "buf";
        }

        private static string Nodes(WwiseAutoStream s) => string.Join(";", s.Nodes.Select(n => $"{n.Buffer!.Start}/{n.Buffer.Size}/{n.Offset}/{n.State & 7}"));

        public string State()
        {
            var src = Src;
            var parts = new List<string>
            {
                $"f10={src.Flags10} f14={src.TotalSamples14} f18={src.SampleBase18} f1c={src.DataSize1C} f20={src.HeaderSize20} f24={src.Word24} f28={src.Word28} h38={src.LoopCount38} stream={(src.Stream3C is null ? 0 : 1)} f40={F40()} f44={src.Left44} f48={src.FileOffset48} f4c={src.StreamOffset4C} f50={src.Skip50} f54={src.LoopStartByte54} f58={src.LoopEndByte58} h5c={src.LoopCounter5C} b5e={src.Bits5E & 0x1F}",
                $"pbi158={Pbi.SourceFormat158} pbi15c={Pbi.Word15C} pbi160={Pbi.Byte160} pbi161={Pbi.Byte161} pbi162={Pbi.Byte162} pbi1b4={Pbi.Word1B4} pbi1bd={Pbi.Flags1BD} pbi1be={Pbi.Flags1BE}",
            };
            if (V is { } v)
                parts.Add($"v68={v.State68} v80={(v.CodebookHandle80 is null ? 0 : 1)} va8={v.ChannelWordA8} ve0={v.SampleRateE0} ve8={v.SeekCollected} vf0={v.SetupPayloadCollected} vf4={v.SetupPrefixCollected} vf8={(v.SetupOwned ? 1 : 0)} l2c={v.LoopStateSkip2C} l2e={v.LoopStateWord2E} vorb={Convert.ToHexString(v.VorbBlock).ToLowerInvariant()}");
            parts.Add($"setups=[{string.Join(";", Setups)}]");
            parts.Add($"cb=[{string.Join(";", Callbacks)}]");
            parts.Add($"ob=[{string.Join(";", OutBuffers)}]");
            var s = src.Stream3C;
            parts.Add(s is null ? "str=none" :
                $"str:b2d={s.Flags2D} b6c={s.Granted6C} b6e={s.Flags6E} b6d={s.Byte6D} f44={BitConverter.SingleToUInt32Bits(s.Throughput44)} f48={s.LoopStart48} f4c={s.LoopEnd4C} f54={s.Buffered54} f58={s.MinBuffer58} p38={s.Position38} nodes=[{Nodes(s)}]");
            return string.Join(" ", parts);
        }
    }

    private static (int[] Results, string[] States) Oracle(string name) => StreamSourceOracle.Cases[name];

    // ------------------------------------------------------------------ W1: the walker double against the engine's walker

    [Fact]
    public void W1_TheWalkerDoubleReproducesTheEnginesWalkerOnTheShippedMedia()
    {
        // emu_stream.py walker / walker_degenerate (the real 0x9CD340 under Unicorn): {result, fmt offset, data offset, data size, loop words}. The double is test-only: C33 does not adopt the walker.
        var plain = ReadWem(VorbisName);
        if (plain is null) return;
        foreach (var (length, result) in new[] { (9289, 1), (600, 1), (200, 1), (90, 8) })
        {
            var w = Walker(new WwiseBytePtr(plain, 0), (uint)length);
            Assert.Equal(result, w.Result);
            if (result == 1) Assert.Equal((20, 94u, 9195u, 0u, 0u), (w.Format.Index, w.DataOffset20, w.DataSize1C, w.Word24, w.Word28));
        }
        var big = ReadWem("1000323750.wem")!;
        var wb = Walker(new WwiseBytePtr(big, 0), (uint)big.Length);
        Assert.Equal((1, 94u, 4120122u), (wb.Result, wb.DataOffset20, wb.DataSize1C));
        Assert.Equal(8, Walker(new WwiseBytePtr(big, 0), 90).Result);
        var loop = ReadWem("English(US)/1013342711.wem")!;
        foreach (uint length in new uint[] { (uint)loop.Length, 600, 200 })   // emu_stream.py walker: lengths 70062 (the whole entry), 600, 200 give result 1; 90 gives 8
        {
            var wl = Walker(new WwiseBytePtr(loop, 0), length);
            Assert.Equal((1, 162u, 69900u, 24302u, 220574u), (wl.Result, wl.DataOffset20, wl.DataSize1C, wl.Word24, wl.Word28));   // the smpl loop: start 24302, end 220574
        }
        Assert.Equal(8, Walker(new WwiseBytePtr(loop, 0), 90).Result);
        Assert.Equal(0x1F, Walker(default, 0).Result);
        Assert.Equal(0x1F, Walker(default, 50).Result);
        Assert.Equal(0x1F, Walker(new WwiseBytePtr(new byte[16], 0), 0).Result);
        Assert.Equal(7, Walker(new WwiseBytePtr(new byte[16], 0), 11).Result);
    }

    // ------------------------------------------------------------------ V1: the first StartStream call of the streamed Vorbis class

    [Theory]
    [InlineData("prefix_covers", 600, 1, 0x3F800000u, 0u, 3)]            // a prefix that covers the seek table and setup packet: 1 with NO buffering gate (0xAB2480..0xAB24B0)
    [InlineData("prefix_exact", 347, 1, 0x3F800000u, 0u, 3)]             // exactly data offset + [S+0xC4] + 2 + setup size: 1, nothing left over
    [InlineData("prefix_one_short", 346, 1, 0x3F800000u, 0u, 3)]         // one byte short: 0x3F (63), the setup payload collected 218 of 219 in an owned copy (vf0 = 218, vf8 = 1)
    [InlineData("prefix_header_only", 94, 1, 0x3F800000u, 0u, 3)]        // the header only: nothing left for the seek table: 0x3F from the state machine's `[S+0x44] == 0`
    [InlineData("prefix_tiny", 40, 1, 0x3F800000u, 0u, 3)]               // the data chunk header is outside the prefix: the walker returns 8, which is returned
    [InlineData("loop_infinite", 600, 0, 0x3F800000u, 0u, 3)]            // loop count 0: loop bytes from the vorb block, SetHeuristics with the loop range (the heavy path)
    [InlineData("loop_three", 600, 3, 0x3F800000u, 0u, 3)]
    [InlineData("priority_7_5", 600, 1, 0x40F00000u, 0u, 3)]             // priority (int)7.5f = 7 in the stream (0xAB14B0..)
    [InlineData("callback_bit", 600, 1, 0x3F800000u, 0x400000u, 3)]      // the has != 0 path has no gate and no callback block: no callback
    [InlineData("prefetch_bit_clear", 600, 1, 0x3F800000u, 0u, 1)]       // [src+0xC] bit 1 clear: no prefetch: 0xAB2088 -> GetBuffer on the unopened stream -> 0x3F
    public void V1_TheFirstCallMatchesTheEnginesResultAndState(string name, int prefixLen, int loop, uint priorityBits, uint flags4, int bits0c)
    {
        var wem = ReadWem(VorbisName);
        if (wem is null) return;
        var (results, states) = Oracle("vorbis_" + name);
        var rig = new SourceRig(wem, prefixLen, loop: (ushort)loop, priorityBits: priorityBits, flags4: flags4, bits0c: (byte)bits0c);
        Assert.Equal(results[0], rig.Start());
        Assert.Equal(states[0], rig.State());
    }

    [Theory]
    [InlineData("retry_no_io_one_short", 346)]
    [InlineData("retry_no_io_tiny", 40)]
    public void V2_ARetryWithoutAnyIoRepeatsTheResultsTheEngineGives(string name, int prefixLen)
    {
        // The voice pass retries by calling StartStream again (0xA56650 leaves the latch clear for any result but 1). Without I/O the one-short stream keeps returning 0x3F from its saved state
        // ([S+0x68] = 2, the setup copy kept); the tiny one fails in the prefetch (8), and its second and third calls find a stream that was never started: GetBuffer gives 0x11 with nothing,
        // 0x9CD340(NULL, 0) returns 0x1F (the walker double reproduces it, W1), and 0x1F is returned (31).
        var wem = ReadWem(VorbisName);
        if (wem is null) return;
        var (results, states) = Oracle("vorbis_" + name);
        var rig = new SourceRig(wem, prefixLen);
        var got = new[] { rig.Start(), rig.Start(), rig.Start() };
        Assert.Equal(results, got);
        Assert.Equal(states[0], rig.State());
    }

    [Theory]
    [InlineData("retry_after_io_one_short", 346)]
    [InlineData("retry_after_io_tiny", 40)]
    public void V3_TheDataThatArrivesAfterTheFirstCallIsReadFromTheEndOfThePrefix(string name, int prefixLen)
    {
        // emu_stream.py: call 1; the I/O thread opens the file and delivers 4096 bytes from [prefix length]; calls 2 and 3. One short: the header completes (v68 = 3, the codebook cache saw the 219-byte setup packet in an owned
        // copy, in_prefix 1: 0) but the gate holds the result at 0x3F: [S+0x44] + available (4095 + 0) is below the nominal buffering 12.971 * 380 = 4928 (0xAB2648..0xAB266C).
        var wem = ReadWem(VorbisName);
        if (wem is null) return;
        var (results, states) = Oracle("vorbis_" + name);
        var rig = new SourceRig(wem, prefixLen);
        var got = new List<int> { rig.Start() };
        rig.Io((uint)prefixLen, 4096);
        got.Add(rig.Start());
        got.Add(rig.Start());
        Assert.Equal(results, got);
        Assert.Equal(states[0], rig.State());
    }

    [Fact]
    public void V4_TwoBuffersPassTheGateAndTheLatchStopsFurtherCalls()
    {
        // emu_stream.py vorbis_retry_after_io_two_buffers: the first call returns 0x3F; two deliveries of 4096 bytes; the second call returns 1 (4095 + 4096 >= 4928). Through the live 0xA56650: the latch is
        // set by the result 1 and a third call returns 1 WITHOUT calling vt+0x28 again.
        var wem = ReadWem(VorbisName);
        if (wem is null) return;
        var (results, states) = Oracle("vorbis_retry_after_io_two_buffers");
        var rig = new SourceRig(wem, 346);
        var source = new FakeVorbisVoiceSource(rig.V!);
        Assert.Equal(results[0], WwiseVoiceSourceStart.StartA56650(source, 0, 0, out bool ran1));
        Assert.True(ran1);
        Assert.False(source.StartStreamSucceeded);                                                         // 0x3F leaves bit 0 of [S+0x10] clear
        rig.Io(346, 4096);
        rig.Rig.Deliver(rig.V!.Stream3C!, 346 + 4096, 4096);
        Assert.Equal(results[1], WwiseVoiceSourceStart.StartA56650(source, 0, 0, out bool ran2));
        Assert.True(ran2);
        Assert.True(source.StartStreamSucceeded);                                                          // 0xA56678..0xA56684: set on exactly 1
        Assert.Equal(states[0], rig.State().Replace("f10=3 ", "f10=2 "));                                  // the oracle calls the raw StartStream: the latch (bit 0 of [S+0x10]) is 0xA56650's
        string before = rig.State();
        Assert.Equal(1, WwiseVoiceSourceStart.StartA56650(source, 0, 0, out bool ran3));
        Assert.False(ran3);
        Assert.Equal(before, rig.State());
    }

    private sealed class FakeVorbisVoiceSource : IWwiseVoiceSource
    {
        private readonly WwiseVorbisStreamSource _s;
        public FakeVorbisVoiceSource(WwiseVorbisStreamSource s) => _s = s;
        public int Channels => 1;
        public int SampleRate => 48000;
        public int Render(WwiseVoiceBuffer buffer) => 0x2E;
        public int StartStream(uint a, uint b) => _s.StartStreamAB22D4();
        public bool StartStreamSucceeded { get => _s.StartLatch; set => _s.StartLatch = value; }
    }

    // ------------------------------------------------------------------ V5: no prefetch, the gate and the callback block

    [Theory]
    [InlineData("noprefetch", 0x44, 0)]
    [InlineData("noprefetch_loop_infinite", 0x44, 1)]
    [InlineData("noprefetch_gate_off", 0x04, 0)]
    public void V5_WithoutAPrefixTheFirstCallReturns0x3FAndTheDataFinishesTheHeader(string name, int flags1BD, int infinite)
    {
        // emu_stream.py vorbis_noprefetch*: call 1 -> 0x3F (the unopened stream gives 0x2E to 0xAB2088); a repeat -> 0x3F; the I/O thread opens and delivers 4096 bytes; call 3 parses the header from the first
        // buffer (0xAB12B4 on [S+0x40], then the state machine): with the gate on (the PBI's bit 6: [S+0x10] bit 1) the result is again 0x3F (3749 + 0 < 4928); with the gate off it is 1 and stays 1.
        var wem = ReadWem(VorbisName);
        if (wem is null) return;
        var (results, states) = Oracle("vorbis_" + name);
        var rig = new SourceRig(wem, 0, loop: (ushort)(infinite == 1 ? 0 : 1), flags1BD: (byte)flags1BD);
        var got = new List<int> { rig.Start() };
        string first = rig.State();
        got.Add(rig.Start());
        rig.Io(0, 4096);
        got.Add(rig.Start());
        string second = rig.State();
        got.Add(rig.Start());
        got.Add(rig.Start());
        Assert.Equal(results, got);
        Assert.Equal(states[0], first);
        Assert.Equal(states[1], second);
        Assert.Equal(states[2], rig.State());
    }

    [Fact]
    public void V6_ASmallFirstBufferKeepsTheGateClosedOnEveryLaterCall()
    {
        // emu_stream.py vorbis_noprefetch_small_buffer(+_call3..5): 400 bytes delivered: the header completes inside it (left 53) and every call returns 0x3F (53 + 0 < 4928).
        var wem = ReadWem(VorbisName);
        if (wem is null) return;
        var rig = new SourceRig(wem, 0);
        rig.Start();
        rig.Io(0, 400);
        var (results, states) = Oracle("vorbis_noprefetch_small_buffer");
        Assert.Equal(results[0], rig.Start());
        Assert.Equal(states[0], rig.State());
        for (int k = 3; k <= 5; k++)
        {
            var (r, st) = Oracle("vorbis_noprefetch_small_buffer_call" + k);
            Assert.Equal(r[0], rig.Start());
            Assert.Equal(st[0], rig.State());
        }
    }

    [Theory]
    [InlineData("below", 4000, 0)]
    [InlineData("above", 6000, 0)]
    [InlineData("two_buffers", 4000, 4000)]
    public void V7_TheGateComparesTheBytesLeftPlusTheBufferedBytesWithTheNominalBuffering(string name, int first, int second)
    {
        // emu_stream.py vorbis_gate_*: [S+0x44] + the Query sum against nominal = (u32)(12.971f * 380.0f) = 4928: below 3653 -> 0x3F three times; 5653 -> 1; 3653 + 4000 -> 1.
        var wem = ReadWem(VorbisName);
        if (wem is null) return;
        var (results, states) = Oracle("vorbis_gate_" + name);
        var rig = new SourceRig(wem, 0);
        rig.Start();
        rig.Io(0, (uint)first);
        if (second != 0) rig.Rig.Deliver(rig.V!.Stream3C!, (ulong)first, (uint)second);
        var got = new[] { rig.Start(), rig.Start(), rig.Start() };
        Assert.Equal(results, got);
        Assert.Equal(states[0], rig.State());
    }

    [Fact]
    public void V8_TheCallbackBlockReportsTheEstimateAndTheFlagWithoutChangingTheResult()
    {
        // emu_stream.py vorbis_gate_callback: bit 22 of [pbi+4] set; 6000 bytes delivered; both calls return 1 and call 0xA059D8 with (playing id 0x1234, estimate (u32)(float(5653) / 12.971f) = 435, flag 0x11:
        // the buffered amount reached the nominal), 0xA74F00..0xA74FC0 and its copies (0xAB2C4C..0xAB2D18).
        var wem = ReadWem(VorbisName);
        if (wem is null) return;
        var (results, states) = Oracle("vorbis_gate_callback");
        var rig = new SourceRig(wem, 0, flags4: 0x400000);
        rig.Start();
        rig.Io(0, 6000);
        Assert.Equal(results, new[] { rig.Start(), rig.Start() });
        Assert.Equal(states[0], rig.State());
        Assert.Equal(new[] { "4660/435/17", "4660/435/17" }, rig.Callbacks);
    }

    [Fact]
    public void V9_AFailedOutputBufferAllocationFailsTheStateThreeAction()
    {
        // emu_stream.py vorbis_output_buffers_fail (0xAB3264 returning -1): the prefix path returns 2 (0xAB1F28..0xAB1F2C movne r0,#2); the state is otherwise that of prefix_covers.
        var wem = ReadWem(VorbisName);
        if (wem is null) return;
        var (results, states) = Oracle("vorbis_output_buffers_fail");
        var rig = new SourceRig(wem, 600) { OutFail = true };
        Assert.Equal(results[0], rig.Start());
        Assert.Equal(states[0], rig.State());
    }

    // ------------------------------------------------------------------ D4: the arguments 0xA74564 gives the stream manager

    [Theory]
    [InlineData("by_id", 0x03, 0x02, 0x3F800000u, 1u, 99908739u, 0u, 1, false)]
    [InlineData("by_id_cache_minus_one_bit0", 0x03, 0x03, 0x3F800000u, 1u, 0xFFFFFFFFu, 1u, 1, false)]    // byte[src+0xD] & 9 != 0: cache id -1; its bit 0 is the company id
    [InlineData("by_id_cache_minus_one_bit3", 0x03, 0x0A, 0x3F800000u, 1u, 0xFFFFFFFFu, 0u, 1, false)]
    [InlineData("by_id_lang_clear", 0x02, 0x02, 0x3F800000u, 1u, 99908739u, 0u, 0, false)]
    [InlineData("by_name", 0x03, 0x06, 0x3F800000u, 1u, 99908739u, 0u, 1, true)]                         // byte[src+0xD] & 4: open by name (manager vt+0x18), the name copied into the record
    public void D4_TheFlagsAndHeuristicsOfTheStreamCreationAreTheEngines(string name, int bits0c, int bits0d, uint priorityBits, uint priority, uint cache, uint company, int lang, bool byName)
    {
        // emu_stream.py create_args_*: the real 0xA74564 -> CreateAuto -> the open record: company id byte[src+0xD] & 1, codec id [src+0x14] >> 16 (4), language byte[src+0xC] & 1, the third flag byte
        // (byte[src+0xD] >> 1) & 1 = 1, +0x12 = 1 (CreateAuto), the cache id -1 when byte[src+0xD] & 9 else [src+4], no prefetch; priority (int)float[pbi+0x1C0] = 1; the stream's throughput
        // 12.971 (float(avg bytes) / 1000, 0xAB14AC) and its minimum buffers byte 1 (a zero byte is stored as 1, 0x964848).
        var wem = ReadWem(VorbisName);
        if (wem is null) return;
        var rig = new SourceRig(wem, 600, bits0c: (byte)bits0c, bits0d: (byte)bits0d, name: byName ? "snd/test.wem" : null);
        Assert.Equal(1, rig.Start());
        var s = rig.V!.Stream3C!;
        Assert.Equal(((byte)priority, cache), (s.Priority2C, s.CacheId40));
        var rec = s.Record0C!;
        Assert.Equal(0u, rec.Mode);
        Assert.Equal(byName ? "snd/test.wem" : null, rec.Name);
        if (!byName) Assert.Equal(99908739u, rec.FileId);
        var f = rec.Flags!;
        Assert.Equal((company, 4u, (byte)lang, (byte)1, (byte)1, cache, 0u), (f.CompanyId, f.CodecId, f.LanguageSpecific, f.Byte11, f.Byte12, f.CacheId, f.PrefetchBytes));
        Assert.Equal((1095731511u, 1u, (byte)1), (BitConverter.SingleToUInt32Bits(s.Throughput44), s.MinBuffer58, s.Byte6D));
    }

    [Fact]
    public void D5_APriorityOutsideTheByteRangeFailsCreateAutoWith0x1F()
    {
        // emu_stream.py create_args_priority_255 / priority_negative: (int)255.0f and (int)-5.0f are bytes 0xFF and 0xFB, above 0x64: CreateAuto returns 0x1F (0x95F354..0x95F35C) and 0xA74564 returns it; no stream.
        var wem = ReadWem(VorbisName);
        if (wem is null) return;
        Assert.Equal(0x1F, new SourceRig(wem, 600, priorityBits: 0x437F0000).Start());
        Assert.Equal(0x1F, new SourceRig(wem, 600, priorityBits: 0xC0A00000).Start());
    }

    // ------------------------------------------------------------------ V10: the decode body's buffering gate

    [Theory]
    [InlineData("below_nominal", 4000, 0x44u, 0u, false)]
    [InlineData("above_nominal", 6000, 0x44u, 0u, false)]
    [InlineData("below_nominal_callback", 4000, 0x44u, 0x400000u, false)]
    [InlineData("above_nominal_callback", 6000, 0x44u, 0x400000u, false)]
    [InlineData("gate_clear", 4000, 0x04u, 0u, false)]
    [InlineData("gate_clear_callback", 4000, 0x04u, 0x400000u, false)]
    [InlineData("error_status", 4000, 0x44u, 0u, true)]
    [InlineData("error_status_callback", 4000, 0x44u, 0x400000u, true)]
    public void V10_TheDecodeGateIsTheEnginesOnReachedAndTheStoredCode(string name, int size, uint flags1BD, uint flags4, bool kill)
    {
        // emu_stream.py vorbis_gate7_*: the real 0xAB1550 with 0xAB7E40 / 0xA73490 stubbed: whether the decode is reached, [state+0x28] when it is not, [S+0x10] after (bit 1 cleared for good once the gate passes,
        // 0xAB1A34..0xAB1A44) and the callbacks. Below the nominal: status code 0x2E and no decode (the callback block first when bit 22 is set); status 2: 2.
        var wem = ReadWem(VorbisName);
        if (wem is null) return;
        var expected = StreamSourceOracle.Gate7[name];
        var rig = new SourceRig(wem, 0, flags1BD: (byte)flags1BD, flags4: flags4);
        rig.Start();
        rig.Io(0, (uint)size);
        rig.Start();
        if (kill) rig.V!.Stream3C!.Kill962028();
        rig.Callbacks.Clear();
        var gate = rig.V!.DecodeGateAB1550();
        Assert.Equal(expected.Reached, gate.Decode);
        if (!expected.Reached) Assert.Equal(expected.Code, gate.Result);
        Assert.Equal(expected.F10, rig.V.Flags10);
        Assert.Equal(expected.Callbacks, string.Join(";", rig.Callbacks));
    }

    public static IEnumerable<object[]> DecodeScenarios()
    {
        // the table of emu_stream.py sc_vorbis_decode: (name, delivered buffers, decode script (status, consumed, frames), output code or -1, mutation)
        yield return new object[] { "one_packet_ready", new[] { (0, 4096) }, new[] { (0x2D, 0, 1024) }, -1, "" };
        yield return new object[] { "three_packets_then_ready", new[] { (0, 4096) }, new[] { (0x2B, 0, 0), (0x2E, 0, 0), (0x2D, 0, 256) }, -1, "" };
        yield return new object[] { "decode_error", new[] { (0, 4096) }, new[] { (2, 0, 0) }, -1, "" };
        yield return new object[] { "decode_status_0x11", new[] { (0, 4096) }, new[] { (0x11, 0, 64) }, -1, "" };
        yield return new object[] { "decode_status_other", new[] { (0, 4096) }, new[] { (0x2C, 0, 64) }, -1, "" };
        yield return new object[] { "consumed_adjusts_the_pointer", new[] { (0, 4096) }, new[] { (0x2D, 40, 512) }, -1, "" };
        yield return new object[] { "output_no_more_data_with_consumed", new[] { (0, 4096) }, new[] { (0x2D, 5, 128) }, 0x2E, "" };
        yield return new object[] { "output_no_more_data_no_consumed", new[] { (0, 4096) }, new[] { (0x2D, 0, 128) }, 0x2E, "" };
        yield return new object[] { "packet_spans_the_end_of_the_buffer", new[] { (0, 380) }, Array.Empty<(int, int, int)>(), -1, "" };
        yield return new object[] { "packet_spans_then_the_next_buffer_arrives", new[] { (0, 380), (380, 4096) }, new[] { (0x2D, 0, 300) }, -1, "second_call" };
        yield return new object[] { "end_reached", new[] { (0, 4096) }, new[] { (0x2D, 0, 1) }, -1, "end" };
        yield return new object[] { "size_prefix_split", new[] { (0, 348), (348, 4096) }, new[] { (0x2D, 0, 77) }, -1, "second_call" };
    }

    [Theory]
    [MemberData(nameof(DecodeScenarios))]
    public void V12_TheDecodeLoopsControlFlowMatchesTheEngineWithTheDecodeSeamsStoodInOnBothSides(
        string name, (int Start, int Size)[] buffers, (int Status, int Consumed, int Frames)[] script, int outCode, string mutate)
    {
        // emu_stream.py vorbis_decode_*: the real 0xAB1550 loop (the packet collection of G3 with the packet decode 0xAB7E40 and the output hand-off 0xA73490 called per packet) with scripted stand-ins for both;
        // the decode calls (packet size argument, [S+0xB0], [S+0xB4], bytes left, owned copy, the packet's length prefix), the output calls (frames, rate, [S+0xA8], the code before) and the final code and state
        // are the engine's. Expected: one_packet_ready -> 0x2D; a decode status of 2 or 0x2C -> 2; 0x11 -> 0x11; 0x2B / 0x2E loop to the next packet; an output code of 0x2E becomes 0x2D when [S+0x6C] != 0 and 2 otherwise;
        // a packet cut by the end of the buffer leaves 0x2E and is completed when the next buffer arrives; bit 0 of [S+0x5E] with no bytes left gives 0x11 and the output stage.
        var wem = ReadWem(VorbisName);
        if (wem is null) return;
        var expected = StreamSourceOracle.Decode[name];
        var rig = new SourceRig(wem, 0, flags1BD: 0x04);
        var queue = new Queue<(int Status, int Consumed, int Frames)>(script);
        var decodes = new List<string>();
        var outputs = new List<string>();
        rig.Seams = new WwiseStreamSourceSeams
        {
            Memory = rig.Memory, WaveWalker9CD340 = Walker, CodebookCacheAB2D74 = rig.Seams.CodebookCacheAB2D74, OutputBuffersFailAB3264 = rig.Seams.OutputBuffersFailAB3264,
            PacketDecodeAB7E40 = (src, cc) =>
            {
                decodes.Add($"{cc}/{src.InputB0}/{src.InputB4}/{src.Left44}/{(src.SetupOwned ? 1 : 0)}/{(src.SetupPacket.IsNull ? 0 : src.SetupPacket.U16(0))}");
                var (status, consumed, frames) = queue.Count > 0 ? queue.Dequeue() : (0x2E, 0, 0);
                src.Status64 = status; src.Consumed6C = (uint)consumed; src.FramesDecoded60 = (ushort)frames; src.OutputA4 = new object();
            },
            OutputHandoffA73490 = (src, st) =>
            {
                outputs.Add($"{src.FramesDecoded60}/{src.SampleRateE0}/{src.ChannelWordA8}/{st.Code28}");
                if (outCode >= 0) st.Code28 = outCode;
            },
        };
        rig.V = new WwiseVorbisStreamSource(rig.Rig.Manager, rig.Pbi, rig.Block, rig.Seams);
        rig.Start();
        var stream = rig.V.Stream3C!;
        stream.RunOpen963890();
        rig.Rig.Deliver(stream, (ulong)buffers[0].Start, (uint)buffers[0].Size);
        rig.Start();                                                                                       // the header, from the first buffer
        if (mutate == "end") { rig.V.Bits5E |= 1; rig.V.Left44 = 0; }
        var state = new WwiseDecodeState();
        rig.V.DecodeAB1550(state);
        Assert.Equal(expected.Code, state.Code28);
        if (mutate == "second_call")
        {
            rig.Rig.Deliver(stream, (ulong)buffers[1].Start, (uint)buffers[1].Size);
            state.Code28 = 0xABCD;
            rig.V.DecodeAB1550(state);
            Assert.Equal(expected.Code2, state.Code28);
        }
        Assert.Equal(expected.Decodes, string.Join(";", decodes));
        Assert.Equal(expected.Outputs, string.Join(";", outputs));
        Assert.Equal(expected.State, rig.State());
    }

    [Fact]
    public void V11_TheUnopenedStreamsStaleWordDecidesTheGateAndIsTheSeams()
    {
        // emu_stream.py vorbis_gate7_unopened: Query leaves the caller's out variable unwritten for a stream that is not opened, so the gate adds the stack's stale word: with a word below the nominal
        // (the oracle's stack held one) the decode is blocked with 0x2E; a seam word above the nominal opens the gate. The word is the seam's (C33.4).
        var wem = ReadWem(VorbisName);
        if (wem is null) return;
        var expected = StreamSourceOracle.Gate7["unopened"];
        var rig = new SourceRig(wem, 0, stale: 0);
        rig.Start();
        var gate = rig.V!.DecodeGateAB1550();
        Assert.Equal((expected.Reached, expected.Code), (gate.Decode, gate.Result));
        Assert.Equal(expected.F10, rig.V.Flags10);
        var other = new SourceRig(wem, 0, stale: 0x10000);
        other.Start();
        Assert.True(other.V!.DecodeGateAB1550().Decode);
    }

    // ------------------------------------------------------------------ the missing bodies

    [Fact]
    public void X1_ABodyThatC33DoesNotAdoptStopsTheStreamInsteadOfBeingGuessed()
    {
        // 0x9CD340, 0xAB2D74, 0xA059D8, 0xA736D4 / 0xAB1020, 0xA73ABC are not adopted: each throws WwiseMissingBehaviourException when reached without its seam (MISSING in the report).
        var wem = ReadWem(VorbisName);
        if (wem is null) return;
        Assert.Throws<WwiseMissingBehaviourException>(() => new SourceRig(wem, 600, noWalker: true).Start());
        Assert.Throws<WwiseMissingBehaviourException>(() => new SourceRig(wem, 600, noCodebook: true).Start());
        var cb = new SourceRig(wem, 0, flags4: 0x400000, noCallback: true);
        cb.Start();
        cb.Io(0, 6000);
        Assert.Throws<WwiseMissingBehaviourException>(() => cb.Start());
        // a start offset (bit 7 of [pbi+0x1BD]) reaches 0xA736D4 once the header is parsed
        var offset = new SourceRig(wem, 0, flags1BD: 0xC4);
        offset.Start();
        offset.Io(0, 4096);
        Assert.Throws<WwiseMissingBehaviourException>(() => offset.Start());
        var adpcm = ReadWem(AdpcmName)!;
        Assert.Throws<WwiseMissingBehaviourException>(() => new SourceRig(adpcm, 600, vorbis: false, bits0c: 0x02, noParse: true).Start());
    }

    // ------------------------------------------------------------------ the ADPCM / PCM stream classes (F7)

    [Theory]
    [InlineData("prefix", 600, 1, 0x44, 0x02, false)]
    [InlineData("prefix_loop_infinite", 600, 0, 0x44, 0x02, false)]
    [InlineData("noprefetch", 0, 1, 0x44, 0x02, true)]
    [InlineData("noprefetch_gate_off", 0, 1, 0x04, 0x02, true)]
    [InlineData("prefetch_bit_clear", 600, 1, 0x44, 0x01, true)]
    [InlineData("start_offset_flag", 600, 1, 0xC4, 0x02, false)]
    public void A1_TheStreamClassStartStreamMatchesTheEngine(string name, int prefixLen, int loop, int flags1BD, int bits0c, bool io)
    {
        // emu_stream.py adpcm_*: the real 0xA7538C of the 0xA74244 class with the header parse stood in (the same stand-in as the C# seam): the prefix case returns the stream's Start result with no gate (0xA75020);
        // with no prefetch the first call is 0x3F (GetBuffer 0x2E, 0xA74D08), later calls (after 4096 bytes) pass the gate with throughput 1.0f (nominal 380) -> 1.
        var wem = ReadWem(AdpcmName);
        if (wem is null) return;
        var (results, states) = Oracle("adpcm_" + name);
        var rig = new SourceRig(wem, prefixLen, vorbis: false, loop: (ushort)loop, flags1BD: (byte)flags1BD, bits0c: (byte)bits0c);
        var got = new List<int> { rig.Start() };
        string first = rig.State();
        if (io)
        {
            rig.Io(0, 4096);
            got.Add(rig.Start()); got.Add(rig.Start()); got.Add(rig.Start());
        }
        Assert.Equal(results, got);
        Assert.Equal(states[0], first);
        Assert.Equal(states[^1], rig.State());
    }

    [Fact]
    public void A2_TheCallbackBlockAndTheSmallBufferGateOfTheStreamClass()
    {
        // emu_stream.py adpcm_callback: bit 22 set, 400 bytes delivered: 0x3F three times (left 336 < the nominal 380); the callback ran on the 2nd and 3rd call with the estimate (u32)(336 / 1.0f) = 336, flag 1.
        var wem = ReadWem(AdpcmName);
        if (wem is null) return;
        var (results, states) = Oracle("adpcm_callback");
        var rig = new SourceRig(wem, 0, vorbis: false, bits0c: 0x02, flags4: 0x400000);
        var got = new List<int> { rig.Start() };
        rig.Io(0, 400);
        got.Add(rig.Start()); got.Add(rig.Start());
        Assert.Equal(results, got);
        Assert.Equal(states[0], rig.State());
        Assert.Equal(new[] { "4660/336/1", "4660/336/1" }, rig.Callbacks);
    }

    // ------------------------------------------------------------------ the live entry: the voice source adapters and AddSrc

    private static string? FindCodebooks()
    {
        var d = new DirectoryInfo(AppContext.BaseDirectory);
        while (d is not null)
        {
            string p = Path.Combine(d.FullName, "third-party", "ww2ogg", "packed_codebooks_aoTuV_603.bin");
            if (File.Exists(p)) return p;
            d = d.Parent;
        }
        Assert.Fail("third-party/ww2ogg/packed_codebooks_aoTuV_603.bin is not present: these tests do not pass silently without it");
        return null;
    }

    [Fact]
    public void L1_TheStreamedAdapterReturnsTheRawResultsThroughAddSrcAndTheRetryDrivesItToOne()
    {
        // The live path: WwisePlaybackBridge.AddSrc -> 0xA56650 -> the adapter's vt+0x28 -> 0xAB22D4. AddSrc returns the raw result (0x3F for a prefix one byte short: the source is kept pending), the
        // voice pass retries through 0xA56650 (the latch is clear), and once the stream layer has delivered enough the result is 1 and the latch is set. The PBI's own format bytes are written by 0xAB12B4 inside
        // StartStream, so the bridge's SourceFormatWriter15C seam is NOT needed (it is left unset, which throws if asked).
        var wem = ReadWem(VorbisName);
        string? books = FindCodebooks();
        if (wem is null || books is null) return;
        var media = WwiseMedia.Parse(wem);
        var codebooks = WwiseCodebookLibrary.Load(books);
        var bridge = new WwisePlaybackBridge().WithTestSeams();
        bridge.SourceFormatWriter15C = null;
        var rig = new StreamRig(fileSize: wem.Length, io: new ManualIo { StaleQueryWord = 0 }, content: wem);
        var memory = new WwiseBankMemory();
        var pbi = bridge.CreatePbi(new WwisePlayInitParams { PlayingId = 0x1234, TargetNodeId = 1 }, 1, new WwiseSourceDescriptor(WwiseSourceFactory.VorbisPlugin, 1, 99908739, 0, 0), continuous: false);
        pbi.Word15C = 0;
        uint address = memory.Allocate(346 + 16)!.Value;
        Array.Copy(wem, memory.Block(address), 346);
        pbi.Word1DC = address; pbi.Word1E0 = 346;
        var setups = new List<string>();
        var seams = new WwiseStreamSourceSeams
        {
            Memory = memory,
            WaveWalker9CD340 = Walker,
            CodebookCacheAB2D74 = (s, ptr, size, flag) => { setups.Add($"{size}/{flag}"); return new object(); },
        };
        bridge.MediaFor = id => media;
        bridge.Codebooks = codebooks;
        bridge.StreamingFor = p => new WwiseStreamingContext
        {
            Manager = rig.Manager, Pbi = p, Seams = seams,
            Block = new WwiseSourceBlock150 { SourceId04 = 99908739, Bits0C = 3, Bits0D = 2, Plugin14 = 0x00040001 },
        };
        var voice = new WwiseLiveVoice(1, 16);
        Assert.Equal(0x3F, bridge.AddSrc(voice, pbi, bActive: false));                                       // prefix one byte short
        var source = Assert.IsType<WwiseVorbisVoiceSource>(voice.Pending);
        Assert.False(source.StartStreamSucceeded);
        Assert.NotNull(source.StreamSource!.Stream3C);
        var stream = source.StreamSource.Stream3C!;
        stream.RunOpen963890();
        rig.Deliver(stream, 346, 4096);
        rig.Deliver(stream, 346 + 4096, 4096);
        Assert.Equal(1, WwiseVoiceSourceStart.StartA56650(source, pbi.Read1DC(), pbi.Read1E0(), out bool ran));   // the voice pass retry
        Assert.True(ran);
        Assert.True(source.StartStreamSucceeded);
        Assert.Equal(48000u, pbi.SourceFormat158);                                                          // written inside StartStream (0xAB1384)
        Assert.Equal(0x4101u, pbi.Word15C);
        Assert.Equal(new[] { "219/0" }, setups);
        // the offline decode seam serves the samples after the gate (vt+0x30): the gate of 0xAB1550 passes with 8191 >= 4928 bytes buffered, then the whole media is decoded
        var buffer = new WwiseVoiceBuffer(1, 1024);
        Assert.Equal(0x2D, source.Render(buffer));
        Assert.Equal(1024, buffer.ValidFrames);
    }

    [Fact]
    public void L4_NotReadyCheckDrivesTheStreamedSourceAndItsWindowUsesTheFrameCount()
    {
        // The live path of the voice pass retry: WwiseVoiceLinker.NotReadyCheck (0xA544BC) -> 0xA56650 -> the adapter's StartStream. A result of 0x3F with a non-negative [pbi+0x1D8] stays pending (0x3F); a result of 1
        // compares [pbi+0x1D8] with the window trunc_s32(float((L + 1) * u16[0x1052440]) * ratio + 0.5f) = (1 + 1) * 0x400 = 2048 (C33.3: the 0x3F at 0xA54570 depends on the frame count, not on the I/O thread):
        // emu_notready.py: offset 2047 -> 1, offset 2048 -> 0x3F, and 0x3F from the source with offset 5 -> 0x3F.
        var wem = ReadWem(VorbisName);
        string? books = FindCodebooks();
        if (wem is null || books is null) return;
        var media = WwiseMedia.Parse(wem);
        var codebooks = WwiseCodebookLibrary.Load(books);
        foreach (var (prefixLen, offset, expected) in new[] { (600, 2047, 1), (600, 2048, 0x3F), (346, 5, 0x3F) })
        {
            var rig = new StreamRig(fileSize: wem.Length, io: new ManualIo { StaleQueryWord = 0 }, content: wem);
            var memory = new WwiseBankMemory();
            var pbi = new WwisePlayingInstance(new WwisePlayInitParams { PlayingId = 0x1234, TargetNodeId = 1 }, 1, new WwiseSourceDescriptor(WwiseSourceFactory.VorbisPlugin, 1, 99908739, 0, 0), new byte[0x44], null, false);
            uint address = memory.Allocate(prefixLen + 16)!.Value;
            Array.Copy(wem, memory.Block(address), prefixLen);
            pbi.Word1DC = address; pbi.Word1E0 = (uint)prefixLen;
            pbi.StartOffset = (uint)offset;
            var seams = new WwiseStreamSourceSeams { Memory = memory, WaveWalker9CD340 = Walker, CodebookCacheAB2D74 = (s, ptr, size, flag) => new object() };
            var source = new WwiseVorbisVoiceSource(WwiseVorbisSourceKind.Streamed, media, codebooks, streaming: new WwiseStreamingContext
            {
                Manager = rig.Manager, Pbi = pbi, Seams = seams,
                Block = new WwiseSourceBlock150 { SourceId04 = 99908739, Bits0C = 3, Bits0D = 2, Plugin14 = 0x00040001 },
            });
            var linker = new WwiseVoiceLinker(new WwiseMixBusHierarchy(), new WwiseOutputDeviceList(), new List<WwiseLiveVoice>(),
                _ => new WwisePbiRouting { Node = new WwiseRoutingNode { Id = 1 } },
                new WwiseVoiceLinkSeams { SourceOwner = _ => pbi, SourceFlag10Bit1 = _ => true });
            var voice = new WwiseLiveVoice(1, 16) { Source = source };
            Assert.Equal(expected, linker.NotReadyCheck(voice, pbi));
            Assert.Equal(expected == 0x3F && prefixLen == 346, !source.StartStreamSucceeded);              // the latch is set only by the raw result 1
        }
    }

    [Fact]
    public void L2_AStreamedAdapterWithoutAContextRefusesToStartInsteadOfFallingBackToTheOfflineDecode()
    {
        var wem = ReadWem(VorbisName);
        string? books = FindCodebooks();
        if (wem is null || books is null) return;
        var source = new WwiseVorbisVoiceSource(WwiseVorbisSourceKind.Streamed, WwiseMedia.Parse(wem), WwiseCodebookLibrary.Load(books));
        Assert.Throws<WwiseMissingBehaviourException>(() => source.StartStream(0, 0));
        Assert.False(source.WritesSourceFormatInStartStream);
        var adpcm = new WwiseAdpcmVoiceSource(WwiseMedia.Parse(ReadWem(AdpcmName)!), streamed: true);
        Assert.Throws<WwiseMissingBehaviourException>(() => adpcm.StartStream(0, 0));
    }

    [Fact]
    public void L3_TheInMemoryKindsKeepTheirEarlierBehaviourBecauseC33DoesNotAdoptTheirBodies()
    {
        // 0xAB0B20 (the in-memory Vorbis StartStream) and 0xA72A2C's class are not adopted: the adapters decode at StartStream and return 1, as before this batch; WritesSourceFormatInStartStream is false.
        var adpcm = ReadWem(AdpcmName);
        if (adpcm is null) return;
        var source = new WwiseAdpcmVoiceSource(WwiseMedia.Parse(adpcm));
        Assert.Equal(1, source.StartStream(0, 0));
        Assert.False(source.WritesSourceFormatInStartStream);
        Assert.Equal(0x2D, source.Render(new WwiseVoiceBuffer(1, 256)));
    }
}
