// <auto-generated> by re-analysis/tools/emu/emu_bus.py from the engine's own output (the real 0x9F4BB8, 0x9BDA6C, 0x9C54E8, 0x9F9CDC, 0x9C39DC, 0xA11590 / 0xA17878 / 0xA17724 / 0xA17280 and 0x9C3620 under Unicorn): do not edit. </auto-generated>
namespace Cozmo.Protocol.Tests;

internal static class BusWalkOracle
{
    public static readonly Dictionary<string, (BusNodeSpec[] Nodes, int Start, int Expected)> F4BB8 = new()
    {
        ["leaf_to_bus"] = (new[] { new BusNodeSpec { Parent = 1 }, new BusNodeSpec { Parent = 2 }, new BusNodeSpec { Bus = 3 }, new BusNodeSpec {  } }, 0, 3),
        ["self_has_bus"] = (new[] { new BusNodeSpec { Bus = 1 }, new BusNodeSpec {  } }, 0, 1),
        ["no_bus"] = (new[] { new BusNodeSpec { Parent = 1 }, new BusNodeSpec {  } }, 0, -1),
        ["nearest_wins"] = (new[] { new BusNodeSpec { Parent = 1, Bus = 2 }, new BusNodeSpec { Bus = 3 }, new BusNodeSpec {  }, new BusNodeSpec {  } }, 0, 2),
    };

    public static readonly Dictionary<string, (BusNodeSpec[] Nodes, byte E9, int Expected)> BDA6C = new()
    {
        ["e9_0"] = (new[] { new BusNodeSpec { Parent = 1 }, new BusNodeSpec { Bus = 2 }, new BusNodeSpec {  } }, 0, 2),
        ["e9_4"] = (new[] { new BusNodeSpec { Parent = 1 }, new BusNodeSpec { Bus = 2 }, new BusNodeSpec {  } }, 4, -1),
        ["e9_5"] = (new[] { new BusNodeSpec { Parent = 1 }, new BusNodeSpec { Bus = 2 }, new BusNodeSpec {  } }, 5, -1),
        ["e9_1"] = (new[] { new BusNodeSpec { Parent = 1 }, new BusNodeSpec { Bus = 2 }, new BusNodeSpec {  } }, 1, 2),
    };

    public static readonly Dictionary<string, (BusNodeSpec[] Nodes, int Start, int Expected)> C54E8 = new()
    {
        ["all_clear"] = (new[] { new BusNodeSpec {  }, new BusNodeSpec { Bus = 0 } }, 1, 0),
        ["fx_slot0"] = (new[] { new BusNodeSpec {  }, new BusNodeSpec { Bus = 0, Fx = new uint[] { 5, 0, 0, 0 } } }, 1, 1),
        ["fx_slot3"] = (new[] { new BusNodeSpec {  }, new BusNodeSpec { Bus = 0, Fx = new uint[] { 0, 0, 0, 9 } } }, 1, 1),
        ["fx_chunk_all_zero"] = (new[] { new BusNodeSpec {  }, new BusNodeSpec { Bus = 0, Fx = new uint[] { 0, 0, 0, 0 } } }, 1, 0),
        ["audio_device_0c"] = (new[] { new BusNodeSpec {  }, new BusNodeSpec { Bus = 0, Cat = 12 } }, 1, 1),
        ["byte68"] = (new[] { new BusNodeSpec {  }, new BusNodeSpec { Bus = 0, B68 = 1 } }, 1, 1),
        ["b46_bit7"] = (new[] { new BusNodeSpec {  }, new BusNodeSpec { Bus = 0, B46 = 128 } }, 1, 1),
        ["b46_bit6_only"] = (new[] { new BusNodeSpec {  }, new BusNodeSpec { Bus = 0, B46 = 64 } }, 1, 0),
        ["no_output_bus"] = (new[] { new BusNodeSpec {  }, new BusNodeSpec {  } }, 1, 1),
        ["w40_e0000"] = (new[] { new BusNodeSpec {  }, new BusNodeSpec { Bus = 0, W40 = 0x00020000U } }, 1, 1),
        ["w40_c0000"] = (new[] { new BusNodeSpec {  }, new BusNodeSpec { Bus = 0, W40 = 0x000C0000U } }, 1, 1),
        ["w40_other"] = (new[] { new BusNodeSpec {  }, new BusNodeSpec { Bus = 0, W40 = 0x0001F000U } }, 1, 0),
        ["w54"] = (new[] { new BusNodeSpec {  }, new BusNodeSpec { Bus = 0, W54 = 0x0000DEADU } }, 1, 1),
        ["actor_mixer_cat1"] = (new[] { new BusNodeSpec {  }, new BusNodeSpec { Bus = 0, Cat = 1 } }, 1, 0),
    };

    public static readonly Dictionary<string, (BusNodeSpec[] Nodes, uint Mask, uint[] Expected)> F9CDC = new()
    {
        ["mask1"] = (new[] { new BusNodeSpec { B46 = 1, States = new (byte, uint)[]?[] { new (byte, uint)[] { (0, 0x3FC00000U), (6, 0x3E800000U), (2, 0x41200000U) }, new (byte, uint)[] { (3, 0x40000000U), (4, 0x40400000U), (5, 0xC0800000U), (0, 0x3F000000U) }, null, new (byte, uint)[] { (7, 0x41100000U) } } } }, 1, new uint[] { 0x40000000U, 0x00000000U, 0x00000000U, 0x00000000U, 0x00000000U, 0x00000000U, 0x3E800000U }),
        ["mask2"] = (new[] { new BusNodeSpec { B46 = 1, States = new (byte, uint)[]?[] { new (byte, uint)[] { (0, 0x3FC00000U), (6, 0x3E800000U), (2, 0x41200000U) }, new (byte, uint)[] { (3, 0x40000000U), (4, 0x40400000U), (5, 0xC0800000U), (0, 0x3F000000U) }, null, new (byte, uint)[] { (7, 0x41100000U) } } } }, 2, new uint[] { 0x00000000U, 0x00000000U, 0x41200000U, 0x00000000U, 0x00000000U, 0x00000000U, 0x00000000U }),
        ["mask4"] = (new[] { new BusNodeSpec { B46 = 1, States = new (byte, uint)[]?[] { new (byte, uint)[] { (0, 0x3FC00000U), (6, 0x3E800000U), (2, 0x41200000U) }, new (byte, uint)[] { (3, 0x40000000U), (4, 0x40400000U), (5, 0xC0800000U), (0, 0x3F000000U) }, null, new (byte, uint)[] { (7, 0x41100000U) } } } }, 4, new uint[] { 0x00000000U, 0x00000000U, 0x00000000U, 0x40000000U, 0x00000000U, 0x00000000U, 0x00000000U }),
        ["mask8"] = (new[] { new BusNodeSpec { B46 = 1, States = new (byte, uint)[]?[] { new (byte, uint)[] { (0, 0x3FC00000U), (6, 0x3E800000U), (2, 0x41200000U) }, new (byte, uint)[] { (3, 0x40000000U), (4, 0x40400000U), (5, 0xC0800000U), (0, 0x3F000000U) }, null, new (byte, uint)[] { (7, 0x41100000U) } } } }, 8, new uint[] { 0x00000000U, 0x00000000U, 0x00000000U, 0x00000000U, 0x40400000U, 0x00000000U, 0x00000000U }),
        ["mask10"] = (new[] { new BusNodeSpec { B46 = 1, States = new (byte, uint)[]?[] { new (byte, uint)[] { (0, 0x3FC00000U), (6, 0x3E800000U), (2, 0x41200000U) }, new (byte, uint)[] { (3, 0x40000000U), (4, 0x40400000U), (5, 0xC0800000U), (0, 0x3F000000U) }, null, new (byte, uint)[] { (7, 0x41100000U) } } } }, 16, new uint[] { 0x00000000U, 0x00000000U, 0x00000000U, 0x00000000U, 0x00000000U, 0xC0800000U, 0x00000000U }),
        ["mask1f"] = (new[] { new BusNodeSpec { B46 = 1, States = new (byte, uint)[]?[] { new (byte, uint)[] { (0, 0x3FC00000U), (6, 0x3E800000U), (2, 0x41200000U) }, new (byte, uint)[] { (3, 0x40000000U), (4, 0x40400000U), (5, 0xC0800000U), (0, 0x3F000000U) }, null, new (byte, uint)[] { (7, 0x41100000U) } } } }, 31, new uint[] { 0x40000000U, 0x00000000U, 0x41200000U, 0x40000000U, 0x40400000U, 0xC0800000U, 0x3E800000U }),
        ["gate_off"] = (new[] { new BusNodeSpec { States = new (byte, uint)[]?[] { new (byte, uint)[] { (0, 0x3FC00000U), (6, 0x3E800000U), (2, 0x41200000U) }, new (byte, uint)[] { (3, 0x40000000U), (4, 0x40400000U), (5, 0xC0800000U), (0, 0x3F000000U) }, null, new (byte, uint)[] { (7, 0x41100000U) } } } }, 31, new uint[] { 0x00000000U, 0x00000000U, 0x00000000U, 0x00000000U, 0x00000000U, 0x00000000U, 0x00000000U }),
        ["mask0"] = (new[] { new BusNodeSpec { B46 = 1, States = new (byte, uint)[]?[] { new (byte, uint)[] { (0, 0x3FC00000U), (6, 0x3E800000U), (2, 0x41200000U) }, new (byte, uint)[] { (3, 0x40000000U), (4, 0x40400000U), (5, 0xC0800000U), (0, 0x3F000000U) }, null, new (byte, uint)[] { (7, 0x41100000U) } } } }, 0, new uint[] { 0x00000000U, 0x00000000U, 0x00000000U, 0x00000000U, 0x00000000U, 0x00000000U, 0x00000000U }),
        ["no_list"] = (new[] { new BusNodeSpec { B46 = 1 } }, 31, new uint[] { 0x00000000U, 0x00000000U, 0x00000000U, 0x00000000U, 0x00000000U, 0x00000000U, 0x00000000U }),
        ["duplicate_id_first_wins"] = (new[] { new BusNodeSpec { B46 = 1, States = new (byte, uint)[]?[] { new (byte, uint)[] { (0, 0x3F800000U), (0, 0x40000000U) } } } }, 1, new uint[] { 0x3F800000U, 0x00000000U, 0x00000000U, 0x00000000U, 0x00000000U, 0x00000000U, 0x00000000U }),
    };

    public static readonly Dictionary<string, (BusNodeSpec[] Nodes, int Start, int Flag, uint P, RtpcValueSpec[] Values, RtpcSubSpec[] Subs, uint Expected, string[] Log)> C39DC = new()
    {
        ["p5_base"] = (new[] { new BusNodeSpec { Base = new (byte, uint)[] { (5, 0xC0600000U) } } }, 0, 0, 5, new RtpcValueSpec[] {  }, new RtpcSubSpec[] {  }, 0xC0600000U, Array.Empty<string>()),
        ["p0_base"] = (new[] { new BusNodeSpec { Base = new (byte, uint)[] { (0, 0xC0000000U) } } }, 0, 0, 0, new RtpcValueSpec[] {  }, new RtpcSubSpec[] {  }, 0xC0000000U, Array.Empty<string>()),
        ["p5_base_absent_id"] = (new[] { new BusNodeSpec { Base = new (byte, uint)[] { (0, 0x3F800000U), (2, 0x40E00000U) } } }, 0, 0, 5, new RtpcValueSpec[] {  }, new RtpcSubSpec[] {  }, 0x00000000U, Array.Empty<string>()),
        ["p5_no_base"] = (new[] { new BusNodeSpec {  } }, 0, 0, 5, new RtpcValueSpec[] {  }, new RtpcSubSpec[] {  }, 0x00000000U, Array.Empty<string>()),
        ["p5_base_plus_ranged_first_float"] = (new[] { new BusNodeSpec { Base = new (byte, uint)[] { (5, 0xC0600000U) }, Ranged = new (byte, uint)[] { (5, 0x3E800000U) } } }, 0, 0, 5, new RtpcValueSpec[] {  }, new RtpcSubSpec[] {  }, 0xC0500000U, Array.Empty<string>()),
        ["p5_ranged_absent"] = (new[] { new BusNodeSpec { Base = new (byte, uint)[] { (5, 0xC0600000U) }, Ranged = new (byte, uint)[] { (0, 0x3E800000U) } } }, 0, 0, 5, new RtpcValueSpec[] {  }, new RtpcSubSpec[] {  }, 0xC0600000U, Array.Empty<string>()),
        ["p5_ranged_only"] = (new[] { new BusNodeSpec { Ranged = new (byte, uint)[] { (5, 0x40200000U) } } }, 0, 0, 5, new RtpcValueSpec[] {  }, new RtpcSubSpec[] {  }, 0x40200000U, Array.Empty<string>()),
        ["p0_state_list"] = (new[] { new BusNodeSpec { B46 = 1, States = new (byte, uint)[]?[] { new (byte, uint)[] { (0, 0x3FC00000U), (6, 0x41100000U) }, new (byte, uint)[] { (0, 0x3F000000U) } } } }, 0, 0, 0, new RtpcValueSpec[] {  }, new RtpcSubSpec[] {  }, 0x40000000U, Array.Empty<string>()),
        ["p5_state_list"] = (new[] { new BusNodeSpec { B46 = 1, States = new (byte, uint)[]?[] { new (byte, uint)[] { (5, 0xBFC00000U), (6, 0x41100000U) }, new (byte, uint)[] { (5, 0xBF000000U) } } } }, 0, 0, 5, new RtpcValueSpec[] {  }, new RtpcSubSpec[] {  }, 0xC0000000U, Array.Empty<string>()),
        ["p5_state_list_gate_off"] = (new[] { new BusNodeSpec { States = new (byte, uint)[]?[] { new (byte, uint)[] { (5, 0xBFC00000U) } } } }, 0, 0, 5, new RtpcValueSpec[] {  }, new RtpcSubSpec[] {  }, 0x00000000U, Array.Empty<string>()),
        ["p5_duck_max_wins"] = (new[] { new BusNodeSpec { DuckA8 = new uint[] { 0xC1900000U } } }, 0, 0, 5, new RtpcValueSpec[] {  }, new RtpcSubSpec[] {  }, 0xC1900000U, Array.Empty<string>()),
        ["p5_duck_sum_above_floor"] = (new[] { new BusNodeSpec { DuckA8 = new uint[] { 0xC1900000U, 0xC0C00000U } } }, 0, 0, 5, new RtpcValueSpec[] {  }, new RtpcSubSpec[] {  }, 0xC1C00000U, Array.Empty<string>()),
        ["p5_duck_sum_positive"] = (new[] { new BusNodeSpec { DuckA8 = new uint[] { 0x40000000U, 0x40400000U } } }, 0, 0, 5, new RtpcValueSpec[] {  }, new RtpcSubSpec[] {  }, 0x40A00000U, Array.Empty<string>()),
        ["p5_duck_floor_above_sum"] = (new[] { new BusNodeSpec { DuckA8 = new uint[] { 0xC1900000U }, MaxDuck = 0xC1200000U } }, 0, 0, 5, new RtpcValueSpec[] {  }, new RtpcSubSpec[] {  }, 0xC1200000U, Array.Empty<string>()),
        ["p5_duck_equal"] = (new[] { new BusNodeSpec { DuckA8 = new uint[] { 0xC1200000U }, MaxDuck = 0xC1200000U } }, 0, 0, 5, new RtpcValueSpec[] {  }, new RtpcSubSpec[] {  }, 0xC1200000U, Array.Empty<string>()),
        ["p0_duck8c"] = (new[] { new BusNodeSpec { Duck8C = new uint[] { 0xC0400000U, 0xBF800000U }, DuckA8 = new uint[] { 0xC2480000U } } }, 0, 0, 0, new RtpcValueSpec[] {  }, new RtpcSubSpec[] {  }, 0xC0800000U, Array.Empty<string>()),
        ["p5_duck_nan_sum"] = (new[] { new BusNodeSpec { DuckA8 = new uint[] { 0x7FC00000U } } }, 0, 0, 5, new RtpcValueSpec[] {  }, new RtpcSubSpec[] {  }, 0x7FC00000U, Array.Empty<string>()),
        ["p5_all_terms"] = (new[] { new BusNodeSpec { B46 = 1, Base = new (byte, uint)[] { (5, 0xC0600000U) }, Ranged = new (byte, uint)[] { (5, 0x3E800000U) }, DuckA8 = new uint[] { 0xBF800000U }, States = new (byte, uint)[]?[] { new (byte, uint)[] { (5, 0x3F800000U) } } } }, 0, 0, 5, new RtpcValueSpec[] {  }, new RtpcSubSpec[] {  }, 0xC0500000U, Array.Empty<string>()),
        ["p5_flag0_stops_at_noncollapsed_parent"] = (new[] { new BusNodeSpec { Fx = new uint[] { 1, 0, 0, 0 }, Base = new (byte, uint)[] { (5, 0xC1200000U) } }, new BusNodeSpec { Bus = 0, Base = new (byte, uint)[] { (5, 0xBF800000U) } } }, 1, 0, 5, new RtpcValueSpec[] {  }, new RtpcSubSpec[] {  }, 0xBF800000U, Array.Empty<string>()),
        ["p5_flag0_continues_through_collapsed_parent"] = (new[] { new BusNodeSpec { Fx = new uint[] { 1, 0, 0, 0 }, Base = new (byte, uint)[] { (5, 0xC1A00000U) } }, new BusNodeSpec { Bus = 0, Base = new (byte, uint)[] { (5, 0xC1200000U) } }, new BusNodeSpec { Bus = 1, Base = new (byte, uint)[] { (5, 0xBF800000U) } } }, 2, 0, 5, new RtpcValueSpec[] {  }, new RtpcSubSpec[] {  }, 0xC1300000U, Array.Empty<string>()),
        ["p5_flag1_always_recurses"] = (new[] { new BusNodeSpec { Fx = new uint[] { 1, 0, 0, 0 }, Base = new (byte, uint)[] { (5, 0xC1200000U) } }, new BusNodeSpec { Bus = 0, Base = new (byte, uint)[] { (5, 0xBF800000U) } } }, 1, 1, 5, new RtpcValueSpec[] {  }, new RtpcSubSpec[] {  }, 0xC1300000U, Array.Empty<string>()),
        ["p5_flag2_is_not_1"] = (new[] { new BusNodeSpec { Fx = new uint[] { 1, 0, 0, 0 }, Base = new (byte, uint)[] { (5, 0xC1200000U) } }, new BusNodeSpec { Bus = 0, Base = new (byte, uint)[] { (5, 0xBF800000U) } } }, 1, 2, 5, new RtpcValueSpec[] {  }, new RtpcSubSpec[] {  }, 0xBF800000U, Array.Empty<string>()),
        ["p5_flag1_chain_of_three"] = (new[] { new BusNodeSpec { Base = new (byte, uint)[] { (5, 0xC0800000U) } }, new BusNodeSpec { Bus = 0, Base = new (byte, uint)[] { (5, 0xC0000000U) } }, new BusNodeSpec { Bus = 1, Base = new (byte, uint)[] { (5, 0xBF800000U) } } }, 2, 1, 5, new RtpcValueSpec[] {  }, new RtpcSubSpec[] {  }, 0xC0E00000U, Array.Empty<string>()),
        ["p5_rtpc_sum"] = (new[] { new BusNodeSpec { Base = new (byte, uint)[] { (5, 0xC0600000U) }, Mask = 0x20UL } }, 0, 0, 5, new RtpcValueSpec[] { new(900, 0x00000000U, true, 0x42480000U) }, new RtpcSubSpec[] { new(0, 5, 0, 1, new (uint, byte, (uint, uint, uint)[])[] { (900, 0, new (uint, uint, uint)[] { (0x00000000U, 0x3F000000U, 4), (0x42C80000U, 0x43488000U, 4) }) }) }, 0x42C20000U, new[] { "A14E28" }),
        ["p5_rtpc_bit_clear_no_call"] = (new[] { new BusNodeSpec { Base = new (byte, uint)[] { (5, 0xC0600000U) }, Mask = 0x10UL } }, 0, 0, 5, new RtpcValueSpec[] { new(900, 0x00000000U, true, 0x42480000U) }, new RtpcSubSpec[] { new(0, 5, 0, 1, new (uint, byte, (uint, uint, uint)[])[] { (900, 0, new (uint, uint, uint)[] { (0x00000000U, 0x3F000000U, 4), (0x42C80000U, 0x43488000U, 4) }) }) }, 0xC0600000U, Array.Empty<string>()),
        ["p0_rtpc_bit0"] = (new[] { new BusNodeSpec { Mask = 0x1UL } }, 0, 0, 0, new RtpcValueSpec[] { new(900, 0x00000000U, true, 0x42480000U) }, new RtpcSubSpec[] { new(0, 0, 0, 1, new (uint, byte, (uint, uint, uint)[])[] { (900, 0, new (uint, uint, uint)[] { (0x00000000U, 0x3F000000U, 4), (0x42C80000U, 0x43488000U, 4) }) }) }, 0x42C90000U, new[] { "A14E28" }),
        ["p5_rtpc_no_subscription_gives_zero"] = (new[] { new BusNodeSpec { Mask = 0x20UL } }, 0, 0, 5, new RtpcValueSpec[] { new(900, 0x00000000U, true, 0x42480000U) }, new RtpcSubSpec[] {  }, 0x00000000U, Array.Empty<string>()),
        ["p5_rtpc_two_curves_sum"] = (new[] { new BusNodeSpec { Mask = 0x20UL } }, 0, 0, 5, new RtpcValueSpec[] { new(900, 0x00000000U, true, 0x42480000U), new(901, 0x00000000U, true, 0x3F800000U) }, new RtpcSubSpec[] { new(0, 5, 0, 1, new (uint, byte, (uint, uint, uint)[])[] { (900, 0, new (uint, uint, uint)[] { (0x00000000U, 0x3F000000U, 4), (0x42C80000U, 0x43488000U, 4) }), (901, 0, new (uint, uint, uint)[] { (0x00000000U, 0x00000000U, 4), (0x42C80000U, 0x42C80000U, 4) }) }) }, 0x42CB0000U, new[] { "A14E28", "A14E28" }),
        ["p5_rtpc_two_curves_product"] = (new[] { new BusNodeSpec { Mask = 0x20UL } }, 0, 0, 5, new RtpcValueSpec[] { new(900, 0x00000000U, true, 0x42480000U), new(901, 0x00000000U, true, 0x3F800000U) }, new RtpcSubSpec[] { new(0, 5, 0, 2, new (uint, byte, (uint, uint, uint)[])[] { (900, 0, new (uint, uint, uint)[] { (0x00000000U, 0x3F000000U, 4), (0x42C80000U, 0x43488000U, 4) }), (901, 0, new (uint, uint, uint)[] { (0x00000000U, 0x00000000U, 4), (0x42C80000U, 0x42C80000U, 4) }) }) }, 0x42C90000U, new[] { "A14E28", "A14E28" }),
        ["p5_rtpc_stmg_default"] = (new[] { new BusNodeSpec { Mask = 0x20UL } }, 0, 0, 5, new RtpcValueSpec[] { new(900, 0x40800000U, false, 0x00000000U) }, new RtpcSubSpec[] { new(0, 5, 0, 1, new (uint, byte, (uint, uint, uint)[])[] { (900, 0, new (uint, uint, uint)[] { (0x00000000U, 0x3F000000U, 4), (0x42C80000U, 0x43488000U, 4) }) }) }, 0x41080000U, new[] { "A14E28" }),
        ["p5_rtpc_real_event_volume_curve"] = (new[] { new BusNodeSpec { Mask = 0x20UL } }, 0, 0, 5, new RtpcValueSpec[] { new(900, 0x00000000U, true, 0x3F000000U) }, new RtpcSubSpec[] { new(0, 5, 0, 1, new (uint, byte, (uint, uint, uint)[])[] { (900, 2, new (uint, uint, uint)[] { (0x00000000U, 0xBF800000U, 1), (0x3F800000U, 0x00000000U, 4) }) }) }, 0xC040B146U, new[] { "A14E28" }),
        ["p5_rtpc_absent_id_param5_calls_9e6748"] = (new[] { new BusNodeSpec { Mask = 0x20UL } }, 0, 0, 5, new RtpcValueSpec[] {  }, new RtpcSubSpec[] { new(0, 5, 0, 1, new (uint, byte, (uint, uint, uint)[])[] { (900, 0, new (uint, uint, uint)[] { (0x00000000U, 0x3F000000U, 4), (0x42C80000U, 0x43488000U, 4) }) }) }, 0x41680000U, new[] { "9E6748", "A14E28" }),
        ["p5_rtpc_absent_id_9e6748_zero_result"] = (new[] { new BusNodeSpec { Mask = 0x20UL } }, 0, 0, 5, new RtpcValueSpec[] {  }, new RtpcSubSpec[] { new(0, 5, 0, 1, new (uint, byte, (uint, uint, uint)[])[] { (900, 0, new (uint, uint, uint)[] { (0x00000000U, 0x3F000000U, 4), (0x42C80000U, 0x43488000U, 4) }) }) }, 0x3F000000U, new[] { "9E6748", "A14E28" }),
        ["p0_rtpc_absent_id_param0_skips"] = (new[] { new BusNodeSpec { Mask = 0x1UL } }, 0, 0, 0, new RtpcValueSpec[] {  }, new RtpcSubSpec[] { new(0, 0, 0, 1, new (uint, byte, (uint, uint, uint)[])[] { (900, 0, new (uint, uint, uint)[] { (0x00000000U, 0x3F000000U, 4), (0x42C80000U, 0x43488000U, 4) }) }) }, 0x00000000U, Array.Empty<string>()),
        ["p0_rtpc_absent_id_type1_calls_9e6748"] = (new[] { new BusNodeSpec { Mask = 0x1UL } }, 0, 0, 0, new RtpcValueSpec[] {  }, new RtpcSubSpec[] { new(0, 0, 1, 1, new (uint, byte, (uint, uint, uint)[])[] { (900, 0, new (uint, uint, uint)[] { (0x00000000U, 0x3F000000U, 4), (0x42C80000U, 0x43488000U, 4) }) }) }, 0x41680000U, new[] { "9E6748", "A14E28" }),
        ["p0_rtpc_absent_id_param0_skips_product"] = (new[] { new BusNodeSpec { Mask = 0x1UL } }, 0, 0, 0, new RtpcValueSpec[] { new(901, 0x00000000U, true, 0x40400000U) }, new RtpcSubSpec[] { new(0, 0, 0, 2, new (uint, byte, (uint, uint, uint)[])[] { (900, 0, new (uint, uint, uint)[] { (0x00000000U, 0x3F000000U, 4), (0x42C80000U, 0x43488000U, 4) }), (901, 0, new (uint, uint, uint)[] { (0x00000000U, 0x00000000U, 4), (0x42C80000U, 0x42C80000U, 4) }) }) }, 0x40400000U, new[] { "A14E28" }),
    };

    public static readonly Dictionary<string, (BusNodeSpec[] Nodes, uint Param, RtpcValueSpec[] Values, RtpcSubSpec[] Subs, uint Expected, string[] Log)> A11590 = new()
    {
        ["empty_table"] = (new[] { new BusNodeSpec {  } }, 3, new RtpcValueSpec[] {  }, new RtpcSubSpec[] {  }, 0x00000000U, Array.Empty<string>()),
        ["not_found_wrong_param"] = (new[] { new BusNodeSpec {  } }, 4, new RtpcValueSpec[] { new(900, 0x00000000U, true, 0x3F800000U) }, new RtpcSubSpec[] { new(0, 3, 0, 1, new (uint, byte, (uint, uint, uint)[])[] { (900, 0, new (uint, uint, uint)[] { (0x00000000U, 0x3F000000U, 4), (0x42C80000U, 0x43488000U, 4) }) }) }, 0x00000000U, Array.Empty<string>()),
        ["sum_one_curve"] = (new[] { new BusNodeSpec {  } }, 3, new RtpcValueSpec[] { new(900, 0x00000000U, true, 0x3F800000U) }, new RtpcSubSpec[] { new(0, 3, 0, 1, new (uint, byte, (uint, uint, uint)[])[] { (900, 0, new (uint, uint, uint)[] { (0x00000000U, 0x3F000000U, 4), (0x42C80000U, 0x43488000U, 4) }) }) }, 0x40200000U, new[] { "A14E28" }),
        ["accumulate_0_is_sum"] = (new[] { new BusNodeSpec {  } }, 3, new RtpcValueSpec[] { new(900, 0x00000000U, true, 0x3F800000U) }, new RtpcSubSpec[] { new(0, 3, 0, 0, new (uint, byte, (uint, uint, uint)[])[] { (900, 0, new (uint, uint, uint)[] { (0x00000000U, 0x3F000000U, 4), (0x42C80000U, 0x43488000U, 4) }) }) }, 0x40200000U, new[] { "A14E28" }),
        ["accumulate_3_is_sum"] = (new[] { new BusNodeSpec {  } }, 3, new RtpcValueSpec[] { new(900, 0x00000000U, true, 0x3F800000U) }, new RtpcSubSpec[] { new(0, 3, 0, 3, new (uint, byte, (uint, uint, uint)[])[] { (900, 0, new (uint, uint, uint)[] { (0x00000000U, 0x3F000000U, 4), (0x42C80000U, 0x43488000U, 4) }) }) }, 0x40200000U, new[] { "A14E28" }),
        ["product_two_curves"] = (new[] { new BusNodeSpec {  } }, 3, new RtpcValueSpec[] { new(900, 0x00000000U, true, 0x3F800000U), new(901, 0x00000000U, true, 0x40800000U) }, new RtpcSubSpec[] { new(0, 3, 0, 2, new (uint, byte, (uint, uint, uint)[])[] { (900, 0, new (uint, uint, uint)[] { (0x00000000U, 0x3F000000U, 4), (0x42C80000U, 0x43488000U, 4) }), (901, 0, new (uint, uint, uint)[] { (0x00000000U, 0x3F800000U, 4), (0x42C80000U, 0x424C0000U, 4) }) }) }, 0x40F00000U, new[] { "A14E28", "A14E28" }),
        ["sum_three_curves_order"] = (new[] { new BusNodeSpec {  } }, 3, new RtpcValueSpec[] { new(900, 0x00000000U, true, 0x3F800000U), new(901, 0x00000000U, true, 0x40400000U), new(902, 0x00000000U, true, 0x40A00000U) }, new RtpcSubSpec[] { new(0, 3, 0, 1, new (uint, byte, (uint, uint, uint)[])[] { (900, 0, new (uint, uint, uint)[] { (0x00000000U, 0x322BCC77U, 4), (0x42C80000U, 0x42C80000U, 4) }), (901, 0, new (uint, uint, uint)[] { (0x00000000U, 0x3F800000U, 4), (0x42C80000U, 0x42CA0000U, 4) }), (902, 0, new (uint, uint, uint)[] { (0x00000000U, 0xBF800000U, 4), (0x42C80000U, 0x42C60000U, 4) }) }) }, 0x41100000U, new[] { "A14E28", "A14E28", "A14E28" }),
        ["empty_curve_list_sum"] = (new[] { new BusNodeSpec {  } }, 3, new RtpcValueSpec[] {  }, new RtpcSubSpec[] { new(0, 3, 0, 1, new (uint, byte, (uint, uint, uint)[])[] {  }) }, 0x00000000U, Array.Empty<string>()),
        ["empty_curve_list_product"] = (new[] { new BusNodeSpec {  } }, 3, new RtpcValueSpec[] {  }, new RtpcSubSpec[] { new(0, 3, 0, 2, new (uint, byte, (uint, uint, uint)[])[] {  }) }, 0x3F800000U, Array.Empty<string>()),
        ["stmg_default_when_root_invalid"] = (new[] { new BusNodeSpec {  } }, 3, new RtpcValueSpec[] { new(900, 0x40C00000U, false, 0x42C60000U) }, new RtpcSubSpec[] { new(0, 3, 0, 1, new (uint, byte, (uint, uint, uint)[])[] { (900, 0, new (uint, uint, uint)[] { (0x00000000U, 0x3F000000U, 4), (0x42C80000U, 0x43488000U, 4) }) }) }, 0x41480000U, new[] { "A14E28" }),
        ["absent_param0_skip"] = (new[] { new BusNodeSpec {  } }, 0, new RtpcValueSpec[] {  }, new RtpcSubSpec[] { new(0, 0, 0, 0, new (uint, byte, (uint, uint, uint)[])[] { (900, 0, new (uint, uint, uint)[] { (0x00000000U, 0x3F000000U, 4), (0x42C80000U, 0x43488000U, 4) }) }) }, 0x00000000U, Array.Empty<string>()),
        ["absent_param7_skip"] = (new[] { new BusNodeSpec {  } }, 7, new RtpcValueSpec[] {  }, new RtpcSubSpec[] { new(0, 7, 0, 0, new (uint, byte, (uint, uint, uint)[])[] { (900, 0, new (uint, uint, uint)[] { (0x00000000U, 0x3F000000U, 4), (0x42C80000U, 0x43488000U, 4) }) }) }, 0x00000000U, Array.Empty<string>()),
        ["absent_param7_type2_skip"] = (new[] { new BusNodeSpec {  } }, 7, new RtpcValueSpec[] {  }, new RtpcSubSpec[] { new(0, 7, 2, 0, new (uint, byte, (uint, uint, uint)[])[] { (900, 0, new (uint, uint, uint)[] { (0x00000000U, 0x3F000000U, 4), (0x42C80000U, 0x43488000U, 4) }) }) }, 0x00000000U, Array.Empty<string>()),
        ["absent_param2_calls_9e6748_result1"] = (new[] { new BusNodeSpec {  } }, 2, new RtpcValueSpec[] {  }, new RtpcSubSpec[] { new(0, 2, 0, 0, new (uint, byte, (uint, uint, uint)[])[] { (900, 0, new (uint, uint, uint)[] { (0x00000000U, 0x3F000000U, 4), (0x42C80000U, 0x43488000U, 4) }) }) }, 0x41940000U, new[] { "9E6748", "A14E28" }),
        ["absent_param2_calls_9e6748_result0"] = (new[] { new BusNodeSpec {  } }, 2, new RtpcValueSpec[] {  }, new RtpcSubSpec[] { new(0, 2, 0, 0, new (uint, byte, (uint, uint, uint)[])[] { (900, 0, new (uint, uint, uint)[] { (0x00000000U, 0x3F000000U, 4), (0x42C80000U, 0x43488000U, 4) }) }) }, 0x3F000000U, new[] { "9E6748", "A14E28" }),
        ["absent_type1_param0_calls_9e6748"] = (new[] { new BusNodeSpec {  } }, 0, new RtpcValueSpec[] {  }, new RtpcSubSpec[] { new(0, 0, 1, 0, new (uint, byte, (uint, uint, uint)[])[] { (900, 0, new (uint, uint, uint)[] { (0x00000000U, 0x3F000000U, 4), (0x42C80000U, 0x43488000U, 4) }) }) }, 0x41940000U, new[] { "9E6748", "A14E28" }),
        ["real_event_volume_half"] = (new[] { new BusNodeSpec {  } }, 3, new RtpcValueSpec[] { new(900, 0x00000000U, true, 0x3F000000U) }, new RtpcSubSpec[] { new(0, 3, 0, 1, new (uint, byte, (uint, uint, uint)[])[] { (900, 2, new (uint, uint, uint)[] { (0x00000000U, 0xBF800000U, 1), (0x3F800000U, 0x00000000U, 4) }) }) }, 0xC040B146U, new[] { "A14E28" }),
        ["real_event_volume_stmg_default_zero"] = (new[] { new BusNodeSpec {  } }, 3, new RtpcValueSpec[] { new(900, 0x00000000U, false, 0x00000000U) }, new RtpcSubSpec[] { new(0, 3, 0, 1, new (uint, byte, (uint, uint, uint)[])[] { (900, 2, new (uint, uint, uint)[] { (0x00000000U, 0xBF800000U, 1), (0x3F800000U, 0x00000000U, 4) }) }) }, 0xC43F2770U, new[] { "A14E28" }),
        ["real_sum_two_curves_scaling2_and_scurve"] = (new[] { new BusNodeSpec {  } }, 3, new RtpcValueSpec[] { new(900, 0x00000000U, true, 0x3F400000U), new(901, 0x00000000U, true, 0x3E99999AU) }, new RtpcSubSpec[] { new(0, 3, 0, 1, new (uint, byte, (uint, uint, uint)[])[] { (900, 2, new (uint, uint, uint)[] { (0x00000000U, 0xBF800000U, 1), (0x3F800000U, 0x00000000U, 4) }), (901, 0, new (uint, uint, uint)[] { (0x00000000U, 0x00000000U, 5), (0x3F800000U, 0x3F800000U, 4) }) }) }, 0xBEFB4BB0U, new[] { "A14E28", "A14E28" }),
        ["real_product_scaling3"] = (new[] { new BusNodeSpec {  } }, 3, new RtpcValueSpec[] { new(902, 0x00000000U, true, 0x42480000U), new(901, 0x00000000U, true, 0x3F7FBE77U) }, new RtpcSubSpec[] { new(0, 3, 0, 2, new (uint, byte, (uint, uint, uint)[])[] { (902, 3, new (uint, uint, uint)[] { (0x00000000U, 0xC2700000U, 4), (0x42C80000U, 0x00000000U, 4) }), (901, 0, new (uint, uint, uint)[] { (0x00000000U, 0x00000000U, 5), (0x3F800000U, 0x3F800000U, 4) }) }) }, 0x0DA2406AU, new[] { "A14E28", "A14E28" }),
        ["real_sum_three_curves_float_order"] = (new[] { new BusNodeSpec {  } }, 3, new RtpcValueSpec[] { new(900, 0x00000000U, true, 0x3F7EB852U), new(901, 0x00000000U, true, 0x3F000000U), new(902, 0x00000000U, true, 0x41200000U) }, new RtpcSubSpec[] { new(0, 3, 0, 1, new (uint, byte, (uint, uint, uint)[])[] { (900, 2, new (uint, uint, uint)[] { (0x00000000U, 0xBF800000U, 1), (0x3F800000U, 0x00000000U, 4) }), (901, 0, new (uint, uint, uint)[] { (0x00000000U, 0x00000000U, 5), (0x3F800000U, 0x3F800000U, 4) }), (902, 3, new (uint, uint, uint)[] { (0x00000000U, 0xC2700000U, 4), (0x42C80000U, 0x00000000U, 4) }) }) }, 0x3EF7BE51U, new[] { "A14E28", "A14E28", "A14E28" }),
        ["real_nan_value_gives_last_point"] = (new[] { new BusNodeSpec {  } }, 3, new RtpcValueSpec[] { new(901, 0x00000000U, true, 0x7FC00000U) }, new RtpcSubSpec[] { new(0, 3, 0, 1, new (uint, byte, (uint, uint, uint)[])[] { (901, 0, new (uint, uint, uint)[] { (0x00000000U, 0x00000000U, 5), (0x3F800000U, 0x3F800000U, 4) }) }) }, 0x3F800000U, new[] { "A14E28" }),
    };

    /// <summary>vt+0x44 of the shipped vtables, read from the .so: the slot [vptr + 0x44] points at a body whose first instruction is mov r0,#n.</summary>
    public static readonly Dictionary<string, int> Vt44 = new()
    {
        ["Bus"] = 0,
        ["AudioDeviceBus"] = 12,
        ["Class1039EA8"] = 8,
        ["Class103A018"] = 7,
        ["Class103A198"] = 9,
        ["Class103A470"] = 6,
        ["Layer"] = 5,
        ["RandomSequence"] = 2,
        ["Sound"] = 3,
        ["Switch"] = 4,
        ["ActorMixer"] = 1,
    };

    /// <summary>The constructor 0x9C3620 on memory pre-filled with 0xAA: (category, word68, maxDuckBits, word54, byte46, byteCC, id, callee log).</summary>
    public static readonly Dictionary<int, (uint Word68, uint MaxDuck, uint Word54, byte B46, byte BCC, uint Id, string[] Log)> Ctor = new()
    {
        [0] = (0x00000000U, 0xC2C0999AU, 0x00000000U, 174, 48, 0x1234ABCDU, new[] { "9F402C", "A19F94", "9F40F4" }),
        [12] = (0x00000000U, 0xC2C0999AU, 0x00000000U, 174, 48, 0x1234ABCDU, new[] { "9F402C", "A19F94", "9F40F4" }),
        [10] = (0x00000000U, 0xC2C0999AU, 0x00000000U, 174, 48, 0x1234ABCDU, new[] { "9F402C", "A19F94", "9F40F4" }),
        [1] = (0x00000000U, 0xC2C0999AU, 0x00000000U, 170, 48, 0x1234ABCDU, new[] { "9F402C", "A19F94", "9F40F4" }),
        [3] = (0x00000000U, 0xC2C0999AU, 0x00000000U, 170, 48, 0x1234ABCDU, new[] { "9F402C", "A19F94", "9F40F4" }),
        [5] = (0x00000000U, 0xC2C0999AU, 0x00000000U, 170, 48, 0x1234ABCDU, new[] { "9F402C", "A19F94", "9F40F4" }),
    };

    /// <summary>0x9F5760: (slot, id, share, version, existing chunk (version, ids, shares) or null, allocation fails) -> (return, chunk after, callbacks).</summary>
    public static readonly Dictionary<string, (int Slot, uint Id, byte Share, int Version, (int Version, uint[] Ids, byte[] Share)? Chunk, bool Fail, uint Ret, (int Version, uint[] Ids, byte[] Share)? After, string[] Log)> Fx = new()
    {
        ["new_chunk_slot0"] = (0, 7, 1, 0, null, false, 1, (0, new uint[] { 7, 0, 0, 0 }, new byte[] { 1, 0, 0, 0 }), new string[] { "vtC4", "vt8C:0" }),
        ["new_chunk_slot3"] = (3, 9, 0, 5, null, false, 1, (5, new uint[] { 0, 0, 0, 9 }, new byte[] { 0, 0, 0, 0 }), new string[] { "vtC4", "vt8C:3" }),
        ["slot4_rejected"] = (4, 7, 1, 0, null, false, 31, null, Array.Empty<string>()),
        ["alloc_fails"] = (0, 7, 1, 0, null, true, 52, null, Array.Empty<string>()),
        ["same_values_no_callbacks"] = (0, 7, 1, 0, (0, new uint[] { 7, 0, 0, 0 }, new byte[] { 1, 0, 0, 0 }), false, 1, (0, new uint[] { 7, 0, 0, 0 }, new byte[] { 1, 0, 0, 0 }), Array.Empty<string>()),
        ["id_changes"] = (0, 8, 1, 0, (0, new uint[] { 7, 0, 0, 0 }, new byte[] { 1, 0, 0, 0 }), false, 1, (0, new uint[] { 8, 0, 0, 0 }, new byte[] { 1, 0, 0, 0 }), new string[] { "vtC4", "vt8C:0" }),
        ["share_changes"] = (0, 7, 0, 0, (0, new uint[] { 7, 0, 0, 0 }, new byte[] { 1, 0, 0, 0 }), false, 1, (0, new uint[] { 7, 0, 0, 0 }, new byte[] { 0, 0, 0, 0 }), new string[] { "vtC4", "vt8C:0" }),
        ["older_version_ignored"] = (0, 9, 0, 2, (3, new uint[] { 7, 0, 0, 0 }, new byte[] { 1, 0, 0, 0 }), false, 1, (3, new uint[] { 7, 0, 0, 0 }, new byte[] { 1, 0, 0, 0 }), Array.Empty<string>()),
        ["equal_version_applies"] = (1, 9, 1, 3, (3, new uint[] { 7, 0, 0, 0 }, new byte[] { 1, 0, 0, 0 }), false, 1, (3, new uint[] { 7, 9, 0, 0 }, new byte[] { 1, 1, 0, 0 }), new string[] { "vtC4", "vt8C:1" }),
        ["newer_version_stores_it"] = (1, 9, 1, 4, (3, new uint[] { 7, 0, 0, 0 }, new byte[] { 1, 0, 0, 0 }), false, 1, (4, new uint[] { 7, 9, 0, 0 }, new byte[] { 1, 1, 0, 0 }), new string[] { "vtC4", "vt8C:1" }),
        ["negative_version_chunk"] = (2, 4, 1, 0, (-1, new uint[] { 0, 0, 0, 0 }, new byte[] { 0, 0, 0, 0 }), false, 1, (0, new uint[] { 0, 0, 4, 0 }, new byte[] { 0, 0, 1, 0 }), new string[] { "vtC4", "vt8C:2" }),
    };

    /// <summary>0x9C0D08: (bytes, mixer result) -> (return, bytes consumed, [bus+0x40] after (starts 0x100), calls in order, chunk ids / shares or null).</summary>
    public static readonly Dictionary<string, (byte[] Data, int MixerRet, uint Ret, int Consumed, uint W40, string[] Log, (uint[] Ids, byte[] Share)? Chunk)> FxList = new()
    {
        ["count0_mixer"] = (new byte[] { 0, 0, 0, 0, 0, 0 }, 1, 1, 6, 0x0001F100U, new string[] { "mixer:0/0/0" }, null),
        ["count0_mixer_id_flag"] = (new byte[] { 0, 85, 0, 0, 0, 1 }, 1, 1, 6, 0x0001F100U, new string[] { "mixer:85/1/0" }, null),
        ["one_fx"] = (new byte[] { 1, 9, 0, 7, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0 }, 1, 1, 14, 0x0001F100U, new string[] { "vtC4", "vt8C:0", "9F5C30:9/4294967295", "mixer:0/0/0" }, (new uint[] { 7, 0, 0, 0 }, new byte[] { 1, 0, 0, 0 })),
        ["two_fx_one_zero_id"] = (new byte[] { 2, 9, 0, 0, 0, 0, 0, 1, 0, 2, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, 1, 1, 21, 0x0001F100U, new string[] { "vtC4", "vt8C:2", "9F5C30:9/4294967295", "mixer:0/0/0" }, (new uint[] { 0, 0, 8, 0 }, new byte[] { 0, 0, 0, 0 })),
        ["fx_slot_out_of_range"] = (new byte[] { 2, 9, 5, 7, 0, 0, 0, 1, 0, 1, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, 1, 31, 9, 0x0001F100U, new string[] { "9F5C30:9/4294967295" }, null),
        ["mixer_result_2"] = (new byte[] { 0, 85, 0, 0, 0, 0 }, 2, 2, 6, 0x0001F100U, new string[] { "mixer:85/0/0" }, null),
        ["three_fx"] = (new byte[] { 3, 4, 0, 1, 0, 0, 0, 1, 0, 1, 2, 0, 0, 0, 0, 0, 3, 3, 0, 0, 0, 1, 0, 102, 0, 0, 0, 1 }, 1, 1, 28, 0x0001F100U, new string[] { "vtC4", "vt8C:0", "vtC4", "vt8C:1", "vtC4", "vt8C:3", "9F5C30:4/4294967295", "mixer:102/1/0" }, (new uint[] { 1, 2, 0, 3 }, new byte[] { 1, 0, 0, 1 })),
    };

    /// <summary>The bus reader 0x9C6420 (count 0, A 0, F, u16, config word, C): (cfg, old [+0x68], F, C, [+0x40] in) -> ([+0x68], [+0x46] (starts 0x20), [+0x40], [+0xCC] (starts 0x30), 0xA4454C called, 0x9C62AC called).</summary>
    public static readonly Dictionary<string, (uint Cfg, uint Old, byte F, byte C, uint W40In, uint Word68, byte B46, uint W40, byte BCC, bool Changed, bool Bit3Call)> Reader = new()
    {
        ["mono_4101_f0_c0"] = (0x00004101U, 0x00000000U, 0, 0, 0x00000001U, 0x00004101U, 33, 0x00000001U, 48, true, false),
        ["mono_4101_f8_c3"] = (0x00004101U, 0x00000000U, 8, 3, 0x00000001U, 0x00004101U, 33, 0x000E0001U, 56, true, true),
        ["mono_4101_fF_c1"] = (0x00004101U, 0x00000000U, 15, 1, 0x00000001U, 0x00004101U, 33, 0x000E0001U, 48, true, true),
        ["mono_4101_f4_c2"] = (0x00004101U, 0x00000000U, 4, 2, 0x00000001U, 0x00004101U, 33, 0x00000001U, 56, true, false),
        ["unchanged_4101_f0_c0"] = (0x00004101U, 0x00004101U, 0, 0, 0x00000001U, 0x00004101U, 33, 0x00000001U, 48, false, false),
        ["unchanged_4101_f8_c3"] = (0x00004101U, 0x00004101U, 8, 3, 0x00000001U, 0x00004101U, 33, 0x000E0001U, 56, false, true),
        ["unchanged_4101_fF_c1"] = (0x00004101U, 0x00004101U, 15, 1, 0x00000001U, 0x00004101U, 33, 0x000E0001U, 48, false, true),
        ["unchanged_4101_f4_c2"] = (0x00004101U, 0x00004101U, 4, 2, 0x00000001U, 0x00004101U, 33, 0x00000001U, 56, false, false),
        ["byte_changed_f0_c0"] = (0x00004101U, 0x00004202U, 0, 0, 0x00000001U, 0x00004101U, 33, 0x00000001U, 48, true, false),
        ["byte_changed_f8_c3"] = (0x00004101U, 0x00004202U, 8, 3, 0x00000001U, 0x00004101U, 33, 0x000E0001U, 56, true, true),
        ["byte_changed_fF_c1"] = (0x00004101U, 0x00004202U, 15, 1, 0x00000001U, 0x00004101U, 33, 0x000E0001U, 48, true, true),
        ["byte_changed_f4_c2"] = (0x00004101U, 0x00004202U, 4, 2, 0x00000001U, 0x00004101U, 33, 0x00000001U, 56, true, false),
        ["nibble_changed_f0_c0"] = (0x00004101U, 0x00004001U, 0, 0, 0x00000001U, 0x00004101U, 33, 0x00000001U, 48, true, false),
        ["nibble_changed_f8_c3"] = (0x00004101U, 0x00004001U, 8, 3, 0x00000001U, 0x00004101U, 33, 0x000E0001U, 56, true, true),
        ["nibble_changed_fF_c1"] = (0x00004101U, 0x00004001U, 15, 1, 0x00000001U, 0x00004101U, 33, 0x000E0001U, 48, true, true),
        ["nibble_changed_f4_c2"] = (0x00004101U, 0x00004001U, 4, 2, 0x00000001U, 0x00004101U, 33, 0x00000001U, 56, true, false),
        ["hi_changed_f0_c0"] = (0x00004101U, 0x00008101U, 0, 0, 0x00000001U, 0x00004101U, 33, 0x00000001U, 48, true, false),
        ["hi_changed_f8_c3"] = (0x00004101U, 0x00008101U, 8, 3, 0x00000001U, 0x00004101U, 33, 0x000E0001U, 56, true, true),
        ["hi_changed_fF_c1"] = (0x00004101U, 0x00008101U, 15, 1, 0x00000001U, 0x00004101U, 33, 0x000E0001U, 48, true, true),
        ["hi_changed_f4_c2"] = (0x00004101U, 0x00008101U, 4, 2, 0x00000001U, 0x00004101U, 33, 0x00000001U, 56, true, false),
        ["stereo_3102_f0_c0"] = (0x00003102U, 0x00000000U, 0, 0, 0x00000001U, 0x00003102U, 33, 0x00000001U, 48, true, false),
        ["stereo_3102_f8_c3"] = (0x00003102U, 0x00000000U, 8, 3, 0x00000001U, 0x00003102U, 33, 0x000E0001U, 56, true, true),
        ["stereo_3102_fF_c1"] = (0x00003102U, 0x00000000U, 15, 1, 0x00000001U, 0x00003102U, 33, 0x000E0001U, 48, true, true),
        ["stereo_3102_f4_c2"] = (0x00003102U, 0x00000000U, 4, 2, 0x00000001U, 0x00003102U, 33, 0x00000001U, 56, true, false),
        ["kind0_byte_f0_c0"] = (0x00000007U, 0x00000000U, 0, 0, 0x00000001U, 0x00000007U, 33, 0x00000001U, 48, true, false),
        ["kind0_byte_f8_c3"] = (0x00000007U, 0x00000000U, 8, 3, 0x00000001U, 0x00000007U, 33, 0x000E0001U, 56, true, true),
        ["kind0_byte_fF_c1"] = (0x00000007U, 0x00000000U, 15, 1, 0x00000001U, 0x00000007U, 33, 0x000E0001U, 48, true, true),
        ["kind0_byte_f4_c2"] = (0x00000007U, 0x00000000U, 4, 2, 0x00000001U, 0x00000007U, 33, 0x00000001U, 56, true, false),
        ["kind0_hi_f0_c0"] = (0x12345603U, 0x00000000U, 0, 0, 0x00000001U, 0x12345603U, 33, 0x00000001U, 48, true, false),
        ["kind0_hi_f8_c3"] = (0x12345603U, 0x00000000U, 8, 3, 0x00000001U, 0x12345603U, 33, 0x000E0001U, 56, true, true),
        ["kind0_hi_fF_c1"] = (0x12345603U, 0x00000000U, 15, 1, 0x00000001U, 0x12345603U, 33, 0x000E0001U, 48, true, true),
        ["kind0_hi_f4_c2"] = (0x12345603U, 0x00000000U, 4, 2, 0x00000001U, 0x12345603U, 33, 0x00000001U, 56, true, false),
        ["kind1_masked_zero_f0_c0"] = (0x00040100U, 0x00000000U, 0, 0, 0x00000001U, 0x00000100U, 33, 0x00000001U, 48, true, false),
        ["kind1_masked_zero_f8_c3"] = (0x00040100U, 0x00000000U, 8, 3, 0x00000001U, 0x00000100U, 33, 0x000E0001U, 56, true, true),
        ["kind1_masked_zero_fF_c1"] = (0x00040100U, 0x00000000U, 15, 1, 0x00000001U, 0x00000100U, 33, 0x000E0001U, 48, true, true),
        ["kind1_masked_zero_f4_c2"] = (0x00040100U, 0x00000000U, 4, 2, 0x00000001U, 0x00000100U, 33, 0x00000001U, 56, true, false),
        ["kind1_mask_bits_f0_c0"] = (0xFFFFF100U, 0x00000000U, 0, 0, 0x00000001U, 0x3FF3F110U, 33, 0x00000001U, 48, true, false),
        ["kind1_mask_bits_f8_c3"] = (0xFFFFF100U, 0x00000000U, 8, 3, 0x00000001U, 0x3FF3F110U, 33, 0x000E0001U, 56, true, true),
        ["kind1_mask_bits_fF_c1"] = (0xFFFFF100U, 0x00000000U, 15, 1, 0x00000001U, 0x3FF3F110U, 33, 0x000E0001U, 48, true, true),
        ["kind1_mask_bits_f4_c2"] = (0xFFFFF100U, 0x00000000U, 4, 2, 0x00000001U, 0x3FF3F110U, 33, 0x00000001U, 56, true, false),
        ["kind1_three_bits_f0_c0"] = (0x0001D100U, 0xFFFFFFFFU, 0, 0, 0x00000001U, 0x0001D104U, 33, 0x00000001U, 48, true, false),
        ["kind1_three_bits_f8_c3"] = (0x0001D100U, 0xFFFFFFFFU, 8, 3, 0x00000001U, 0x0001D104U, 33, 0x000E0001U, 56, true, true),
        ["kind1_three_bits_fF_c1"] = (0x0001D100U, 0xFFFFFFFFU, 15, 1, 0x00000001U, 0x0001D104U, 33, 0x000E0001U, 48, true, true),
        ["kind1_three_bits_f4_c2"] = (0x0001D100U, 0xFFFFFFFFU, 4, 2, 0x00000001U, 0x0001D104U, 33, 0x00000001U, 56, true, false),
        ["kind2_same_as_old_f0_c0"] = (0x00005202U, 0x00005202U, 0, 0, 0x00000001U, 0x00005202U, 33, 0x00000001U, 48, false, false),
        ["kind2_same_as_old_f8_c3"] = (0x00005202U, 0x00005202U, 8, 3, 0x00000001U, 0x00005202U, 33, 0x000E0001U, 56, false, true),
        ["kind2_same_as_old_fF_c1"] = (0x00005202U, 0x00005202U, 15, 1, 0x00000001U, 0x00005202U, 33, 0x000E0001U, 48, false, true),
        ["kind2_same_as_old_f4_c2"] = (0x00005202U, 0x00005202U, 4, 2, 0x00000001U, 0x00005202U, 33, 0x00000001U, 56, false, false),
    };

    /// <summary>0x9BE898 with [ctx+0xD0] == 0 on a leaf under a root with pan properties 0.5 / -0.25 / 0.75: (E8, E9, pan floats in, [ctx+0xB4] in) -> (return, E8, pan bits, [ctx+0xB4], *out unchanged).</summary>
    public static readonly Dictionary<string, (byte E8, byte E9, uint[] PanIn, byte C0In, uint Ret, byte E8Out, uint[] PanOut, byte C0Out, bool OutUnchanged)> Be898 = new()
    {
        ["e9_bit2_clears"] = (0x5D, 5, new uint[] { 0x41100000U, 0x41000000U, 0x40E00000U }, 9, 2, 0x5C, new uint[] { 0x00000000U, 0x00000000U, 0x00000000U }, 0, true),
        ["e9_bit2_e8_low_bits"] = (0x5F, 4, new uint[] { 0x3F800000U, 0x40000000U, 0x40400000U }, 1, 2, 0x5C, new uint[] { 0x00000000U, 0x00000000U, 0x00000000U }, 0, true),
        ["bits01_eq1_runs_9fb9b8"] = (0x5D, 1, new uint[] { 0x00000000U, 0x00000000U, 0x00000000U }, 0, 2, 0x54, new uint[] { 0x3F000000U, 0xBE800000U, 0x3F400000U }, 0, true),
        ["bits01_eq1_other_e8"] = (0xA1, 0, new uint[] { 0x00000000U, 0x00000000U, 0x00000000U }, 0, 2, 0xA4, new uint[] { 0x3F000000U, 0xBE800000U, 0x3F400000U }, 0, true),
        ["bits01_not1_nothing"] = (0x5E, 1, new uint[] { 0x40800000U, 0x40A00000U, 0x40C00000U }, 3, 2, 0x5E, new uint[] { 0x40800000U, 0x40A00000U, 0x40C00000U }, 3, true),
        ["bits01_zero_nothing"] = (0x5C, 1, new uint[] { 0x40800000U, 0x40A00000U, 0x40C00000U }, 3, 2, 0x5C, new uint[] { 0x40800000U, 0x40A00000U, 0x40C00000U }, 3, true),
        ["bits01_eq3_nothing"] = (0x5F, 1, new uint[] { 0x40800000U, 0x40A00000U, 0x40C00000U }, 3, 2, 0x5F, new uint[] { 0x40800000U, 0x40A00000U, 0x40C00000U }, 3, true),
    };
}
