// <auto-generated> by re-analysis/tools/emu/emu_notify.py from the engine's own output (the real push 0xA38600 and flush 0xA38420 under Unicorn): do not edit. </auto-generated>
namespace Cozmo.Protocol.Tests;

internal static class NotificationQueueOracle
{
    /// <summary>name -> (array capacity, limit, free-list order, allocations that fail, the operations, the engine's result of each: "result | calls | queue state").</summary>
    public static readonly Dictionary<string, (int Capacity, uint Limit, int[] FreeOrder, int[] AllocFails, string[] Ops, string[] Steps)> Scenarios = new()
    {
        ["free_item_empty_queue"] = (3, 8u, new int[] { 0, 1, 2 }, new int[] {  }, new string[] { "push:100:3:0:1065353216" }, new string[] {
            "ok |  | head=0 tail=0 free=1,2 count=1 queue=0:100/3/0/1065353216" }),
        ["free_list_order_is_kept"] = (3, 8u, new int[] { 2, 0, 1 }, new int[] {  }, new string[] { "push:100:3:0:1", "push:101:3:1:2", "push:102:4:1:0" }, new string[] {
            "ok |  | head=2 tail=2 free=0,1 count=1 queue=2:100/3/0/1",
            "ok |  | head=2 tail=0 free=1 count=2 queue=2:100/3/0/1,0:101/3/1/2",
            "ok |  | head=2 tail=1 free= count=3 queue=2:100/3/0/1,0:101/3/1/2,1:102/4/1/0" }),
        ["four_pushes_third_array_then_heap"] = (2, 8u, new int[] { 0, 1 }, new int[] {  }, new string[] { "push:1:3:0:0", "push:2:3:0:0", "push:3:3:0:0", "push:4:4:1:0" }, new string[] {
            "ok |  | head=0 tail=0 free=1 count=1 queue=0:1/3/0/0",
            "ok |  | head=0 tail=1 free= count=2 queue=0:1/3/0/0,1:2/3/0/0",
            "ok | alloc | head=0 tail=2 free= count=3 queue=0:1/3/0/0,1:2/3/0/0,2:3/3/0/0",
            "ok | alloc | head=0 tail=3 free= count=4 queue=0:1/3/0/0,1:2/3/0/0,2:3/3/0/0,3:4/4/1/0" }),
        ["no_array_allocates_each_item"] = (0, 4u, new int[] {  }, new int[] {  }, new string[] { "push:1:3:0:0", "push:2:3:0:0" }, new string[] {
            "ok | alloc | head=0 tail=0 free= count=1 queue=0:1/3/0/0",
            "ok | alloc | head=0 tail=1 free= count=2 queue=0:1/3/0/0,1:2/3/0/0" }),
        ["limit_reached_flush_drains_then_reuses"] = (2, 2u, new int[] { 0, 1 }, new int[] {  }, new string[] { "push:1:3:0:0", "push:2:3:0:0", "push:3:3:0:0", "push:4:3:0:0" }, new string[] {
            "ok |  | head=0 tail=0 free=1 count=1 queue=0:1/3/0/0",
            "ok |  | head=0 tail=1 free= count=2 queue=0:1/3/0/0,1:2/3/0/0",
            "ok | h:1/3/0/0 h:2/3/0/0 | head=1 tail=1 free=0 count=1 queue=1:3/3/0/0",
            "ok |  | head=1 tail=0 free= count=2 queue=1:3/3/0/0,0:4/3/0/0" }),
        ["heap_items_full_flush_frees_then_allocates"] = (0, 1u, new int[] {  }, new int[] {  }, new string[] { "push:1:3:0:0", "push:2:3:0:0", "push:3:3:0:0" }, new string[] {
            "ok | alloc | head=0 tail=0 free= count=1 queue=0:1/3/0/0",
            "ok | h:1/3/0/0 free alloc | head=1 tail=1 free= count=1 queue=1:2/3/0/0",
            "ok | h:2/3/0/0 free alloc | head=2 tail=2 free= count=1 queue=2:3/3/0/0" }),
        ["alloc_fails_below_limit_flushes_then_allocates"] = (0, 4u, new int[] {  }, new int[] { 2 }, new string[] { "push:1:3:0:0", "push:2:3:0:0" }, new string[] {
            "ok | alloc | head=0 tail=0 free= count=1 queue=0:1/3/0/0",
            "ok | alloc h:1/3/0/0 free alloc | head=1 tail=1 free= count=1 queue=1:2/3/0/0" }),
        ["alloc_fails_twice_crashes"] = (0, 4u, new int[] {  }, new int[] { 2, 3 }, new string[] { "push:1:3:0:0", "push:2:3:0:0" }, new string[] {
            "ok | alloc | head=0 tail=0 free= count=1 queue=0:1/3/0/0",
            "crash | alloc h:1/3/0/0 free alloc | head=- tail=- free= count=0 queue=" }),
        ["limit_zero_crashes_when_empty"] = (0, 0u, new int[] {  }, new int[] {  }, new string[] { "push:1:3:0:0" }, new string[] {
            "crash |  | head=- tail=- free= count=0 queue=" }),
        ["limit_zero_with_free_array"] = (1, 0u, new int[] { 0 }, new int[] {  }, new string[] { "push:1:3:0:0", "push:2:3:0:0" }, new string[] {
            "ok |  | head=0 tail=0 free= count=1 queue=0:1/3/0/0",
            "ok | h:1/3/0/0 | head=0 tail=0 free= count=1 queue=0:2/3/0/0" }),
        ["flush_pops_in_order"] = (3, 8u, new int[] { 0, 1, 2 }, new int[] {  }, new string[] { "push:1:3:0:0", "push:2:5:1:0", "push:3:7:2:9", "flush", "push:4:3:0:0", "flush" }, new string[] {
            "ok |  | head=0 tail=0 free=1,2 count=1 queue=0:1/3/0/0",
            "ok |  | head=0 tail=1 free=2 count=2 queue=0:1/3/0/0,1:2/5/1/0",
            "ok |  | head=0 tail=2 free= count=3 queue=0:1/3/0/0,1:2/5/1/0,2:3/7/2/9",
            "flush | h:1/3/0/0 h:2/5/1/0 h:3/7/2/9 | head=- tail=- free=2,1,0 count=0 queue=",
            "ok |  | head=2 tail=2 free=1,0 count=1 queue=2:4/3/0/0",
            "flush | h:4/3/0/0 | head=- tail=- free=2,1,0 count=0 queue=" }),
        ["flush_empty"] = (2, 8u, new int[] { 0, 1 }, new int[] {  }, new string[] { "flush", "push:1:3:0:0", "flush", "flush" }, new string[] {
            "flush |  | head=- tail=- free=0,1 count=0 queue=",
            "ok |  | head=0 tail=0 free=1 count=1 queue=0:1/3/0/0",
            "flush | h:1/3/0/0 | head=- tail=- free=0,1 count=0 queue=",
            "flush |  | head=- tail=- free=0,1 count=0 queue=" }),
        ["flush_mixed_array_and_heap_items"] = (1, 8u, new int[] { 0 }, new int[] {  }, new string[] { "push:1:3:0:0", "push:2:3:0:0", "push:3:3:0:0", "flush", "push:4:3:0:0", "push:5:3:0:0", "flush" }, new string[] {
            "ok |  | head=0 tail=0 free= count=1 queue=0:1/3/0/0",
            "ok | alloc | head=0 tail=1 free= count=2 queue=0:1/3/0/0,1:2/3/0/0",
            "ok | alloc | head=0 tail=2 free= count=3 queue=0:1/3/0/0,1:2/3/0/0,2:3/3/0/0",
            "flush | h:1/3/0/0 h:2/3/0/0 free h:3/3/0/0 free | head=- tail=- free=0 count=0 queue=",
            "ok |  | head=0 tail=0 free= count=1 queue=0:4/3/0/0",
            "ok | alloc | head=0 tail=3 free= count=2 queue=0:4/3/0/0,3:5/3/0/0",
            "flush | h:4/3/0/0 h:5/3/0/0 free | head=- tail=- free=0 count=0 queue=" }),
        ["free_list_after_flush_is_lifo"] = (3, 8u, new int[] { 0, 1, 2 }, new int[] {  }, new string[] { "push:1:3:0:0", "push:2:3:0:0", "push:3:3:0:0", "flush", "push:4:3:0:0", "push:5:3:0:0" }, new string[] {
            "ok |  | head=0 tail=0 free=1,2 count=1 queue=0:1/3/0/0",
            "ok |  | head=0 tail=1 free=2 count=2 queue=0:1/3/0/0,1:2/3/0/0",
            "ok |  | head=0 tail=2 free= count=3 queue=0:1/3/0/0,1:2/3/0/0,2:3/3/0/0",
            "flush | h:1/3/0/0 h:2/3/0/0 h:3/3/0/0 | head=- tail=- free=2,1,0 count=0 queue=",
            "ok |  | head=2 tail=2 free=1,0 count=1 queue=2:4/3/0/0",
            "ok |  | head=2 tail=1 free=0 count=2 queue=2:4/3/0/0,1:5/3/0/0" }),
        ["wrap_negative_values"] = (2, 8u, new int[] { 0, 1 }, new int[] {  }, new string[] { "push:-1:-2:-2147483648:2147483647" }, new string[] {
            "ok |  | head=0 tail=0 free=1 count=1 queue=0:4294967295/4294967294/2147483648/2147483647" }),
    };
}
