// <auto-generated> by re-analysis/tools/emu/emu_reader.py from the engine's own output (the real reader 0x9BBB04..0x9BBF9C under Unicorn): do not edit. </auto-generated>
namespace Cozmo.Protocol.Tests;

internal static class BankReaderOracle
{
    /// <summary>name -> (config, the operations, the engine's result of each: "result | stream calls | reader state").</summary>
    public static readonly Dictionary<string, (ReaderConfig Config, string[] Ops, string[] Steps)> Scenarios = new()
    {
        ["mem_read_all"] = (new ReaderConfig { Memory = "030a11181f262d343b424950575e656c737a8188", StreamLength = 300, MinDirect = 64, Block = 16, Throughput = BitConverter.UInt32BitsToSingle(0x40000000U), Priority = 50, ReadFail = 0, WaitFail = 0, SkipFail = 0, ReadCap = -1, SkipCap = -1, Status = 0, AllocFail = 0 }, new string[] { "read:4", "read:100", "read:1" }, new string[] {
            "r=1 got=4 data=030a1118 |  | left=16 cur=0 mem=4 stream=0 temp=0",
            "r=1 got=16 data=1f262d343b424950575e656c737a8188 |  | left=0 cur=0 mem=20 stream=0 temp=0",
            "r=1 got=0 data= |  | left=0 cur=0 mem=20 stream=0 temp=0" }),
        ["mem_read_exact_left"] = (new ReaderConfig { Memory = "030a11181f262d343b424950575e656c737a8188", StreamLength = 300, MinDirect = 64, Block = 16, Throughput = BitConverter.UInt32BitsToSingle(0x40000000U), Priority = 50, ReadFail = 0, WaitFail = 0, SkipFail = 0, ReadCap = -1, SkipCap = -1, Status = 0, AllocFail = 0 }, new string[] { "read:20", "read:0" }, new string[] {
            "r=1 got=20 data=030a11181f262d343b424950575e656c737a8188 |  | left=0 cur=0 mem=20 stream=0 temp=0",
            "r=1 got=0 data= |  | left=0 cur=0 mem=20 stream=0 temp=0" }),
        ["mem_skip_then_read"] = (new ReaderConfig { Memory = "030a11181f262d343b424950575e656c737a8188", StreamLength = 300, MinDirect = 64, Block = 16, Throughput = BitConverter.UInt32BitsToSingle(0x40000000U), Priority = 50, ReadFail = 0, WaitFail = 0, SkipFail = 0, ReadCap = -1, SkipCap = -1, Status = 0, AllocFail = 0 }, new string[] { "skip:5", "read:6", "skip:100", "read:1" }, new string[] {
            "r=1 skipped=5 |  | left=15 cur=0 mem=5 stream=0 temp=0",
            "r=1 got=6 data=262d343b4249 |  | left=9 cur=0 mem=11 stream=0 temp=0",
            "r=1 skipped=9 |  | left=0 cur=0 mem=20 stream=0 temp=0",
            "r=1 got=0 data= |  | left=0 cur=0 mem=20 stream=0 temp=0" }),
        ["mem_window"] = (new ReaderConfig { Memory = "030a11181f262d343b424950575e656c737a8188", StreamLength = 300, MinDirect = 64, Block = 16, Throughput = BitConverter.UInt32BitsToSingle(0x40000000U), Priority = 50, ReadFail = 0, WaitFail = 0, SkipFail = 0, ReadCap = -1, SkipCap = -1, Status = 0, AllocFail = 0 }, new string[] { "window:4", "window:30", "window:1" }, new string[] {
            "p=mem+0 data=030a1118 |  | left=16 cur=0 mem=4 stream=0 temp=0",
            "p=mem+4 data=1f262d343b424950575e656c737a8188 |  | left=0 cur=0 mem=20 stream=0 temp=0",
            "p=mem+20 data= |  | left=0 cur=0 mem=20 stream=0 temp=0" }),
        ["mem_raw_short_0x38"] = (new ReaderConfig { Memory = "030a11181f262d343b424950575e656c737a8188", StreamLength = 300, MinDirect = 64, Block = 16, Throughput = BitConverter.UInt32BitsToSingle(0x40000000U), Priority = 50, ReadFail = 0, WaitFail = 0, SkipFail = 0, ReadCap = -1, SkipCap = -1, Status = 0, AllocFail = 0 }, new string[] { "raw:8", "raw:8", "raw:8" }, new string[] {
            "r=1 data=030a11181f262d34 |  | left=12 cur=0 mem=8 stream=0 temp=0",
            "r=1 data=3b424950575e656c |  | left=4 cur=0 mem=16 stream=0 temp=0",
            "r=56 data=737a8188eeeeeeee |  | left=0 cur=0 mem=20 stream=0 temp=0" }),
        ["mem_release"] = (new ReaderConfig { Memory = "030a11181f262d343b424950575e656c737a8188", StreamLength = 300, MinDirect = 64, Block = 16, Throughput = BitConverter.UInt32BitsToSingle(0x40000000U), Priority = 50, ReadFail = 0, WaitFail = 0, SkipFail = 0, ReadCap = -1, SkipCap = -1, Status = 0, AllocFail = 0 }, new string[] { "read:3", "release", "read:3" }, new string[] {
            "r=1 got=3 data=030a11 |  | left=17 cur=0 mem=3 stream=0 temp=0",
            "r=1 |  | left=0 cur=0 mem=-1 stream=0 temp=0",
            "r=1 got=0 data= |  | left=0 cur=0 mem=-1 stream=0 temp=0" }),
        ["mem_heur"] = (new ReaderConfig { Memory = "030a11181f262d343b424950575e656c737a8188", StreamLength = 300, MinDirect = 64, Block = 16, Throughput = BitConverter.UInt32BitsToSingle(0x40000000U), Priority = 50, ReadFail = 0, WaitFail = 0, SkipFail = 0, ReadCap = -1, SkipCap = -1, Status = 0, AllocFail = 0 }, new string[] { "heur:1.5:50", "heur:-1.0:50", "heur:1.0:101", "heur:0.0:100", "heur:2.0:200" }, new string[] {
            "r=1 thr=3fc00000 prio=50 |  | left=20 cur=0 mem=0 stream=0 temp=0",
            "r=31 thr=3fc00000 prio=50 |  | left=20 cur=0 mem=0 stream=0 temp=0",
            "r=31 thr=3fc00000 prio=50 |  | left=20 cur=0 mem=0 stream=0 temp=0",
            "r=1 thr=00000000 prio=100 |  | left=20 cur=0 mem=0 stream=0 temp=0",
            "r=31 thr=00000000 prio=100 |  | left=20 cur=0 mem=0 stream=0 temp=0" }),
        ["stream_small_reads_refill_window"] = (new ReaderConfig { Memory = null, StreamLength = 300, MinDirect = 64, Block = 16, Throughput = BitConverter.UInt32BitsToSingle(0x40000000U), Priority = 50, ReadFail = 0, WaitFail = 0, SkipFail = 0, ReadCap = -1, SkipCap = -1, Status = 0, AllocFail = 0 }, new string[] { "read:8", "read:8", "read:20", "read:40" }, new string[] {
            "r=1 got=8 data=030a11181f262d34 | r1C:64:42000000:50:f1 wait | left=56 cur=8 mem=-1 stream=1 temp=0",
            "r=1 got=8 data=3b424950575e656c |  | left=48 cur=16 mem=-1 stream=1 temp=0",
            "r=1 got=20 data=737a81888f969da4abb2b9c0c7ced5dce3eaf1f8 |  | left=28 cur=36 mem=-1 stream=1 temp=0",
            "r=1 got=40 data=ff060d141b222930373e454c535a61686f767d848b9299a0a7aeb5bcc3cad1d8dfe6edf4fb020910 | r1C:64:42000000:50:f1 wait | left=52 cur=12 mem=-1 stream=1 temp=0" }),
        ["stream_direct_read_multiple_of_block"] = (new ReaderConfig { Memory = null, StreamLength = 300, MinDirect = 64, Block = 16, Throughput = BitConverter.UInt32BitsToSingle(0x40000000U), Priority = 50, ReadFail = 0, WaitFail = 0, SkipFail = 0, ReadCap = -1, SkipCap = -1, Status = 0, AllocFail = 0 }, new string[] { "read:128", "read:5" }, new string[] {
            "r=1 got=128 data=030a11181f262d343b424950575e656c737a81888f969da4abb2b9c0c7ced5dce3eaf1f8ff060d141b222930373e454c535a61686f767d848b9299a0a7aeb5bcc3cad1d8dfe6edf4fb020910171e252c333a41484f565d646b727980878e959ca3aab1b8bfc6cdd4dbe2e9f0f7fe050c131a21282f363d444b525960676e757c | r1C:128:42800000:50:f1 wait | left=0 cur=0 mem=-1 stream=1 temp=0",
            "r=1 got=5 data=838a91989f | r1C:64:42000000:50:f1 wait | left=59 cur=5 mem=-1 stream=1 temp=0" }),
        ["stream_direct_read_with_remainder"] = (new ReaderConfig { Memory = null, StreamLength = 300, MinDirect = 64, Block = 16, Throughput = BitConverter.UInt32BitsToSingle(0x40000000U), Priority = 50, ReadFail = 0, WaitFail = 0, SkipFail = 0, ReadCap = -1, SkipCap = -1, Status = 0, AllocFail = 0 }, new string[] { "read:100", "read:3" }, new string[] {
            "r=1 got=100 data=030a11181f262d343b424950575e656c737a81888f969da4abb2b9c0c7ced5dce3eaf1f8ff060d141b222930373e454c535a61686f767d848b9299a0a7aeb5bcc3cad1d8dfe6edf4fb020910171e252c333a41484f565d646b727980878e959ca3aab1b8 | r1C:96:42400000:50:f1 wait r1C:64:42000000:50:f1 wait | left=60 cur=4 mem=-1 stream=1 temp=0",
            "r=1 got=3 data=bfc6cd |  | left=57 cur=7 mem=-1 stream=1 temp=0" }),
        ["stream_direct_short_returns_2"] = (new ReaderConfig { Memory = null, StreamLength = 150, MinDirect = 64, Block = 16, Throughput = BitConverter.UInt32BitsToSingle(0x40000000U), Priority = 50, ReadFail = 0, WaitFail = 0, SkipFail = 0, ReadCap = -1, SkipCap = -1, Status = 0, AllocFail = 0 }, new string[] { "read:200" }, new string[] {
            "r=1 got=150 data=030a11181f262d343b424950575e656c737a81888f969da4abb2b9c0c7ced5dce3eaf1f8ff060d141b222930373e454c535a61686f767d848b9299a0a7aeb5bcc3cad1d8dfe6edf4fb020910171e252c333a41484f565d646b727980878e959ca3aab1b8bfc6cdd4dbe2e9f0f7fe050c131a21282f363d444b525960676e757c838a91989fa6adb4bbc2c9d0d7dee5ecf3fa01080f16 | r1C:192:42c00000:50:f1 wait r1C:64:42000000:50:f1 wait | left=0 cur=0 mem=-1 stream=1 temp=0" }),
        ["stream_direct_short_below_min"] = (new ReaderConfig { Memory = null, StreamLength = 90, MinDirect = 64, Block = 16, Throughput = BitConverter.UInt32BitsToSingle(0x40000000U), Priority = 50, ReadFail = 0, WaitFail = 0, SkipFail = 0, ReadCap = -1, SkipCap = -1, Status = 0, AllocFail = 0 }, new string[] { "read:100" }, new string[] {
            "r=1 got=90 data=030a11181f262d343b424950575e656c737a81888f969da4abb2b9c0c7ced5dce3eaf1f8ff060d141b222930373e454c535a61686f767d848b9299a0a7aeb5bcc3cad1d8dfe6edf4fb020910171e252c333a41484f565d646b72 | r1C:96:42400000:50:f1 wait r1C:64:42000000:50:f1 wait | left=0 cur=0 mem=-1 stream=1 temp=0" }),
        ["stream_read_zero"] = (new ReaderConfig { Memory = null, StreamLength = 300, MinDirect = 64, Block = 16, Throughput = BitConverter.UInt32BitsToSingle(0x40000000U), Priority = 50, ReadFail = 0, WaitFail = 0, SkipFail = 0, ReadCap = -1, SkipCap = -1, Status = 0, AllocFail = 0 }, new string[] { "read:0" }, new string[] {
            "r=1 got=0 data= |  | left=0 cur=0 mem=-1 stream=1 temp=0" }),
        ["stream_eof_returns_short"] = (new ReaderConfig { Memory = null, StreamLength = 60, MinDirect = 32, Block = 16, Throughput = BitConverter.UInt32BitsToSingle(0x40000000U), Priority = 50, ReadFail = 0, WaitFail = 0, SkipFail = 0, ReadCap = -1, SkipCap = -1, Status = 0, AllocFail = 0 }, new string[] { "read:8", "read:50", "read:50" }, new string[] {
            "r=1 got=8 data=030a11181f262d34 | r1C:32:41800000:50:f1 wait | left=24 cur=8 mem=-1 stream=1 temp=0",
            "r=1 got=50 data=3b424950575e656c737a81888f969da4abb2b9c0c7ced5dce3eaf1f8ff060d141b222930373e454c535a61686f767d848b92 | r1C:32:41800000:50:f1 wait | left=2 cur=26 mem=-1 stream=1 temp=0",
            "r=2 got=2 data=99a0 | r1C:48:41c00000:50:f1 wait st | left=0 cur=28 mem=-1 stream=1 temp=0" }),
        ["stream_read_fail_9"] = (new ReaderConfig { Memory = null, StreamLength = 300, MinDirect = 64, Block = 16, Throughput = BitConverter.UInt32BitsToSingle(0x40000000U), Priority = 50, ReadFail = 1, WaitFail = 0, SkipFail = 0, ReadCap = -1, SkipCap = -1, Status = 0, AllocFail = 0 }, new string[] { "read:8", "read:8" }, new string[] {
            "r=9 got=0 data= | r1C:64:42000000:50:f1 | left=0 cur=0 mem=-1 stream=1 temp=0",
            "r=1 got=8 data=030a11181f262d34 | r1C:64:42000000:50:f1 wait | left=56 cur=8 mem=-1 stream=1 temp=0" }),
        ["stream_direct_read_fail"] = (new ReaderConfig { Memory = null, StreamLength = 300, MinDirect = 64, Block = 16, Throughput = BitConverter.UInt32BitsToSingle(0x40000000U), Priority = 50, ReadFail = 1, WaitFail = 0, SkipFail = 0, ReadCap = -1, SkipCap = -1, Status = 0, AllocFail = 0 }, new string[] { "read:100" }, new string[] {
            "r=9 got=0 data= | r1C:96:42400000:50:f1 | left=0 cur=0 mem=-1 stream=1 temp=0" }),
        ["stream_wait_fail_5"] = (new ReaderConfig { Memory = null, StreamLength = 300, MinDirect = 64, Block = 16, Throughput = BitConverter.UInt32BitsToSingle(0x40000000U), Priority = 50, ReadFail = 0, WaitFail = 1, SkipFail = 0, ReadCap = -1, SkipCap = -1, Status = 0, AllocFail = 0 }, new string[] { "read:8" }, new string[] {
            "r=1 got=0 data= | r1C:64:42000000:50:f1 wait | left=64 cur=0 mem=-1 stream=1 temp=0" }),
        ["stream_direct_wait_fail"] = (new ReaderConfig { Memory = null, StreamLength = 300, MinDirect = 64, Block = 16, Throughput = BitConverter.UInt32BitsToSingle(0x40000000U), Priority = 50, ReadFail = 0, WaitFail = 1, SkipFail = 0, ReadCap = -1, SkipCap = -1, Status = 0, AllocFail = 0 }, new string[] { "read:100" }, new string[] {
            "r=1 got=0 data= | r1C:96:42400000:50:f1 wait | left=0 cur=0 mem=-1 stream=1 temp=0" }),
        ["stream_read_cap"] = (new ReaderConfig { Memory = null, StreamLength = 300, MinDirect = 64, Block = 16, Throughput = BitConverter.UInt32BitsToSingle(0x40000000U), Priority = 50, ReadFail = 0, WaitFail = 0, SkipFail = 0, ReadCap = 24, SkipCap = -1, Status = 0, AllocFail = 0 }, new string[] { "read:8", "read:100" }, new string[] {
            "r=1 got=8 data=030a11181f262d34 | r1C:64:42000000:50:f1 wait | left=16 cur=8 mem=-1 stream=1 temp=0",
            "r=1 got=100 data=3b424950575e656c737a81888f969da4abb2b9c0c7ced5dce3eaf1f8ff060d141b222930373e454c535a61686f767d848b9299a0a7aeb5bcc3cad1d8dfe6edf4fb020910171e252c333a41484f565d646b727980878e959ca3aab1b8bfc6cdd4dbe2e9f0 | r1C:80:42200000:50:f1 wait r1C:64:42000000:50:f1 wait r1C:64:42000000:50:f1 wait r1C:64:42000000:50:f1 wait | left=12 cur=12 mem=-1 stream=1 temp=0" }),
        ["stream_raw_short_0x38"] = (new ReaderConfig { Memory = null, StreamLength = 250, MinDirect = 32, Block = 16, Throughput = BitConverter.UInt32BitsToSingle(0x40000000U), Priority = 50, ReadFail = 0, WaitFail = 0, SkipFail = 0, ReadCap = -1, SkipCap = -1, Status = 0, AllocFail = 0 }, new string[] { "raw:200", "raw:100" }, new string[] {
            "r=1 data=030a11181f262d343b424950575e656c737a81888f969da4abb2b9c0c7ced5dce3eaf1f8ff060d141b222930373e454c535a61686f767d848b9299a0a7aeb5bcc3cad1d8dfe6edf4fb020910171e252c333a41484f565d646b727980878e959ca3aab1b8bfc6cdd4dbe2e9f0f7fe050c131a21282f363d444b525960676e757c838a91989fa6adb4bbc2c9d0d7dee5ecf3fa01080f161d242b323940474e555c636a71787f868d949ba2a9b0b7bec5ccd3dae1e8eff6fd040b121920272e353c434a51585f666d74 | r1C:192:42c00000:50:f1 wait r1C:32:41800000:50:f1 wait | left=24 cur=8 mem=-1 stream=1 temp=0",
            "r=2 data=7b828990979ea5acb3bac1c8cfd6dde4ebf2f900070e151c232a31383f464d545b626970777e858c939aa1a8afb6bdc4cbd2eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee | r1C:64:42000000:50:f1 wait st | left=0 cur=32 mem=-1 stream=1 temp=0" }),
        ["stream_priority_and_throughput"] = (new ReaderConfig { Memory = null, StreamLength = 300, MinDirect = 32, Block = 16, Throughput = BitConverter.UInt32BitsToSingle(0x40800000U), Priority = 240, ReadFail = 0, WaitFail = 0, SkipFail = 0, ReadCap = -1, SkipCap = -1, Status = 0, AllocFail = 0 }, new string[] { "read:100" }, new string[] {
            "r=1 got=100 data=030a11181f262d343b424950575e656c737a81888f969da4abb2b9c0c7ced5dce3eaf1f8ff060d141b222930373e454c535a61686f767d848b9299a0a7aeb5bcc3cad1d8dfe6edf4fb020910171e252c333a41484f565d646b727980878e959ca3aab1b8 | r1C:96:41c00000:-16:f1 wait r1C:32:41000000:-16:f1 wait | left=28 cur=4 mem=-1 stream=1 temp=0" }),
        ["stream_skip_window_then_direct_skip"] = (new ReaderConfig { Memory = null, StreamLength = 400, MinDirect = 64, Block = 16, Throughput = BitConverter.UInt32BitsToSingle(0x40000000U), Priority = 50, ReadFail = 0, WaitFail = 0, SkipFail = 0, ReadCap = -1, SkipCap = -1, Status = 0, AllocFail = 0 }, new string[] { "read:4", "skip:3", "skip:200", "read:4" }, new string[] {
            "r=1 got=4 data=030a1118 | r1C:64:42000000:50:f1 wait | left=60 cur=4 mem=-1 stream=1 temp=0",
            "r=1 skipped=3 |  | left=57 cur=7 mem=-1 stream=1 temp=0",
            "r=1 skipped=200 | s28:143 | left=0 cur=64 mem=-1 stream=1 temp=0",
            "r=1 got=4 data=acb3bac1 | r1C:64:42000000:50:f1 wait | left=60 cur=4 mem=-1 stream=1 temp=0" }),
        ["stream_skip_small_refills"] = (new ReaderConfig { Memory = null, StreamLength = 400, MinDirect = 64, Block = 16, Throughput = BitConverter.UInt32BitsToSingle(0x40000000U), Priority = 50, ReadFail = 0, WaitFail = 0, SkipFail = 0, ReadCap = -1, SkipCap = -1, Status = 0, AllocFail = 0 }, new string[] { "skip:10", "skip:10", "read:4" }, new string[] {
            "r=1 skipped=10 | r1C:64:42000000:50:f1 wait st | left=54 cur=10 mem=-1 stream=1 temp=0",
            "r=1 skipped=10 |  | left=44 cur=20 mem=-1 stream=1 temp=0",
            "r=1 got=4 data=8f969da4 |  | left=40 cur=24 mem=-1 stream=1 temp=0" }),
        ["stream_skip_small_status_nonzero_short_2"] = (new ReaderConfig { Memory = null, StreamLength = 10, MinDirect = 64, Block = 16, Throughput = BitConverter.UInt32BitsToSingle(0x40000000U), Priority = 50, ReadFail = 0, WaitFail = 0, SkipFail = 0, ReadCap = -1, SkipCap = -1, Status = 1, AllocFail = 0 }, new string[] { "skip:30" }, new string[] {
            "r=2 skipped=0 | r1C:64:42000000:50:f1 wait st | left=10 cur=0 mem=-1 stream=1 temp=0" }),
        ["stream_skip_small_status_nonzero_enough"] = (new ReaderConfig { Memory = null, StreamLength = 100, MinDirect = 64, Block = 16, Throughput = BitConverter.UInt32BitsToSingle(0x40000000U), Priority = 50, ReadFail = 0, WaitFail = 0, SkipFail = 0, ReadCap = -1, SkipCap = -1, Status = 1, AllocFail = 0 }, new string[] { "skip:5" }, new string[] {
            "r=1 skipped=5 | r1C:64:42000000:50:f1 wait st | left=59 cur=5 mem=-1 stream=1 temp=0" }),
        ["stream_skip_fail"] = (new ReaderConfig { Memory = null, StreamLength = 400, MinDirect = 64, Block = 16, Throughput = BitConverter.UInt32BitsToSingle(0x40000000U), Priority = 50, ReadFail = 0, WaitFail = 0, SkipFail = 1, ReadCap = -1, SkipCap = -1, Status = 0, AllocFail = 0 }, new string[] { "skip:200" }, new string[] {
            "r=9 skipped=0 | s28:200 | left=0 cur=0 mem=-1 stream=1 temp=0" }),
        ["stream_skip_partial_cap"] = (new ReaderConfig { Memory = null, StreamLength = 400, MinDirect = 64, Block = 16, Throughput = BitConverter.UInt32BitsToSingle(0x40000000U), Priority = 50, ReadFail = 0, WaitFail = 0, SkipFail = 0, ReadCap = -1, SkipCap = 50, Status = 0, AllocFail = 0 }, new string[] { "skip:200", "read:4" }, new string[] {
            "r=1 skipped=200 | s28:200 s28:150 s28:100 r1C:64:42000000:50:f1 wait st | left=14 cur=50 mem=-1 stream=1 temp=0",
            "r=1 got=4 data=7b828990 |  | left=10 cur=54 mem=-1 stream=1 temp=0" }),
        ["stream_skip_zero"] = (new ReaderConfig { Memory = null, StreamLength = 400, MinDirect = 64, Block = 16, Throughput = BitConverter.UInt32BitsToSingle(0x40000000U), Priority = 50, ReadFail = 0, WaitFail = 0, SkipFail = 0, ReadCap = -1, SkipCap = -1, Status = 0, AllocFail = 0 }, new string[] { "skip:0" }, new string[] {
            "r=1 skipped=0 |  | left=0 cur=0 mem=-1 stream=1 temp=0" }),
        ["stream_skip_refill_read_fail"] = (new ReaderConfig { Memory = null, StreamLength = 400, MinDirect = 64, Block = 16, Throughput = BitConverter.UInt32BitsToSingle(0x40000000U), Priority = 50, ReadFail = 1, WaitFail = 0, SkipFail = 0, ReadCap = -1, SkipCap = -1, Status = 0, AllocFail = 0 }, new string[] { "skip:10" }, new string[] {
            "r=9 skipped=0 | r1C:64:42000000:50:f1 | left=0 cur=0 mem=-1 stream=1 temp=0" }),
        ["stream_skip_refill_wait_fail"] = (new ReaderConfig { Memory = null, StreamLength = 400, MinDirect = 64, Block = 16, Throughput = BitConverter.UInt32BitsToSingle(0x40000000U), Priority = 50, ReadFail = 0, WaitFail = 1, SkipFail = 0, ReadCap = -1, SkipCap = -1, Status = 0, AllocFail = 0 }, new string[] { "skip:10" }, new string[] {
            "r=1 skipped=0 | r1C:64:42000000:50:f1 wait | left=64 cur=0 mem=-1 stream=1 temp=0" }),
        ["stream_window_in_window"] = (new ReaderConfig { Memory = null, StreamLength = 300, MinDirect = 64, Block = 16, Throughput = BitConverter.UInt32BitsToSingle(0x40000000U), Priority = 50, ReadFail = 0, WaitFail = 0, SkipFail = 0, ReadCap = -1, SkipCap = -1, Status = 0, AllocFail = 0 }, new string[] { "read:2", "window:6", "window:6" }, new string[] {
            "r=1 got=2 data=030a | r1C:64:42000000:50:f1 wait | left=62 cur=2 mem=-1 stream=1 temp=0",
            "p=win+2 data=11181f262d34 |  | left=56 cur=8 mem=-1 stream=1 temp=0",
            "p=win+8 data=3b424950575e |  | left=50 cur=14 mem=-1 stream=1 temp=0" }),
        ["stream_window_alloc_copy"] = (new ReaderConfig { Memory = null, StreamLength = 300, MinDirect = 64, Block = 16, Throughput = BitConverter.UInt32BitsToSingle(0x40000000U), Priority = 50, ReadFail = 0, WaitFail = 0, SkipFail = 0, ReadCap = -1, SkipCap = -1, Status = 0, AllocFail = 0 }, new string[] { "window:100", "freetemp", "freetemp" }, new string[] {
            "p=tmp+0 data= | alloc r1C:96:42400000:50:f1 wait r1C:64:42000000:50:f1 wait | left=60 cur=4 mem=-1 stream=1 temp=1",
            " | free | left=60 cur=4 mem=-1 stream=1 temp=0",
            " |  | left=60 cur=4 mem=-1 stream=1 temp=0" }),
        ["stream_window_alloc_pad"] = (new ReaderConfig { Memory = null, StreamLength = 300, MinDirect = 64, Block = 16, Throughput = BitConverter.UInt32BitsToSingle(0x40000000U), Priority = 50, ReadFail = 0, WaitFail = 0, SkipFail = 0, ReadCap = -1, SkipCap = -1, Status = 0, AllocFail = 0 }, new string[] { "read:3", "window:100" }, new string[] {
            "r=1 got=3 data=030a11 | r1C:64:42000000:50:f1 wait | left=61 cur=3 mem=-1 stream=1 temp=0",
            "p=tmp+3 data= | alloc r1C:64:42000000:50:f1 wait | left=25 cur=39 mem=-1 stream=1 temp=1" }),
        ["stream_window_alloc_fails"] = (new ReaderConfig { Memory = null, StreamLength = 300, MinDirect = 64, Block = 16, Throughput = BitConverter.UInt32BitsToSingle(0x40000000U), Priority = 50, ReadFail = 0, WaitFail = 0, SkipFail = 0, ReadCap = -1, SkipCap = -1, Status = 0, AllocFail = 1 }, new string[] { "window:100" }, new string[] {
            "p=null data= | alloc | left=0 cur=0 mem=-1 stream=1 temp=0" }),
        ["stream_window_short_read"] = (new ReaderConfig { Memory = null, StreamLength = 50, MinDirect = 32, Block = 16, Throughput = BitConverter.UInt32BitsToSingle(0x40000000U), Priority = 50, ReadFail = 0, WaitFail = 0, SkipFail = 0, ReadCap = -1, SkipCap = -1, Status = 0, AllocFail = 0 }, new string[] { "window:100" }, new string[] {
            "p=null data= | alloc r1C:96:42400000:50:f1 wait st free | left=0 cur=0 mem=-1 stream=1 temp=0" }),
        ["stream_release_closes_stream"] = (new ReaderConfig { Memory = null, StreamLength = 300, MinDirect = 64, Block = 16, Throughput = BitConverter.UInt32BitsToSingle(0x40000000U), Priority = 50, ReadFail = 0, WaitFail = 0, SkipFail = 0, ReadCap = -1, SkipCap = -1, Status = 0, AllocFail = 0 }, new string[] { "read:4", "release", "read:4" }, new string[] {
            "r=1 got=4 data=030a1118 | r1C:64:42000000:50:f1 wait | left=60 cur=4 mem=-1 stream=1 temp=0",
            "r=1 | rel | left=0 cur=4 mem=-1 stream=0 temp=0",
            "r=1 got=0 data= |  | left=0 cur=4 mem=-1 stream=0 temp=0" }),
    };
}

internal sealed class ReaderConfig
{
    public string? Memory { get; init; }
    public int StreamLength { get; init; }
    public uint MinDirect { get; init; }
    public uint Block { get; init; }
    public float Throughput { get; init; }
    public int Priority { get; init; }
    public int ReadFail { get; init; }
    public int WaitFail { get; init; }
    public int SkipFail { get; init; }
    public int ReadCap { get; init; }
    public int SkipCap { get; init; }
    public int Status { get; init; }
    public int AllocFail { get; init; }
}
