from pathlib import Path
import re, struct
root=Path(__file__).resolve().parent
native=(root/'20261009-sound-eq-parameter-graphs-native.txt').read_text(encoding='utf-8-sig')
old=(root/'20261008-sound-eq-coefficient-boundary-native.txt').read_text(encoding='utf-8-sig')
ins={}
for text in (old,native):
 for m in re.finditer(r'^([0-9A-F]{8}):\s+(\S+)\s+(.*)$',text,re.M):
  if m[2]!='raw=' and not m[2].startswith('raw='): ins[int(m[1],16)]=(m[2],m[3])
expected=set()
for a,z in re.findall(r'RANGE 0x([0-9A-F]+)..0x([0-9A-F]+) exclusive',native): expected.update(range(int(a,16),int(z,16),4))
actual={int(v,16) for v in re.findall(r'^([0-9A-F]{8}): (?!raw=)',native,re.M)}
assert expected==actual
out=['# EQ persistent coefficient dependency graphs','','Primary: `20261009-sound-eq-parameter-graphs-native.txt` plus the already positive type1 branch in `20261008-sound-eq-coefficient-boundary-native.txt`. Engine SHA256 02263c07f6bb60f4d7f351a3667dca84fd3e6c0fc6f838e18b5de7cf4e2989e1. Generated by `20261009-sound-eq-parameter-graphs.py` directly from the captured instructions. This is a research description, not production code or a numerical equivalence test. All offsets hex.','','Each vADDRESS names one native scalar operation. Copies remain aliases; raw constants use F32(hex). VMLA names the old destination before its two multiplicands, preserving association, including zero multiplication. Imported phone math arguments/call order and returned-value dependencies are exact; phone bodies remain external. SQ merges native VSQRT with its conditional imported sqrtf fallback; the comparison is the native result with itself. No PCM inputs, recurrence or sample loop.','','Entry inputs: P=plugin, tuple={kind at0,gain at4,frequency at8,Q atC}; band index is unchecked. Rate is unsigned P48 converted by AA2608. AA260C/2610 compute F32(F32(rate*F32(3F000000))*F32(3F666666)). AA2614/261C selects that cap when ordered frequency>=cap, otherwise keeps frequency, including unordered. Types0..6 select the branches below. Unsigned kind>6 goes directly to AA272C with incoming live coefficient registers, not an identity or error fallback. F9/F11 and LP434 own parameter and consumer joins.','','Types4/5 reload unsigned P48 after powf; other types use the converted entry rate. Default parameter kinds and concrete raw authored inputs are in LP434; this graph adds no inferred band names.','','Common output base=P+20(decimal)*band. Exact store order: AA2748 +4=s14/s11; AA2754 +8=s13/s11; AA275C +10=(-s16)/s11; AA2768 +14=(-s15)/s11; AA276C +C=s10/s11. Arithmetic interleaves as shown in each graph; VPOP at AA2760 does not restore s9..s15.','','out of scope: per-sample biquad arithmetic under ADP-1; allocator/storage infrastructure and excluded source branches under scope guard.']
imports={0x4d6778:'powf',0x4a415c:'cosf',0x4a4168:'sinf',0x4ab038:'tanf',0x4a4078:'sqrtf'}
fallback={0xaa26ac:('s18','s14',0xaa2a48),0xaa26d4:('s15','s19',0xaa2a78),0xaa29c0:('s18','s14',0xaa2a68),0xaa29e8:('s15','s19',0xaa2a58)}
ops=0; stores=0
for kind,a,z in [(0,0xaa27f0,0xaa2848),(1,0xaa2848,0xaa28a0),(2,0xaa28a0,0xaa28f0),(3,0xaa28f0,0xaa2944),(4,0xaa2648,0xaa272c),(5,0xaa295c,0xaa2a44),(6,0xaa2774,0xaa27f0)]:
 reg={'s12':'EntryRate','s18':'CappedFrequency'}; rows=[]
 def value(x):
  x=x.strip()
  if x.startswith('#'):
   return 'F32('+struct.pack('>f',float(x[1:])).hex().upper()+')'
  assert x in reg,(kind,hex(addr),x)
  return reg[x]
 for addr in list(range(a,z,4))+list(range(0xaa272c,0xaa2774,4)):
  mn,full=ins[addr]; operand=full.split(' ;')[0]; args=[v.strip() for v in operand.split(',')]
  node=f'v{addr:08X}'; expression=None
  if mn=='vldr':
   dest=args[0]
   lit=re.search(r'word\[[^]]+\]=([0-9A-F]{8})',full)
   if lit: reg[dest]='F32('+lit[1]+')'
   elif '#0x48' in full: reg[dest]=f'RawU32(P48@{addr:08X})'
   elif re.search(r'\[r[26], #4\]',full): reg[dest]='Gain'
   elif '#0xc' in full: reg[dest]='Q'
   else: raise ValueError((hex(addr),full))
  elif mn in ('vmov','vmov.f32'):
   reg[args[0]]=value(args[1])
  elif mn=='mov' and args[0]=='r0': reg['r0']=f'RawU32({int(args[1][1:],0):08X})'
  elif mn=='movt' and args[0]=='r0':
   assert reg['r0']=='RawU32(00000000)'; reg['r0']='F32(41200000)'
  elif mn=='bl':
   target=int(args[0][1:],0); name=imports[target]
   vals=[value('r0')]+([value('r1')] if name=='powf' else [])
   expression=f'phone.{name}('+', '.join(vals)+')'; reg['r0']=node
  elif mn in ('vmul.f32','vnmul.f32','vadd.f32','vsub.f32','vdiv.f32','vneg.f32','vsqrt.f32','vcvt.f32.u32','vmla.f32'):
   vals=([value(args[0])] if mn=='vmla.f32' else [])+[value(x) for x in args[1:]]
   expression=mn+'('+', '.join(vals)+')'; reg[args[0]]=node
  elif addr in fallback:
   dest,src,call=fallback[addr]
   expression=f'SQ({value(dest)}; unordered({value(dest)},{value(dest)}) ? phone.sqrtf@{call:08X}({value(src)}) : native-result)'
   reg[dest]=node
  elif mn in ('str','vstr'):
   dest={0xaa2748:'+4',0xaa2754:'+8',0xaa275c:'+10',0xaa2768:'+14',0xaa276c:'+C'}[addr]
   rows.append(f'| {addr:08X} | P+20*band{dest} | publish {value(args[0])} |');stores+=1
  elif mn in ('b','vcmp.f32','vmrs','vpop','pop','add','mov'): pass
  else: raise ValueError((hex(addr),mn,full))
  if expression: rows.append(f'| {addr:08X} | {node} | {expression} |');ops+=1
 out+=['',f'## Type {kind}','','| Address | Result / destination | Native dependency |','|---|---|---|',*rows]
assert stores==35
out+=['',f'Generated {ops} operation/call/merge nodes and {stores} ordered persistent stores. Companion has {len(actual)} complete ARM instructions; reused type1 contributes22 instructions. No numerical measurement or fidelity promotion.','']
(root/'20261009-sound-eq-parameter-graphs.md').write_text('\n'.join(out),encoding='utf-8')
print(f'Validated {len(actual)} native instructions; generated {ops} nodes/{stores} stores across seven types')
