import json
from pathlib import Path

p=Path('re-analysis/research')
records=json.loads((p/'20261006-M1M2-missing-records.json').read_text(encoding='utf-8-sig'))
manifest=json.loads(Path('re-analysis/fidelity_manifest.json').read_text(encoding='utf-8'))
related=['M3-035','M4-003','M4-016','M11-053','M15-004','M15-028']
out=['| Requested record | Coverage | Residuals considered |','|---|---|---|']
counts={'M1-015':'shared lifetime/service/factory/reset residuals','M1-024':'repair mutation/RNG, FP/NaN, outer exceptions','M1-025':'nested recipients, entry/state writers, connection callbacks, telemetry, lock diagnostics','M1-029':'formatting, allocation, extreme length, exception destination','M1-031':'shared lifetime/service/factory/reset residuals','M1-041':'implicit on-idle/ready residual (no literal MISSING)','M1-044':'shared lifetime/service/factory/reset residuals','M1-045':'shared lifetime/service/factory/reset residuals','M1-046':'subscription vector, messaging retirement, callback descendants','M2-002':'implicit remaining uncertainty: delocalize, state callers, action lifecycle, polling/clock'}
for r in records: out.append(f"| {r['id']} | CHECKED | {counts[r['id']]} |")
out += ['', '# M1/M2 remaining-item ownership triage — 2026-10-06', '',
'Answers the operator’s 2026-10-06 request. Pull returned Already up to date. CHECKED denotes triage of every named residual, not recovery of every callee or approval to build. No upper-layer destructor internals were extended. No manifest, inventory, production code or fidelity status is changed; no commit is made in this research lane.', '',
'Categories: **HIGHER-LAYER** transfers recipient semantics to the named layer; **PHONE-RUNTIME** is only the identified unshipped runtime/state boundary; **M1-EXTRACT** retains shipped transport/app glue or shared support still requiring recovery/checking; **UNREACHABLE** is limited to the specifically bounded operation stated. Already extracted but unbuilt M1 slices are identified explicitly, rather than represented as unread code. Proposed NEW names are descriptive proposals, not allocated IDs.', '',
'Primary evidence: `resources/lib/armeabi-v7a/libcozmoEngine.so`, SHA-256 `02263c07f6bb60f4d7f351a3667dca84fd3e6c0fc6f838e18b5de7cf4e2989e1`; packaged `libc++_shared.so`, SHA-256 `8ac5090bbd0be7401af5fff6044ded6f1e6ced692fcd3581fa3cb937b519a16a`. Fresh bounded instruction transcripts: [native boundaries](20261006-M1M2-triage-native.txt), [additional boundaries](20261006-M1M2-triage-extra-native.txt). Previously checked rows: [D/E/T extraction](20261005-B-M1M2-blockers-extraction.md), [reader/teardown check](20261005-B-M1M2-rows-check.md), [real formatter extraction](20261005-M1-029-real-extraction.md). Earlier reports are leads at authority 6; their addresses identify primary code for manager checking. Ranges below using those earlier reports are boundary citations, not a claim to have reopened every function in this task.', '',
'## Current records quoted before the proposals', '', 'The following quotes are the current title, status, evidence and unresolved, taken after the pull. Historical paragraphs in unresolved do not override its current leading disposition.']
for r in records+ [r for r in manifest['records'] if r['id'] in related]:
    out += ['',f"### {r['id']}",'','```json',json.dumps({k:r[k] for k in ('id','title','status','evidence','unresolved')},ensure_ascii=False,indent=2),'```']
out += ['', '## Shared residuals: M1-015, M1-031, M1-044, M1-045', '',
'Every S row applies to every occurrence of the shared unresolved paragraph in these four records. This is ownership, not four separate missing implementations. The lower record retains its ordered invocation contract. A shared paragraph must not cause a disconnect-only record to claim that every recipient is on its own live path.', '',
'| Row / missing piece | Classification | Layer / proposed ownership | Primary boundary and reason |',
'|---|---|---|---|',
'| S1 higher-layer lifetime bindings: NV | HIGHER-LAYER | M3-device, existing M3-038; retain M3-035’s specific callback-discard contract | Robot ownership/delete boundary `005112D6..005112E4`; recipient identity `0050FD8C..0050FD90`. No new duplicate record needed; this triage does not reread its destructor. |',
'| S2 control/sensor/light/movement/cube-accel bindings; retained ResetDevices candidate | HIGHER-LAYER | M4-control, existing M4-026/027; ResetDevices mapping amendment to M4-027 | AbortAll `0051194C..0051198C`; component boundaries `005111EA..0051121A`, `005113E0..005113F6`, `00511428..00511488`, `00511500..00511510`. A managed blanket ResetDevices is a candidate, not proof of equivalent native ownership. |',
'| S3 animation bindings | HIGHER-LAYER | M5-animation, existing M5-037 | Robot boundary `00511524..0051154A`; retained streamer recipient citations `0057AF48..0057AFDA`, `0057B044..0057B0C2`. Ordering belongs to M1; retirement effects to M5. |',
'| S4 mood bindings | HIGHER-LAYER | M7-reactions, existing M7-023 | Robot null action-list store `00511150`, mood invocation `005111B6`; recipient entry `0067AE14`. Preserve cross-component nulling order; no recursive extension here. |',
'| S5 action queue and behavior container bindings | HIGHER-LAYER | M8-framework, existing M8-015/016 | Queue cancellation boundary `0053E6A8..0053E6E0`; behavior calls `0051112C`, `0051113A`. Child cancellation/results and behavior retirement are not socket teardown. |',
'| S6 classifier/filter/gyro bindings | HIGHER-LAYER | M10-strategies, existing M10-014 | Robot member retirement `0051121A..0051124C`, `00511418..00511424`; construction identity `0050FE1C..0050FE20`. |',
'| S7 vision/history/world/pose/map bindings | HIGHER-LAYER | M11-vision, existing M11-055 | Robot boundaries `0051115E..005111AC`, `0051124C..0051126A`, `005112CE`, `00511310..005113DE`. Thread join remains a shipped component obligation; not wholesale PHONE-RUNTIME. |',
'| S8 carrying/docking bindings | HIGHER-LAYER | M12-manipulation, existing M12-040 | After AbortAll, Robot `005113FA..00511414`; recipient entry `0063BE10`. |',
'| S9 planner bindings | HIGHER-LAYER | M13-navigation, existing M13-029 | Robot `0051127E..00511288`; recipient entries `00649100`, `00649220`. |',
'| S10 pet/face/speech bindings | HIGHER-LAYER | M14-social, existing M14-013 | Robot `0051128C..005112C6`, `005114A6..005114B4`. |',
'| S11 needs/AI/progression/inventory bindings | HIGHER-LAYER | M15-freeplay, existing M15-027 | Needs OnDisconnect `00695908..0069594A`, Robot `005111BE..005111EA`, `00511314..00511338`; ForceUpdate handoff `0056EEB8`. |',
'| S12 telemetry/context lifetime service effects | HIGHER-LAYER | M15-freeplay, existing M15-028 | Perf conditional stop `0050B734..0050B748`, DAS unpause `0052F2EE`, destructor event `005110EE`, members `0051155C..005115A2`, tail `005115F0`. These app telemetry call/field decisions ship; they are not automatically phone policy. |',
'| S13 external notification delivery, concrete external-interface sink | M1-EXTRACT | M1: proposed NEW External-interface disconnect/report delivery | RemoveRobot `0052F29E..0052F2EE`: virtual slot `+0x30` at `0052F2AC`, then notification construction/delivery and session handling. Concrete sink/subscribers UNKNOWN here. Virtual dispatch is shipped code, not proof that the behavior is outside the package. Separate any subsequently identified UI recipient into its own layer. |',
'| S14 go-to-sleep factory implementation and compound children | HIGHER-LAYER | M5-038 (animation factory), M4-028 (lift), M8-017 (compound); existing IDs | Caller `0052CE5E`; factory `0052CEA2..0052CFC0`, lift boundary `0052CF8E..0052CFB0`. M1 retains QueueAction NOW, retry count zero and call order. Child selection/order/failure belong to these records. Lift tolerance bits `40A00000`; factory duration bits `42700000`. |',
'| S15 generic channel/member subscription retirement | M1-EXTRACT | Existing M1-046, see Q rows | The shared phrase recursive recipients does not relocate messaging ownership. Robot `005112F2..00511308` crosses actual channel/member retirement. |',
'', '## M1-024: needs callback, FP state and escaping exceptions', '',
'| Row / missing piece | Classification | Layer / proposed ownership | Primary boundary and reason |', '|---|---|---|---|',
'| D1 D17 repair mutation and RNG | HIGHER-LAYER | M15-freeplay, proposed NEW Repair damage mutation and random-selection contract, alongside M15-004 | `0069C522` stores the f32 result; `0069C528` sets dirty byte `+0x88`; `0069C52E..0069C536` calls PossiblyDamageParts only for need id zero, with r1=1. Recipient entry/range `0069C5D8..0069C77A`; body intentionally not extended. M15-004 currently describes multipliers/count thresholds, not this mutation/RNG contract. |',
'| D2 global initial FP control state | PHONE-RUNTIME | Candidate external execution-environment assumption for needs f32 operations; not ADP-1 | Initial thread FPSCR rounding/DN/FZ is phone OS/hardware state, not a value supplied by ApplyDecay `0069C3C0..0069C560`. Its f32 opcodes and ordering ship and remain exact. Bounded caller has no FP-state write; a complete application-side writer search is not established by this task, so adoption is conditional on that check, not an assertion no writer exists. |',
'| D3 NaN payload/production of NaN operands | HIGHER-LAYER | M15-freeplay: proposed NEW Needs binary32 exceptional-value propagation; M15-001/004 input ownership | `0069C48A`, `0069C4A8..0069C4EE`, `0069C512..0069C544` are shipped comparisons, arithmetic, clamp and stores. Input bits and non-default NaN handling cannot all be externalized as FP environment. Payload/result under a fixed runtime mode still requires source/oracle checking; UNKNOWN. Only mode selection is D2. |',
'| D4 outer exception disposition | M1-EXTRACT | M1: proposed NEW Engine tick escaping-exception boundary | Tick caller `004ED4DE..004ED6C4`, thread runner `0065B3A8..0065B63E` and their unwind/LSDA/landing pads. Invocation order alone does not establish catch/terminate behavior. Recover shipped EH before separating eventual OS thread/process termination. |',
'', '## M1-025: SDK reset and state transitions', '',
'| Row / missing piece | Classification | Layer / proposed ownership | Primary boundary and reason |', '|---|---|---|---|',
'| E1 nested SDK reset recipient orchestration | HIGHER-LAYER | M8-framework: proposed NEW SDK reset recipient dispatch contract, with child contracts E2–E5 | ResetRobot `0065DCFC..0065DF98` invokes external-interface slot `+0x0C` repeatedly. M1 keeps the outer ExitSdkMode order/gates. Receiver effects and behavior activation are separate; actual subscriber targets require verification, not inferred from message names. |',
'| E2 RemoveDisableReactionsLock("sdk"), ActivateHighLevelActivity(1) | HIGHER-LAYER | M7-reactions proposed NEW SDK reaction-lock recipient; M15-freeplay proposed NEW SDK activity activation recipient | Dispatch sites `0065DD9A`, `0065DDBA`. Those behavioral state changes are outside M1 transport. Concrete receiver bodies UNKNOWN. |',
'| E3 EnableCubeSleep(1,1), EnableLightStates(false,-1), EnableLiftPower(true) | HIGHER-LAYER | M3-device proposed NEW SDK cube-sleep recipient; M4-control proposed NEW SDK light/lift-power reset recipients | Dispatch `0065DEA2`, `0065DECA`, `0065DF8C`. Cube/light sends require SDK byte +0x79 nonzero; ordinary external ExitMode clears it first. Skipped on that branch is not globally UNREACHABLE: ResetRobot has other shipped callers/state. |',
'| E4 camera settings, color images, custom marker/object deletion | HIGHER-LAYER | M11-vision proposed NEW SDK camera/custom-world reset recipients | `0065DEDE..0065DEFC` settings (auto true, exposure zero, gain bits `00000000`); `0065DF14` color false; `0065DF32` undefine custom markers; `0065DF4E` delete custom objects. Preserve send order; message names alone do not settle handlers. |',
'| E5 StopRobotForSdk | HIGHER-LAYER | M4-control proposed NEW SDK stop-recipient action/control contract | Dispatch `0065DF6A`; actual receiver/action effects UNKNOWN here. It is a shipped message handoff, not permission to substitute host StopAll. |',
'| E6 EnterSdkMode and SDK connection/state writers | M1-EXTRACT | M1: proposed NEW SDK mode entry and lifecycle state writers | SDK EnterMode `0065E104..0065E224`, ExitMode `0065E2A4..0065E43E`, OnDisconnect `0065E4D8..0065E620`, OnConnectionSuccess `0065E6E0..0065E940`, UiMessageHandler OnEnter `0066150C..00661538`; UI `+0xE1` and communication `+0x88` are independent bytes. Complete writers/callers UNKNOWN, not phone state. |',
'| E7 concrete SDK connection callbacks | M1-EXTRACT | M1: proposed NEW SDK connection callback virtual targets | Communication change `00663298..006632C4` invokes slot `+0x24` with old/new values; helper `0065FE16..0065FE24` selects UDP/TCP indices with mask6. Actual vtable targets UNKNOWN. Transport routing/callback semantics ship. |',
'| E8 SDK telemetry fields | HIGHER-LAYER | M15-freeplay proposed NEW SDK transition telemetry field contract; M15-028 covers lifetime adjunct only | Entry/exit lifecycle boundaries `0065E104..0065E224`, `0065E2A4..0065E43E`, UI exit `00661546..00661566`. Specific field construction/address sites UNKNOWN; no bulk claim that M15-028 already owns all SDK telemetry. |',
'| E9 PrintLockState | HIGHER-LAYER | M4-control proposed NEW Track-lock diagnostic enumeration | Function `006410D8..006413CA`; lock/unlock caller `0063FF02..0063FF24`. Tree traversal, ownership names and diagnostic ordering are shipped control behavior. M4-003/016 cover motor action semantics, not this whole diagnostic recipient. |',
'', '## M1-029: split shipped wrappers from runtime services', '',
'| Row / missing piece | Classification | Layer / proposed ownership | Primary boundary and reason |', '|---|---|---|---|',
'| J1 real asString dispatch and formatting wrapper | M1-EXTRACT | M1-029 retained; checked formatter rows F1–F8 exist, so remaining build/check work rather than a wholly unread function | `008E48B8..008E4902` real dispatch; formatter `008EBF7C..008EC038`. Precision17; capacity36; suffix .0 decision before comma-to-dot rewrite; nonfinite string choices are shipped. Live robot handler parses then calls asString at `0052D4DA` without checking field type. A JSON real in build reaches this path. Do not label the whole formatter UNREACHABLE from usual asset types. |',
'| J2 imported sprintf/snprintf/__isfinite body and formatting runtime state | PHONE-RUNTIME | Candidate M1-029 formatting-runtime assumption, explicitly separate from J1 | Imports at `008EBF98..008EBFBC`; bodies are undefined engine imports, supplied by phone libc rather than the packaged libc++ converter. Formatting algorithm/runtime locale behavior of these bodies does not ship in these artifacts. The app’s precision, cap, literal handling and comma rewrite do ship. Existing converter C-locale/nearest decision does not automatically approve every formatter assumption. |',
'| J3 real formatting on ParseFirmwareHeader integer-access subpath only | UNREACHABLE | No new record for this excluded sub-operation | `0052EA28..0052EAF4` obtains version/time via asUInt. That bounded file-header function does not call real asString. This local exclusion does not exclude J1 on the robot-supplied handler. |',
'| J4 allocation success/failure availability | PHONE-RUNTIME | Candidate memory-availability runtime boundary | Converter malloc/free call wrappers in packaged libc++ `0007E4BC..0007E516`, `0007E52C..0007E560` import phone allocation; available heap and whether allocation fails are runtime state. Code deciding what to do after failure is J5, not external. |',
'| J5 allocation-failure branch results, sentinel handling, Reader/string allocation exceptions | M1-EXTRACT | M1-029 support path; proposed NEW Firmware JSON allocation-failure contract if split needed | Packaged libc++ `0007E4BC..0007E516`, sentinel data `0009FD90`, failure use `0007EE66..0007EE80`, context `0007EC62..0007F202`; engine Reader `008E07A4..008E1ECA` and value/access/formatter allocation paths. Successful converter fixtures do not prove failure branches. Full mixed failure/throw path UNKNOWN; packaged libc++ throw behavior is shipped. |',
'| J6 enormous-input integer-counter wrap requiring more than 32-bit length | UNREACHABLE | Only such length-dependent branches on the two bounded firmware-input entry paths | File header max prefix0x800 (LoadFirmwareHeader `00677C3C..00677DE4`, prior checked loader rows); FirmwareVersion Unpack `007B908E..007B9092` calls `0071A8F6`, reads TWO count bytes at `0071A900..0071A904`, zero-extends via ldrh `0071A90C`, forwards count. Robot JSON length at most65535. This excludes >32-bit-length input, not long mantissas/exponents, deep nesting, allocation failure, or other general JSON users. |',
'| J7 extreme lengths within the reachable bound | M1-EXTRACT | M1-029 retained | Reader `008E07A4..008E1ECA`, packaged converter `0007E824..0007F202`; up to65535 robot JSON bytes still permits long numbers and depth-limit exceptions. Only specifically impossible counter-width cases are J6; no blanket extreme-length waiver. Converter successful long-input coverage already adopted; remaining Reader/string failure behavior stays UNKNOWN. |',
'| J8 final escaping exception destination | M1-EXTRACT | Proposed NEW Firmware JSON escaping-exception disposition, shared with D4 at tick boundary | Reader throw/access `008E09AA..008E0D92`; robot handler `0052D470..0052DA09`; header accessor `0052EA28..0052EAF4`; loader/proxy `00677C3C..00677DE4`, `0067861C..006786ED`, runner D4. Follow shipped unwinding/landing pads first. Eventual phone termination is not evidence for the entire path being external. |',
'', 'Round-to-nearest and converter decimal point C/. are already adopted EQUIVALENT_IMPLEMENTATION assumptions in the current quoted record, not additional MISSING items. This report neither changes them nor treats packaged libc++ conversion as an external body.',
'', '## M1-041, M1-046 and M2-002', '',
'| Row / missing piece | Classification | Layer / proposed ownership | Primary boundary and reason |', '|---|---|---|---|',
'| N1 M1-041 implicit on-idle callback execution / NV-idle predicate | HIGHER-LAYER | M3-device proposed NEW NV idle callback scheduling contract (or extend existing NV queue record after checking its exact claim) | Registration `00528A5A..00528A6E`; invocation boundary `00645C20..00645C32`; lambda `0052C3A6` stores ready before log `0052C3B6`. M3-035 governs discarded read callbacks, not all on-idle scheduling. No new lower M1 protocol required by this predicate alone. |',
'| N2 M1-041 ready-to-stream consumer lifecycle | HIGHER-LAYER | M5-animation proposed NEW Ready-to-stream animation lifecycle gate | Ready-byte store `0052C3A6`; SyncTimeAck `0053667E..005366AC`; current M1-041 already claims store/log and first-synced-state boundary. Full downstream streaming semantics belong to M5. Its old unresolved residual is not proof the now-built M1 store is absent. Exact downstream target span UNKNOWN in this bounded triage. |',
'| Q1 M1-046 Idle subscription vector retirement | M1-EXTRACT | Existing M1-046; amend its owner wording if necessary | Robot `005112F2..00511308` retires subscription/member storage. Generic scoped-handle destruction and unsubscribe targets UNKNOWN. Higher-layer recipient transfer is conditional on identifying a concrete subscriber, not on the word Idle. |',
'| Q2 M1-046 RobotToEngineImplMessaging retirement | M1-EXTRACT | Existing M1-046: concrete transport/channel owner | `00532A10..00532A78`: destroy map/tree members +0x144,+0x138,+0x110,+0x104; shared scoped-handle vector +0xF8 at `00532A48`; filebuf/ios retirement `00532A64..00532A6A`; tail at `00532A74`. This actual robot-message channel owner is not an upper behavior component. Scoped-handle deletion/unsubscribe descendants still UNKNOWN. |',
'| Q3 M1-046 behavior-changing subscriber descendants after retirement | M1-EXTRACT | M1-046 pending target identification; only identified upper targets get proposed per-layer recipient records | Caller ranges Q1/Q2 establish an unresolved dispatch boundary, not the final owner. Cannot name a fictitious higher-layer record for an unidentified callback. Concrete target/range UNKNOWN; retain M1 extraction to resolve, then split. |',
'| P1 M2-002 status0x2 Delocalize argument | HIGHER-LAYER | M11-vision, M11-053 amendment: explicit status/tread-boundary argument row | `00512B78..00512BA6`, call at `00512B98`; Delocalize `00510A24..00510D98`. M11-053 already explicitly describes this trigger bypass in its authority text, although its title highlights frame mismatch. Preserve actual boolean/argument computation and downstream ownership; no duplicate full Delocalize record. |',
'| P2 M2-002 GetRobotState callers / engine-to-game projection | M1-EXTRACT | M1 app tick/dispatch: proposed NEW Outgoing RobotState publication contract; M11 owns pose-derived inputs | `005180D8..00518252` getter; concrete caller `0052F6C0..0052F7B0` UpdateAllRobots updates each robot, gates HasReceivedRobotState, gets snapshot, constructs MessageEngineToGame then invokes external slot+0x1C. Tick entry `004ED648`. This is M1 glue still requiring caller/sink closure, not M2 raw status bit decoding. Other callers UNKNOWN; bounded caller found does not prove exhaustive callers. |',
'| P3 M2-002 complete queue-driven lifecycle | HIGHER-LAYER | M8-framework proposed NEW ActionList/ActionQueue and IAction lifecycle contract; M4-003/016 motor children, M8-015 cancellation/destruction adjunct | ActionList Update `0053F580..0053F5F2` calls ActionQueue Update `0053F5F4..0053F70C`; IActionRunner Update `00540370..0054063E`; IAction first-clock/timeout `00540D4A..00540E80`. Existing M8-012 is BehaviorManager tick/switching, NOT ActionQueue lifecycle; cannot silently assign full queue to it. Results/track locks/child order remain exact. |',
'| P4 M2-002 RunAsync polling and clock bridge | HIGHER-LAYER | Same proposed M8 queue/lifecycle record, linked to M4-016 and manipulation child ownership | Native action tick boundaries P3 and action CheckIfDone `005549B8..005549F4`, timeout bits `41F00000` (30.0f), result `03000018`. Host async scheduling is not proof that shipped action scheduling is PHONE-RUNTIME. Replace/validate bridge against native tick lifecycle; tests of local polling alone do not establish source fidelity. |',
'', '## Manager disposition', '',
'All explicit MISSING phrases and the implicit open residuals in M1-041/M2-002 are covered above. The shared paragraph is expanded once with all four origins named. No whole record is discarded or externalized. In particular, real formatting is reachable on the robot firmware JSON handler, channel retirement remains M1-owned until actual subscriber targets are identified, and SDK mode writers are shipped engine state.', '',
'Unknown callback targets, SDK telemetry field sites, complete application FP writers and final exception destinations are deliberately retained as gaps. The next extractor tasks are bounded by the cited M1 entry/caller ranges; this report does not request upper-layer destructor expansion. HIGHER-LAYER proposals identify boundary contracts only, with UNKNOWN recipient internals where not established. Manager checking is still required before inventory changes, build rows or settlement.']
(p/'20261006-M1M2-missing-triage.md').write_text('\n'.join(out)+'\n',encoding='utf-8')
